# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import robonix_runtime_pb2 as robonix__runtime__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in robonix_runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobonixRuntimeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterNode = channel.unary_unary(
                '/robonix.runtime.RobonixRuntime/RegisterNode',
                request_serializer=robonix__runtime__pb2.RegisterNodeRequest.SerializeToString,
                response_deserializer=robonix__runtime__pb2.RegisterNodeResponse.FromString,
                _registered_method=True)
        self.UnregisterNode = channel.unary_unary(
                '/robonix.runtime.RobonixRuntime/UnregisterNode',
                request_serializer=robonix__runtime__pb2.UnregisterNodeRequest.SerializeToString,
                response_deserializer=robonix__runtime__pb2.UnregisterNodeResponse.FromString,
                _registered_method=True)
        self.NodeHeartbeat = channel.unary_unary(
                '/robonix.runtime.RobonixRuntime/NodeHeartbeat',
                request_serializer=robonix__runtime__pb2.NodeHeartbeatRequest.SerializeToString,
                response_deserializer=robonix__runtime__pb2.NodeHeartbeatResponse.FromString,
                _registered_method=True)
        self.DeclareInterface = channel.unary_unary(
                '/robonix.runtime.RobonixRuntime/DeclareInterface',
                request_serializer=robonix__runtime__pb2.DeclareInterfaceRequest.SerializeToString,
                response_deserializer=robonix__runtime__pb2.DeclareInterfaceResponse.FromString,
                _registered_method=True)
        self.QueryNodes = channel.unary_unary(
                '/robonix.runtime.RobonixRuntime/QueryNodes',
                request_serializer=robonix__runtime__pb2.QueryNodesRequest.SerializeToString,
                response_deserializer=robonix__runtime__pb2.QueryNodesResponse.FromString,
                _registered_method=True)
        self.NegotiateChannel = channel.unary_unary(
                '/robonix.runtime.RobonixRuntime/NegotiateChannel',
                request_serializer=robonix__runtime__pb2.NegotiateChannelRequest.SerializeToString,
                response_deserializer=robonix__runtime__pb2.NegotiateChannelResponse.FromString,
                _registered_method=True)
        self.ReleaseChannel = channel.unary_unary(
                '/robonix.runtime.RobonixRuntime/ReleaseChannel',
                request_serializer=robonix__runtime__pb2.ReleaseChannelRequest.SerializeToString,
                response_deserializer=robonix__runtime__pb2.ReleaseChannelResponse.FromString,
                _registered_method=True)
        self.QuerySkillMd = channel.unary_unary(
                '/robonix.runtime.RobonixRuntime/QuerySkillMd',
                request_serializer=robonix__runtime__pb2.QuerySkillMdRequest.SerializeToString,
                response_deserializer=robonix__runtime__pb2.QuerySkillMdResponse.FromString,
                _registered_method=True)
        self.QueryAllSkills = channel.unary_unary(
                '/robonix.runtime.RobonixRuntime/QueryAllSkills',
                request_serializer=robonix__runtime__pb2.QueryAllSkillsRequest.SerializeToString,
                response_deserializer=robonix__runtime__pb2.QueryAllSkillsResponse.FromString,
                _registered_method=True)
        self.InspectRuntime = channel.unary_unary(
                '/robonix.runtime.RobonixRuntime/InspectRuntime',
                request_serializer=robonix__runtime__pb2.InspectRuntimeRequest.SerializeToString,
                response_deserializer=robonix__runtime__pb2.InspectRuntimeResponse.FromString,
                _registered_method=True)


class RobonixRuntimeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeHeartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeclareInterface(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NegotiateChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuerySkillMd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryAllSkills(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InspectRuntime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobonixRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=robonix__runtime__pb2.RegisterNodeRequest.FromString,
                    response_serializer=robonix__runtime__pb2.RegisterNodeResponse.SerializeToString,
            ),
            'UnregisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterNode,
                    request_deserializer=robonix__runtime__pb2.UnregisterNodeRequest.FromString,
                    response_serializer=robonix__runtime__pb2.UnregisterNodeResponse.SerializeToString,
            ),
            'NodeHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeHeartbeat,
                    request_deserializer=robonix__runtime__pb2.NodeHeartbeatRequest.FromString,
                    response_serializer=robonix__runtime__pb2.NodeHeartbeatResponse.SerializeToString,
            ),
            'DeclareInterface': grpc.unary_unary_rpc_method_handler(
                    servicer.DeclareInterface,
                    request_deserializer=robonix__runtime__pb2.DeclareInterfaceRequest.FromString,
                    response_serializer=robonix__runtime__pb2.DeclareInterfaceResponse.SerializeToString,
            ),
            'QueryNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryNodes,
                    request_deserializer=robonix__runtime__pb2.QueryNodesRequest.FromString,
                    response_serializer=robonix__runtime__pb2.QueryNodesResponse.SerializeToString,
            ),
            'NegotiateChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.NegotiateChannel,
                    request_deserializer=robonix__runtime__pb2.NegotiateChannelRequest.FromString,
                    response_serializer=robonix__runtime__pb2.NegotiateChannelResponse.SerializeToString,
            ),
            'ReleaseChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseChannel,
                    request_deserializer=robonix__runtime__pb2.ReleaseChannelRequest.FromString,
                    response_serializer=robonix__runtime__pb2.ReleaseChannelResponse.SerializeToString,
            ),
            'QuerySkillMd': grpc.unary_unary_rpc_method_handler(
                    servicer.QuerySkillMd,
                    request_deserializer=robonix__runtime__pb2.QuerySkillMdRequest.FromString,
                    response_serializer=robonix__runtime__pb2.QuerySkillMdResponse.SerializeToString,
            ),
            'QueryAllSkills': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryAllSkills,
                    request_deserializer=robonix__runtime__pb2.QueryAllSkillsRequest.FromString,
                    response_serializer=robonix__runtime__pb2.QueryAllSkillsResponse.SerializeToString,
            ),
            'InspectRuntime': grpc.unary_unary_rpc_method_handler(
                    servicer.InspectRuntime,
                    request_deserializer=robonix__runtime__pb2.InspectRuntimeRequest.FromString,
                    response_serializer=robonix__runtime__pb2.InspectRuntimeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robonix.runtime.RobonixRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robonix.runtime.RobonixRuntime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobonixRuntime(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.runtime.RobonixRuntime/RegisterNode',
            robonix__runtime__pb2.RegisterNodeRequest.SerializeToString,
            robonix__runtime__pb2.RegisterNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.runtime.RobonixRuntime/UnregisterNode',
            robonix__runtime__pb2.UnregisterNodeRequest.SerializeToString,
            robonix__runtime__pb2.UnregisterNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.runtime.RobonixRuntime/NodeHeartbeat',
            robonix__runtime__pb2.NodeHeartbeatRequest.SerializeToString,
            robonix__runtime__pb2.NodeHeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeclareInterface(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.runtime.RobonixRuntime/DeclareInterface',
            robonix__runtime__pb2.DeclareInterfaceRequest.SerializeToString,
            robonix__runtime__pb2.DeclareInterfaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.runtime.RobonixRuntime/QueryNodes',
            robonix__runtime__pb2.QueryNodesRequest.SerializeToString,
            robonix__runtime__pb2.QueryNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NegotiateChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.runtime.RobonixRuntime/NegotiateChannel',
            robonix__runtime__pb2.NegotiateChannelRequest.SerializeToString,
            robonix__runtime__pb2.NegotiateChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.runtime.RobonixRuntime/ReleaseChannel',
            robonix__runtime__pb2.ReleaseChannelRequest.SerializeToString,
            robonix__runtime__pb2.ReleaseChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QuerySkillMd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.runtime.RobonixRuntime/QuerySkillMd',
            robonix__runtime__pb2.QuerySkillMdRequest.SerializeToString,
            robonix__runtime__pb2.QuerySkillMdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryAllSkills(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.runtime.RobonixRuntime/QueryAllSkills',
            robonix__runtime__pb2.QueryAllSkillsRequest.SerializeToString,
            robonix__runtime__pb2.QueryAllSkillsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InspectRuntime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.runtime.RobonixRuntime/InspectRuntime',
            robonix__runtime__pb2.InspectRuntimeRequest.SerializeToString,
            robonix__runtime__pb2.InspectRuntimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
