[package]
name = "robonix-cli"
version = "0.1.0"
edition = "2024"
default-run = "rbnx"

[[bin]]
name = "rbnx"
path = "src/main.rs"

[[bin]]
name = "rbnx-daemon"
path = "src/daemon_main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.33"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
reqwest = { version = "0.13", features = ["json"] }
urlencoding = "2.1"
log = "0.4"
env_logger = "0.11"
dirs = "6.0.0"
pathdiff = "0.2"
chrono = "0.4"
git2 = { version = "0.20.2", default-features = false, features = ["https", "ssh"] }
hostname = "0.4"
regex = "1.10"
colored = "3.0.0"
[target.'cfg(unix)'.dependencies]
nix = { version = "0.31.1", features = ["signal", "process"] }
robonix-server = { path = "../robonix-server" }
ros2-client = { version = "0.8.2", features = ["pre-iron-gid"] }
rustdds = "0.11"

