#!/usr/bin/env bash
# SPDX-License-Identifier: MulanPSL-2.0
set -euo pipefail
PKG="${RBNX_PACKAGE_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
EXAMPLES="$(cd "$PKG/../.." && pwd)"
RUST_ROOT="$(cd "$EXAMPLES/.." && pwd)"
PROTO_GEN="$EXAMPLES/proto_gen"

if [[ "${RBNX_BUILD_CLEAN:-}" == "1" ]]; then
  rm -rf "$PKG/rbnx-build"
  rm -rf "$PKG/proto_stubs"
fi

# Generate proto stubs if grpcio-tools is available.
# If not found, fall back to proto_gen/ (must have been generated by another package).
PROTO_STUBS="$PKG/proto_stubs"
if python3 -m grpc_tools.protoc --version >/dev/null 2>&1; then
  echo "[build] generating proto stubs..."
  mkdir -p "$PROTO_STUBS"
  RUNTIME_DIR="$RUST_ROOT/proto"
  INTERFACES_DIR="$RUST_ROOT/robonix-interfaces/robonix_proto"
  python3 -m grpc_tools.protoc \
    -I "$RUNTIME_DIR" \
    -I "$INTERFACES_DIR" \
    --python_out="$PROTO_STUBS" \
    --grpc_python_out="$PROTO_STUBS" \
    "$RUNTIME_DIR/robonix_runtime.proto" \
    "$INTERFACES_DIR/vlm.proto" \
    "$INTERFACES_DIR/robonix_msg.proto" \
    "$INTERFACES_DIR/builtin_interfaces.proto" \
    "$INTERFACES_DIR/std_msgs.proto" \
    "$INTERFACES_DIR/geometry_msgs.proto" \
    "$INTERFACES_DIR/sensor_msgs.proto"
else
  echo "[build] grpcio-tools not found — using pre-generated stubs from proto_gen/"
  PROTO_STUBS="$PROTO_GEN"
fi

mkdir -p "$PKG/rbnx-build/ws/install"
cat >"$PKG/rbnx-build/ws/install/setup.bash" <<EOF
#!/usr/bin/env bash
export PYTHONPATH="$PKG:$PROTO_STUBS:$PROTO_GEN:\${PYTHONPATH:-}"
EOF

echo "[build] done."
