#!/usr/bin/env python3
"""ManiSkill3 environment bridge.

Dual-interface node:
  - gRPC EnvDataService (demo-local ``maniskill_env.proto`` — not a merged ``robonix_contracts`` service)
  - MCP tools: lightweight commands for robonix-pilot (contract IDs under ``rust/contracts``)
"""
import asyncio
import base64
import json
import logging
import os
import socket
import sys
import threading
import time
from concurrent import futures as _grpc_futures
from io import BytesIO
from pathlib import Path

from . import numpy_compat  # noqa: F401 — np.float shim before Sapien/transforms3d
import numpy as np
from PIL import Image as PILImage

for _n in (
    "mcp", "mcp.server", "mcp.server.streamable_http",
    "mcp.server.streamable_http_manager",
    "httpx", "httpcore", "uvicorn", "uvicorn.access",
):
    logging.getLogger(_n).setLevel(logging.WARNING)

def _ensure_proto_paths() -> None:
    pkg = Path(__file__).resolve().parent
    sys.path.insert(0, str(pkg))
    d = pkg
    while d.parent != d:
        pg = d / "proto_gen"
        if pg.is_dir() and (pg / "robonix_runtime_pb2.py").exists():
            sys.path.insert(0, str(pg))
            return
        d = d.parent


def _ensure_mcp_types() -> None:
    """Find robonix_mcp_types/ generated by robonix-codegen --lang mcp and add to path."""
    d = Path(__file__).resolve().parent
    while d.parent != d:
        mt = d / "robonix_mcp_types"
        if mt.is_dir() and (mt / "__init__.py").exists():
            if str(mt) not in sys.path:
                sys.path.insert(0, str(mt))
            return
        d = d.parent


def _ensure_robonix_py() -> None:
    """Add the shared Python helper lib (crates/robonix-py) to sys.path.

    Uses `rbnx path robonix-py` when available; falls back to PYTHONPATH
    injected by the package build.sh (rbnx-build/ws/install/setup.bash).
    """
    import subprocess
    try:
        out = subprocess.run(
            ["rbnx", "path", "robonix-py"],
            capture_output=True, text=True, timeout=5, check=False,
        )
        if out.returncode == 0:
            lib = Path(out.stdout.strip())
            if lib.is_dir() and str(lib) not in sys.path:
                sys.path.insert(0, str(lib))
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass  # rbnx not installed → rely on PYTHONPATH set by build.sh


_ensure_robonix_py()

from robonix_py import mcp_contract  # noqa: E402
from mcp.server.fastmcp import FastMCP  # noqa: E402

import grpc  # noqa: E402
import robonix_runtime_pb2 as pb  # noqa: E402
import robonix_runtime_pb2_grpc as pb_grpc  # noqa: E402
import maniskill_env_pb2 as env_pb  # noqa: E402
import maniskill_env_pb2_grpc as env_pb_grpc  # noqa: E402

# Contract IDL types (generated by robonix-codegen --lang mcp)
import std_msgs_mcp  # noqa: E402
import sensor_msgs_mcp  # noqa: E402
import prm_base_mcp  # noqa: E402
import geometry_msgs_mcp  # noqa: E402

# ── Global state ──────────────────────────────────────────────────────────────

mcp = FastMCP("maniskill-env")

_lock = threading.Lock()
_env = None
_latest_obs = None
_latest_done = False
_latest_reward = 0.0

# ── iceoryx2 publish loop (OBS_TRANSPORT=iceoryx2) ────────────────────────────

_IOX2_TRANSPORT = os.environ.get("OBS_TRANSPORT", "grpc").strip().lower() == "iceoryx2"


def _iox2_publish_loop(fps: float = 30.0) -> None:
    """Background thread: publish camera frames to iceoryx2 SHM at `fps`."""
    try:
        import iceoryx2 as iox2
    except ImportError:
        print("[env-node] ERROR: iceoryx2 not installed — pip install iceoryx2", file=sys.stderr)
        return

    from maniskill_vla_demo.iox2_types import (
        RgbCameraFrame, DepthCameraFrame,
        IOX2_SERVICE_RGB, IOX2_SERVICE_DEPTH,
    )

    node = iox2.NodeBuilder.new().create(iox2.ServiceType.Ipc)

    rgb_svc = (
        node.service_builder(iox2.ServiceName.new(IOX2_SERVICE_RGB))
            .publish_subscribe(RgbCameraFrame)
            .open_or_create()
    )
    depth_svc = (
        node.service_builder(iox2.ServiceName.new(IOX2_SERVICE_DEPTH))
            .publish_subscribe(DepthCameraFrame)
            .open_or_create()
    )
    rgb_pub   = rgb_svc.publisher_builder().create()
    depth_pub = depth_svc.publisher_builder().create()

    print(f"[env-node] iceoryx2 publisher ready: {IOX2_SERVICE_RGB}, {IOX2_SERVICE_DEPTH}",
          file=sys.stderr)

    seq = 0
    interval = 1.0 / fps
    while True:
        t0 = time.monotonic()
        with _lock:
            obs = _latest_obs
        if obs is not None:
            try:
                rgb, depth = _get_camera(obs)
                ts_ns = int(time.time() * 1e9)
                h, w = rgb.shape[:2]
                ch = rgb.shape[2] if rgb.ndim == 3 else 1

                # ── Publish RGB ───────────────────────────────────────────────
                frame_rgb = RgbCameraFrame(
                    width=w, height=h, channels=ch, seq=seq, ts_ns=ts_ns
                )
                n = min(len(rgb.tobytes()), len(frame_rgb.pixels))
                import ctypes
                ctypes.memmove(frame_rgb.pixels, rgb.tobytes(), n)
                rgb_pub.loan_uninit().write_payload(frame_rgb).send()

                # ── Publish Depth ─────────────────────────────────────────────
                if depth is not None:
                    import numpy as _np
                    depth_bytes = _np.ascontiguousarray(depth, dtype=_np.float32).tobytes()
                    frame_dep = DepthCameraFrame(
                        width=w, height=h, seq=seq, ts_ns=ts_ns
                    )
                    nd = min(len(depth_bytes), len(frame_dep.pixels))
                    ctypes.memmove(frame_dep.pixels, depth_bytes, nd)
                    depth_pub.loan_uninit().write_payload(frame_dep).send()

                seq += 1
            except Exception as exc:
                print(f"[env-node] iox2 publish error: {exc}", file=sys.stderr)

        elapsed = time.monotonic() - t0
        sleep_for = interval - elapsed
        if sleep_for > 0:
            time.sleep(sleep_for)

# ── Observation helpers ───────────────────────────────────────────────────────


def _to_np(t):
    if hasattr(t, "cpu"):
        return t.cpu().numpy()
    return np.asarray(t)


def _get_camera(obs):
    """Return (rgb, depth) arrays from the first available camera."""
    images = obs.get("sensor_data", obs.get("image", {}))
    if not images:
        raise KeyError("no image data in obs (expected 'sensor_data' or 'image' key)")
    cam = next(iter(images.values()))
    rgb = _to_np(cam["rgb"])
    depth = _to_np(cam.get("depth")) if "depth" in cam else None
    if rgb.ndim == 4:
        rgb = rgb[0]
    if depth is not None and depth.ndim == 4:
        depth = depth[0]
    rgb = np.ascontiguousarray(rgb[:, :, :3]).astype(np.uint8)
    if depth is not None:
        if depth.ndim == 3 and depth.shape[-1] == 1:
            depth = depth[:, :, 0]
        # ManiSkill returns depth as int16/uint16 in millimeters (per ManiSkill docs).
        # Convert to float32 meters so downstream consumers (RTAB-Map 32FC1,
        # Rerun DepthImage meter=1.0) all receive correct scale.
        depth = np.ascontiguousarray(depth).astype(np.float32) / 1000.0
    return rgb, depth


def _get_camera_intrinsics(obs):
    """Return (fx, fy, cx, cy) from the first camera's intrinsic_cv matrix."""
    params = obs.get("sensor_param", {})
    if not params:
        return None
    cam = next(iter(params.values()))
    K = _to_np(cam["intrinsic_cv"])
    if K.ndim == 3:
        K = K[0]
    return float(K[0, 0]), float(K[1, 1]), float(K[0, 2]), float(K[1, 2])


def _get_proprio(obs):
    agent = obs.get("agent", {})
    parts = []
    for k in ("qpos", "qvel"):
        v = agent.get(k)
        if v is not None:
            parts.extend(_to_np(v).flatten().tolist())
    return parts


def _get_camera_extrinsic(obs) -> list[float]:
    """Get T_world_camera (4×4, row-major) from ManiSkill sensor_param.

    ManiSkill's extrinsic_cv is the world-to-camera matrix (OpenCV convention).
    We invert it to get the camera-to-world transform needed by downstream
    consumers (TSDF, RTAB-Map, Rerun).

    Handles two layouts seen across ManiSkill versions / envs:
      • (4, 4) — full homogeneous world-to-camera matrix  (ideal)
      • (3, 4) — [R|t] submatrix, missing the [0,0,0,1] row
    GPU-sim observations also carry a leading batch dimension, so we strip
    any extra leading dimensions before processing.
    """
    params = obs.get("sensor_param", {})
    if not params:
        return []
    cam = next(iter(params.values()))
    ext = _to_np(cam["extrinsic_cv"]).astype(np.float64)

    # Strip leading batch dimensions (GPU sim prepends them even for 1 env).
    while ext.ndim > 2:
        ext = ext[0]

    # Some ManiSkill envs return the 3×4 [R|t] form rather than 4×4.
    if ext.shape == (3, 4):
        ext = np.vstack([ext, [0.0, 0.0, 0.0, 1.0]])

    if ext.shape != (4, 4):
        return []  # Unexpected shape — skip rather than crash

    T_world_cam = np.linalg.inv(ext)
    return T_world_cam.flatten().tolist()


def _get_extra(obs):
    """Extract extra info: tcp_pose, goal_pos, is_grasped."""
    extra = obs.get("extra", {})
    result = {}
    for k in ("tcp_pose", "goal_pos"):
        v = extra.get(k)
        if v is not None:
            result[k] = _to_np(v).flatten().tolist()
    if "is_grasped" in extra:
        result["is_grasped"] = _bool_scalar(extra["is_grasped"])
    return result


def _rgb_to_jpeg(rgb: np.ndarray) -> bytes:
    buf = BytesIO()
    PILImage.fromarray(rgb).save(buf, format="JPEG", quality=85)
    return buf.getvalue()


def _scalar(v):
    return float(v.item()) if hasattr(v, "item") else float(v)


def _bool_scalar(v):
    return bool(v.item() if hasattr(v, "item") else v)


def _step_env(action_list, repeat_steps: int = 1):
    """Step env under lock, return (obs, reward, done, info_dict).

    repeat_steps holds the same action for multiple simulator steps so motion
    is visible for small delta actions.
    """
    global _latest_obs, _latest_done, _latest_reward
    import torch

    act_dim = _env.action_space.shape[-1]
    while len(action_list) < act_dim:
        action_list.append(0.0)
    action = torch.tensor([action_list[:act_dim]], dtype=torch.float32)
    repeat_steps = max(1, min(int(repeat_steps), 200))
    r = 0.0
    done = False
    info = {}
    with _lock:
        for _ in range(repeat_steps):
            obs, reward, terminated, truncated, info = _env.step(action)
            _latest_obs = obs
            r += _scalar(reward)
            done = _bool_scalar(terminated) or _bool_scalar(truncated)
            _latest_done = done
            _latest_reward = float(r)
            if done:
                break
    info_dict = {}
    if "success" in info:
        info_dict["success"] = _bool_scalar(info["success"])
    info_dict["applied_steps"] = repeat_steps
    return obs, r, done, info_dict


def _reset_env():
    global _latest_obs, _latest_done, _latest_reward
    with _lock:
        obs, _ = _env.reset()
        _latest_obs = obs
        _latest_done = False
        _latest_reward = 0.0
    return obs


# ── MCP tools (one per contract) ─────────────────────────────────────────────

# Contract: robonix/prm/camera/snapshot
@mcp_contract(
    mcp,
    contract_id="robonix/prm/camera/snapshot",
)
def camera_snapshot(msg: std_msgs_mcp.Empty) -> sensor_msgs_mcp.Image:
    """Get current RGB camera image from the ManiSkill3 environment.
    Contract: robonix/prm/camera/snapshot.
    Returns sensor_msgs/Image (JPEG in `data`)."""
    _ = msg
    with _lock:
        obs = _latest_obs
    if obs is None:
        raise RuntimeError("environment not initialized")
    rgb, _ = _get_camera(obs)
    jpeg = _rgb_to_jpeg(rgb)
    return sensor_msgs_mcp.Image(
        width=int(rgb.shape[1]),
        height=int(rgb.shape[0]),
        encoding="jpeg",
        step=len(jpeg),
        data=jpeg,
    )


# Contract: robonix/prm/robot/state
@mcp_contract(
    mcp,
    contract_id="robonix/prm/robot/state",
)
def robot_state(msg: std_msgs_mcp.Empty) -> prm_base_mcp.RobotState:
    """Get robot state: joints, end-effector pose, gripper state.
    Contract: robonix/prm/robot/state.
    Fields: joint_state.position (proprio), tcp_pose (end-effector), is_grasped."""
    _ = msg
    with _lock:
        obs = _latest_obs
    if obs is None:
        raise RuntimeError("environment not initialized")
    extra = _get_extra(obs)
    proprio = _get_proprio(obs)

    state = prm_base_mcp.RobotState()
    state.joint_state.position = [float(v) for v in proprio]
    state.is_grasped = bool(extra.get("is_grasped", False))

    if "tcp_pose" in extra and len(extra["tcp_pose"]) >= 7:
        tp = extra["tcp_pose"]
        state.tcp_pose.pose.position.x = float(tp[0])
        state.tcp_pose.pose.position.y = float(tp[1])
        state.tcp_pose.pose.position.z = float(tp[2])
        state.tcp_pose.pose.orientation.x = float(tp[3])
        state.tcp_pose.pose.orientation.y = float(tp[4])
        state.tcp_pose.pose.orientation.z = float(tp[5])
        state.tcp_pose.pose.orientation.w = float(tp[6])

    return state


# Contract: robonix/prm/manipulation/exec
# input: std_msgs/msg/String  output: std_msgs/msg/String
# ``data`` is either a JSON array of floats, or ``{"action": [...], "hold_steps": 8}``.
@mcp_contract(
    mcp,
    contract_id="robonix/prm/manipulation/exec",
)
def manipulation_exec(msg: std_msgs_mcp.String) -> std_msgs_mcp.String:
    """Apply a manipulation action to the ManiSkill3 environment.
    Contract: robonix/prm/manipulation/exec.
    ``data``: JSON list of action floats (Fetch 12-DoF), or object with ``action`` and optional ``hold_steps``."""
    hold_steps = 8
    try:
        parsed = json.loads(msg.data)
    except Exception as e:
        return std_msgs_mcp.String(data=json.dumps({"error": f"invalid action JSON: {e}"}))
    if isinstance(parsed, dict):
        vals = parsed.get("action")
        if vals is None:
            vals = parsed.get("values")
        if vals is None and isinstance(parsed.get("data"), list):
            vals = parsed["data"]
        hold_steps = int(parsed.get("hold_steps", hold_steps))
        if vals is None:
            return std_msgs_mcp.String(
                data=json.dumps({"error": "expected JSON array or object with 'action' list"})
            )
    else:
        vals = parsed
    if not isinstance(vals, list):
        return std_msgs_mcp.String(data=json.dumps({"error": "action must be a JSON array of floats"}))
    _, r, done, info_dict = _step_env(vals, repeat_steps=hold_steps)
    result = {"reward": r, "done": done, "info": info_dict}
    return std_msgs_mcp.String(data=json.dumps(result))


def reset_env() -> str:
    """Reset the ManiSkill3 environment (not exposed as MCP tool)."""
    _reset_env()
    return json.dumps({"status": "reset_complete"})


# ── gRPC data service (for perception / VLA nodes) ───────────────────────────


def _obs_to_proto(obs, done=False, reward=0.0):
    """Build Observation protobuf from ManiSkill obs dict."""
    rgb, depth = _get_camera(obs)
    intrinsics = _get_camera_intrinsics(obs)
    extra = _get_extra(obs)
    kwargs = dict(
        rgb=rgb.tobytes(),
        depth=depth.tobytes() if depth is not None else b"",
        width=rgb.shape[1], height=rgb.shape[0],
        proprio=_get_proprio(obs),
        done=done, reward=reward,
    )
    if intrinsics:
        kwargs["fx"], kwargs["fy"], kwargs["cx"], kwargs["cy"] = intrinsics
    if "goal_pos" in extra:
        kwargs["goal_pos"] = extra["goal_pos"]
    cam_pose = _get_camera_extrinsic(obs)
    if cam_pose:
        kwargs["camera_pose"] = cam_pose
    tcp = _get_extra(obs).get("tcp_pose")
    if tcp:
        kwargs["tcp_pose"] = [float(v) for v in tcp]
    return env_pb.Observation(**kwargs)


class _EnvDataServicer(env_pb_grpc.EnvDataServiceServicer):

    def GetObs(self, request, context):
        with _lock:
            obs = _latest_obs
            done = _latest_done
            reward = _latest_reward
        if obs is None:
            context.abort(grpc.StatusCode.UNAVAILABLE, "env not initialized")
            return env_pb.Observation()
        return _obs_to_proto(obs, done=done, reward=reward)

    def Step(self, request, context):
        obs, r, done, info_dict = _step_env(list(request.values))
        obs_pb = _obs_to_proto(obs, done=done, reward=r)
        return env_pb.StepResult(
            obs=obs_pb, reward=r, done=done,
            info_json=json.dumps(info_dict),
        )

    def Reset(self, request, context):
        obs = _reset_env()
        return _obs_to_proto(obs)


# ── Boilerplate ──────────────────────────────────────────────────────────────


def _pick_port() -> int:
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    s.bind(("0.0.0.0", 0))
    p = s.getsockname()[1]
    s.close()
    return p


def _single_tool_meta(tool_name: str, description: str, input_schema: dict) -> str:
    return json.dumps({
        "tools": [{
            "name": tool_name,
            "description": description,
            "input_schema": input_schema,
        }]
    })


def _start_mcp_http(port: int) -> None:
    import uvicorn
    app = mcp.streamable_http_app()
    uvicorn.run(app, host="0.0.0.0", port=port, log_level="warning")


def _run_grpc_server(port: int) -> None:
    server = grpc.server(_grpc_futures.ThreadPoolExecutor(max_workers=4))
    env_pb_grpc.add_EnvDataServiceServicer_to_server(_EnvDataServicer(), server)
    server.add_insecure_port(f"0.0.0.0:{port}")
    server.start()
    print(f"[env-node] gRPC EnvDataService on :{port}", file=sys.stderr)
    server.wait_for_termination()


def _heartbeat_loop(stub, node_id: str) -> None:
    while True:
        time.sleep(15.0)
        try:
            stub.NodeHeartbeat(pb.NodeHeartbeatRequest(node_id=node_id))
        except Exception as e:
            print(f"[env-node] heartbeat failed: {e}", file=sys.stderr)


# ── Main ─────────────────────────────────────────────────────────────────────


def main() -> None:
    global _env, _latest_obs, _latest_done, _latest_reward

    import gymnasium as gym
    try:
        import mani_skill.envs  # noqa: F401 — registers ManiSkill envs
    except ImportError:
        print("[env-node] ERROR: mani_skill not installed.  pip install mani-skill", file=sys.stderr)
        sys.exit(1)

    # Auto-accept asset downloads (no stdin in background processes)
    os.environ["MS_SKIP_ASSET_DOWNLOAD_PROMPT"] = "1"

    env_id = os.environ.get("MANISKILL_ENV_ID", "ReplicaCADTidyHouseTrain_SceneManipulation-v1")
    control_mode = os.environ.get("MANISKILL_CONTROL_MODE", "pd_ee_delta_pose")
    cam_w = int(os.environ.get("MANISKILL_CAM_W", "640"))
    cam_h = int(os.environ.get("MANISKILL_CAM_H", "480"))
    # Shader presets: minimal (fastest), default (PBR-ish, more texture detail),
    # rt-fast / rt-med / rt (ray-traced, slowest, most photorealistic).
    shader_pack = os.environ.get("MANISKILL_SHADER_PACK", "default").strip()
    print(f"[env-node] creating ManiSkill3 env: {env_id}  control={control_mode}  robot=fetch  cam={cam_w}x{cam_h}  shader={shader_pack}",
          file=sys.stderr)

    sensor_configs = {"width": cam_w, "height": cam_h, "shader_pack": shader_pack}

    try:
        _env = gym.make(
            env_id,
            obs_mode="rgbd",
            control_mode=control_mode,
            robot_uids="fetch",
            render_mode="rgb_array",
            sensor_configs=sensor_configs,
        )
    except FileNotFoundError as exc:
        # Room/scene envs need asset downloads; fall back to PickCube-v1
        print(f"[env-node] WARNING: {exc}", file=sys.stderr)
        print("[env-node] Scene assets missing. Run: ./run.sh setup  (downloads ReplicaCAD)", file=sys.stderr)
        print("[env-node] Falling back to PickCube-v1 (no assets required).", file=sys.stderr)
        env_id = "PickCube-v1"
        _env = gym.make(
            env_id,
            obs_mode="rgbd",
            control_mode=control_mode,
            robot_uids="fetch",
            render_mode="rgb_array",
            sensor_configs=sensor_configs,
        )
    except NotImplementedError as exc:
        print(f"[env-node] WARNING: {env_id} does not support robot_uids=fetch in this task path: {exc}", file=sys.stderr)
        print("[env-node] Falling back to StackCube-v1 for the current Fetch-based demo.", file=sys.stderr)
        env_id = "StackCube-v1"
        _env = gym.make(
            env_id,
            obs_mode="rgbd",
            control_mode=control_mode,
            robot_uids="fetch",
            render_mode="rgb_array",
            sensor_configs=sensor_configs,
        )
    obs, _ = _env.reset()
    _latest_obs = obs
    _latest_done = False
    _latest_reward = 0.0
    print("[env-node] env ready", file=sys.stderr)

    server_addr = os.environ.get("ROBONIX_ATLAS", "localhost:50051")
    channel = grpc.insecure_channel(server_addr)
    stub = pb_grpc.RobonixRuntimeStub(channel)

    node_id = "com.robonix.demo.maniskill"
    stub.RegisterNode(pb.RegisterNodeRequest(
        node_id=node_id,
        namespace="robonix/prm/sim/maniskill",
        kind="primitive",
    ))

    mcp_port = _pick_port()

    # ── One DeclareInterface per contract ──────────────────────────────────────

    # robonix/prm/camera/snapshot — Empty → Image
    stub.DeclareInterface(pb.DeclareInterfaceRequest(
        node_id=node_id,
        name="camera_snapshot",
        supported_transports=["mcp"],
        metadata_json=_single_tool_meta(
            "camera_snapshot",
            "Get current RGB camera image. Returns sensor_msgs/Image (JPEG base64).",
            std_msgs_mcp.Empty.json_schema(),
        ),
        listen_port=mcp_port,
        contract_id="robonix/prm/camera/snapshot",
    ))

    # robonix/prm/robot/state — Empty → RobotState
    stub.DeclareInterface(pb.DeclareInterfaceRequest(
        node_id=node_id,
        name="robot_state",
        supported_transports=["mcp"],
        metadata_json=_single_tool_meta(
            "robot_state",
            "Get robot state (joints, tcp_pose, is_grasped). Returns prm_base/RobotState.",
            std_msgs_mcp.Empty.json_schema(),
        ),
        listen_port=mcp_port,
        contract_id="robonix/prm/robot/state",
    ))

    # robonix/prm/manipulation/exec — String → String
    stub.DeclareInterface(pb.DeclareInterfaceRequest(
        node_id=node_id,
        name="manipulation_exec",
        supported_transports=["mcp"],
        metadata_json=_single_tool_meta(
            "manipulation_exec",
            "Apply manipulation action: std_msgs/String.data is JSON array or {action, hold_steps}. Returns std_msgs/String.",
            std_msgs_mcp.String.json_schema(),
        ),
        listen_port=mcp_port,
        contract_id="robonix/prm/manipulation/exec",
    ))

    grpc_port = _pick_port()
    stub.DeclareInterface(pb.DeclareInterfaceRequest(
        node_id=node_id,
        name="env_data",
        supported_transports=["grpc"],
        metadata_json="{}",
        listen_port=grpc_port,
    ))

    threading.Thread(target=_heartbeat_loop, args=(stub, node_id), daemon=True).start()
    threading.Thread(target=_run_grpc_server, args=(grpc_port,), daemon=True).start()
    threading.Thread(target=_start_mcp_http, args=(mcp_port,), daemon=True).start()

    if _IOX2_TRANSPORT:
        iox2_fps = float(os.environ.get("IOX2_FPS", "30"))
        threading.Thread(
            target=_iox2_publish_loop, args=(iox2_fps,), daemon=True, name="iox2-pub"
        ).start()
        print(f"[env-node] iceoryx2 publisher started at {iox2_fps:.0f} fps", file=sys.stderr)

    print(f"[env-node] MCP :{mcp_port}  gRPC :{grpc_port}", file=sys.stderr)
    print("[env-node] ready", file=sys.stderr)

    try:
        while True:
            time.sleep(1.0)
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main()
