# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import maniskill_env_pb2 as maniskill__env__pb2


class EnvDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetObs = channel.unary_unary(
                '/maniskill.EnvDataService/GetObs',
                request_serializer=maniskill__env__pb2.Empty.SerializeToString,
                response_deserializer=maniskill__env__pb2.Observation.FromString,
                )
        self.Step = channel.unary_unary(
                '/maniskill.EnvDataService/Step',
                request_serializer=maniskill__env__pb2.Action.SerializeToString,
                response_deserializer=maniskill__env__pb2.StepResult.FromString,
                )
        self.Reset = channel.unary_unary(
                '/maniskill.EnvDataService/Reset',
                request_serializer=maniskill__env__pb2.Empty.SerializeToString,
                response_deserializer=maniskill__env__pb2.Observation.FromString,
                )


class EnvDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetObs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnvDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetObs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObs,
                    request_deserializer=maniskill__env__pb2.Empty.FromString,
                    response_serializer=maniskill__env__pb2.Observation.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=maniskill__env__pb2.Action.FromString,
                    response_serializer=maniskill__env__pb2.StepResult.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=maniskill__env__pb2.Empty.FromString,
                    response_serializer=maniskill__env__pb2.Observation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'maniskill.EnvDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EnvDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetObs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/maniskill.EnvDataService/GetObs',
            maniskill__env__pb2.Empty.SerializeToString,
            maniskill__env__pb2.Observation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/maniskill.EnvDataService/Step',
            maniskill__env__pb2.Action.SerializeToString,
            maniskill__env__pb2.StepResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/maniskill.EnvDataService/Reset',
            maniskill__env__pb2.Empty.SerializeToString,
            maniskill__env__pb2.Observation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class SlamDataServiceStub(object):
    """SLAM results served by rtabmap_bridge running in the Docker container.
    viz_node (on the host) polls this to log 3-D cloud + 2-D occupancy to Rerun.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSlamData = channel.unary_unary(
                '/maniskill.SlamDataService/GetSlamData',
                request_serializer=maniskill__env__pb2.Empty.SerializeToString,
                response_deserializer=maniskill__env__pb2.SlamData.FromString,
                )


class SlamDataServiceServicer(object):
    """SLAM results served by rtabmap_bridge running in the Docker container.
    viz_node (on the host) polls this to log 3-D cloud + 2-D occupancy to Rerun.
    """

    def GetSlamData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SlamDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSlamData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSlamData,
                    request_deserializer=maniskill__env__pb2.Empty.FromString,
                    response_serializer=maniskill__env__pb2.SlamData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'maniskill.SlamDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SlamDataService(object):
    """SLAM results served by rtabmap_bridge running in the Docker container.
    viz_node (on the host) polls this to log 3-D cloud + 2-D occupancy to Rerun.
    """

    @staticmethod
    def GetSlamData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/maniskill.SlamDataService/GetSlamData',
            maniskill__env__pb2.Empty.SerializeToString,
            maniskill__env__pb2.SlamData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
