# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import robot_control_pb2 as robot__control__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in robot_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Move = channel.unary_unary(
                '/robotcontrol.RobotControl/Move',
                request_serializer=robot__control__pb2.MoveRequest.SerializeToString,
                response_deserializer=robot__control__pb2.MoveReply.FromString,
                _registered_method=True)
        self.Rotate = channel.unary_unary(
                '/robotcontrol.RobotControl/Rotate',
                request_serializer=robot__control__pb2.RotateRequest.SerializeToString,
                response_deserializer=robot__control__pb2.MoveReply.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/robotcontrol.RobotControl/Stop',
                request_serializer=robot__control__pb2.StopRequest.SerializeToString,
                response_deserializer=robot__control__pb2.MoveReply.FromString,
                _registered_method=True)
        self.GetPose = channel.unary_unary(
                '/robotcontrol.RobotControl/GetPose',
                request_serializer=robot__control__pb2.GetPoseRequest.SerializeToString,
                response_deserializer=robot__control__pb2.PoseReply.FromString,
                _registered_method=True)
        self.MoveTo = channel.unary_unary(
                '/robotcontrol.RobotControl/MoveTo',
                request_serializer=robot__control__pb2.MoveToRequest.SerializeToString,
                response_deserializer=robot__control__pb2.MoveReply.FromString,
                _registered_method=True)
        self.GetRGBImage = channel.unary_unary(
                '/robotcontrol.RobotControl/GetRGBImage',
                request_serializer=robot__control__pb2.GetImageRequest.SerializeToString,
                response_deserializer=robot__control__pb2.RGBImageReply.FromString,
                _registered_method=True)
        self.GetDepthImage = channel.unary_unary(
                '/robotcontrol.RobotControl/GetDepthImage',
                request_serializer=robot__control__pb2.GetImageRequest.SerializeToString,
                response_deserializer=robot__control__pb2.DepthImageReply.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/robotcontrol.RobotControl/Reset',
                request_serializer=robot__control__pb2.ResetRequest.SerializeToString,
                response_deserializer=robot__control__pb2.MoveReply.FromString,
                _registered_method=True)


class RobotControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Move(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rotate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveTo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRGBImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDepthImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Move': grpc.unary_unary_rpc_method_handler(
                    servicer.Move,
                    request_deserializer=robot__control__pb2.MoveRequest.FromString,
                    response_serializer=robot__control__pb2.MoveReply.SerializeToString,
            ),
            'Rotate': grpc.unary_unary_rpc_method_handler(
                    servicer.Rotate,
                    request_deserializer=robot__control__pb2.RotateRequest.FromString,
                    response_serializer=robot__control__pb2.MoveReply.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=robot__control__pb2.StopRequest.FromString,
                    response_serializer=robot__control__pb2.MoveReply.SerializeToString,
            ),
            'GetPose': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPose,
                    request_deserializer=robot__control__pb2.GetPoseRequest.FromString,
                    response_serializer=robot__control__pb2.PoseReply.SerializeToString,
            ),
            'MoveTo': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveTo,
                    request_deserializer=robot__control__pb2.MoveToRequest.FromString,
                    response_serializer=robot__control__pb2.MoveReply.SerializeToString,
            ),
            'GetRGBImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRGBImage,
                    request_deserializer=robot__control__pb2.GetImageRequest.FromString,
                    response_serializer=robot__control__pb2.RGBImageReply.SerializeToString,
            ),
            'GetDepthImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDepthImage,
                    request_deserializer=robot__control__pb2.GetImageRequest.FromString,
                    response_serializer=robot__control__pb2.DepthImageReply.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=robot__control__pb2.ResetRequest.FromString,
                    response_serializer=robot__control__pb2.MoveReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robotcontrol.RobotControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robotcontrol.RobotControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robotcontrol.RobotControl/Move',
            robot__control__pb2.MoveRequest.SerializeToString,
            robot__control__pb2.MoveReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rotate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robotcontrol.RobotControl/Rotate',
            robot__control__pb2.RotateRequest.SerializeToString,
            robot__control__pb2.MoveReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robotcontrol.RobotControl/Stop',
            robot__control__pb2.StopRequest.SerializeToString,
            robot__control__pb2.MoveReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robotcontrol.RobotControl/GetPose',
            robot__control__pb2.GetPoseRequest.SerializeToString,
            robot__control__pb2.PoseReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveTo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robotcontrol.RobotControl/MoveTo',
            robot__control__pb2.MoveToRequest.SerializeToString,
            robot__control__pb2.MoveReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRGBImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robotcontrol.RobotControl/GetRGBImage',
            robot__control__pb2.GetImageRequest.SerializeToString,
            robot__control__pb2.RGBImageReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDepthImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robotcontrol.RobotControl/GetDepthImage',
            robot__control__pb2.GetImageRequest.SerializeToString,
            robot__control__pb2.DepthImageReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robotcontrol.RobotControl/Reset',
            robot__control__pb2.ResetRequest.SerializeToString,
            robot__control__pb2.MoveReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
