// SPDX-License-Identifier: MulanPSL-2.0
// Emit `contract_proto_modules.rs` for Rust crates that `tonic::include_proto!` the whole
// `robonix_contracts.proto` closure. Module order follows proto `import` dependencies (deps first).

use anyhow::{Context, Result};
use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

/// Parse `import "pkg/foo.proto";` lines; skip `google/` well-known types.
fn parse_proto_imports(path: &Path) -> Result<Vec<String>> {
    let text = fs::read_to_string(path).with_context(|| format!("read {}", path.display()))?;
    let mut v = Vec::new();
    for line in text.lines() {
        let line = line.trim();
        let Some(rest) = line.strip_prefix("import ") else {
            continue;
        };
        let rest = rest.trim();
        let Some(rest) = rest.strip_prefix('"') else {
            continue;
        };
        let path_part = rest.split('"').next().unwrap_or("").trim();
        if path_part.starts_with("google/") {
            continue;
        }
        if path_part.ends_with(".proto") {
            v.push(path_part.to_string());
        }
    }
    Ok(v)
}

/// `package robonix.foo;` → `robonix.foo`
fn parse_proto_package(path: &Path) -> Result<Option<String>> {
    let text = fs::read_to_string(path).with_context(|| format!("read {}", path.display()))?;
    for line in text.lines() {
        let line = line.trim();
        if line.starts_with("//") || line.is_empty() {
            continue;
        }
        let Some(rest) = line.strip_prefix("package ") else {
            continue;
        };
        let pkg = rest.trim_end_matches(';').trim();
        if !pkg.is_empty() {
            return Ok(Some(pkg.to_string()));
        }
    }
    Ok(None)
}

/// `robonix.prm_base` → Rust sibling module name `prm_base` (last segment).
fn package_to_rust_module(dot_pkg: &str) -> String {
    dot_pkg
        .rsplit_once('.')
        .map(|(_, last)| last.to_string())
        .unwrap_or_else(|| dot_pkg.to_string())
}

fn dfs_postorder(
    out_dir: &Path,
    file: &str,
    visiting: &mut BTreeSet<String>,
    visited: &mut BTreeSet<String>,
    order: &mut Vec<String>,
) -> Result<()> {
    if visited.contains(file) {
        return Ok(());
    }
    if visiting.contains(file) {
        return Ok(()); // import cycle — skip re-entry
    }
    let path = out_dir.join(file);
    if !path.is_file() {
        return Ok(());
    }

    visiting.insert(file.to_string());
    for imp in parse_proto_imports(&path)? {
        dfs_postorder(out_dir, &imp, visiting, visited, order)?;
    }
    visiting.remove(file);
    visited.insert(file.to_string());
    order.push(file.to_string());
    Ok(())
}

/// After `robonix_contracts.proto` is written, emit sibling `contract_proto_modules.rs`.
pub fn write(out_dir: &Path) -> Result<()> {
    let root = "robonix_contracts.proto";
    let contracts_path = out_dir.join(root);
    if !contracts_path.is_file() {
        return Ok(());
    }

    let mut visiting = BTreeSet::new();
    let mut visited = BTreeSet::new();
    let mut order = Vec::new();
    dfs_postorder(out_dir, root, &mut visiting, &mut visited, &mut order)?;

    let mut out = String::new();
    writeln!(
        &mut out,
        "// @generated by robonix-codegen (--contracts). Source: proto import closure for `{}`.",
        root
    )?;
    writeln!(&mut out, "// Do not edit by hand.")?;
    writeln!(
        &mut out,
        "// `tonic::include_proto!` order matches prost `super::` sibling resolution."
    )?;
    writeln!(
        &mut out,
        "// Most generated types are unused in any single binary."
    )?;
    writeln!(
        &mut out,
        "// (Suppress dead_code on the `robonix-interfaces` crate — not `#![allow]` here: included via `include!`.)"
    )?;
    writeln!(&mut out)?;

    for proto_file in &order {
        let path = out_dir.join(proto_file);
        let Some(dot_pkg) = parse_proto_package(&path)? else {
            continue;
        };
        let rust_mod = package_to_rust_module(&dot_pkg);
        writeln!(&mut out, "pub mod {rust_mod} {{")?;
        writeln!(&mut out, "    tonic::include_proto!(\"{dot_pkg}\");")?;
        writeln!(&mut out, "}}")?;
        writeln!(&mut out)?;
    }

    let outfile = out_dir.join("contract_proto_modules.rs");
    fs::write(&outfile, &out).with_context(|| format!("write {}", outfile.display()))?;
    eprintln!(
        "[robonix-codegen] contracts: wrote {} ({} include_proto modules)",
        outfile.display(),
        order.len()
    );
    Ok(())
}
