// SPDX-License-Identifier: MulanPSL-2.0
// Generate `robonix_contracts.proto` from `rust/contracts/**/*.toml`.
//
// `[mode].type` → `robonix_contracts.proto` (see `rust/contracts/README.md`).
// Streaming: `rpc_server_stream` uses the .srv response (exactly one field) as stream element; `rpc_client_stream` uses the request (exactly one field).

use anyhow::{bail, Context, Result};
use serde::Deserialize;
use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use super::msg_parser::{MsgField, MsgResolver, MsgTypeRef, SrvSpec};
use super::proto_gen::proto_package_name;

#[derive(Debug, Deserialize)]
struct ContractToml {
    contract: ContractMeta,
    io: IoSpec,
    mode: ModeSpec,
}

#[derive(Debug, Deserialize)]
struct ContractMeta {
    id: String,
    #[allow(dead_code)]
    version: String,
    #[allow(dead_code)]
    kind: String,
}

/// Exactly **one** of `[io.msg]` (`msg = …`) or `[io.srv]` (`srv = …`).
#[derive(Debug, Deserialize, Default)]
struct IoSpec {
    #[serde(default)]
    msg: Option<IoMsgIo>,
    #[serde(default)]
    srv: Option<IoSrvIo>,
}

#[derive(Debug, Deserialize)]
struct IoMsgIo {
    msg: String,
}

#[derive(Debug, Deserialize)]
struct IoSrvIo {
    srv: String,
}

#[derive(Debug, Deserialize)]
struct ModeSpec {
    #[serde(rename = "type")]
    mode_type: String,
}

/// `(ROS package, srv interface name)` pairs from every contract `[io.srv].srv` path.
/// Used by proto generation: only these `.srv` files get `*_Request` / `*_Response` messages; per-package `service` RPCs are not emitted.
pub fn collect_referenced_srvs(contracts_dir: &Path) -> Result<BTreeSet<(String, String)>> {
    let paths = collect_tomls(contracts_dir)?;
    let mut set = BTreeSet::new();
    for p in paths {
        let raw =
            fs::read_to_string(&p).with_context(|| format!("read contract {}", p.display()))?;
        let c: ContractToml =
            toml::from_str(&raw).with_context(|| format!("parse TOML {}", p.display()))?;
        if let Some(ref io_srv) = c.io.srv {
            let path = io_srv.srv.trim();
            if let Some((pkg, "srv", name)) = parse_ros_path(path) {
                set.insert((pkg.to_string(), name.to_string()));
            } else {
                bail!(
                    "contract {}: [io.srv].srv must be pkg/srv/Name, got {path:?}",
                    c.contract.id
                );
            }
        }
    }
    Ok(set)
}

pub fn generate(
    resolver: &mut MsgResolver,
    contracts_dir: &Path,
    out_dir: &Path,
    verbose: bool,
) -> Result<()> {
    let paths = collect_tomls(contracts_dir)?;
    if paths.is_empty() {
        if verbose {
            eprintln!(
                "[robonix-codegen] contracts: no .toml under {}",
                contracts_dir.display()
            );
        }
        return Ok(());
    }

    let mut contracts: Vec<(PathBuf, ContractToml)> = Vec::new();
    for p in paths {
        let raw =
            fs::read_to_string(&p).with_context(|| format!("read contract {}", p.display()))?;
        let c: ContractToml =
            toml::from_str(&raw).with_context(|| format!("parse TOML {}", p.display()))?;
        contracts.push((p, c));
    }
    contracts.sort_by(|a, b| a.1.contract.id.cmp(&b.1.contract.id));

    let mut out = String::new();
    writeln!(&mut out, "// @generated by robonix-codegen (--contracts).")?;
    writeln!(&mut out, "// Do not edit by hand.")?;
    writeln!(&mut out, "syntax = \"proto3\";")?;
    writeln!(&mut out)?;
    writeln!(&mut out, "package robonix.contracts;")?;
    writeln!(&mut out)?;
    writeln!(&mut out, "import \"google/protobuf/empty.proto\";")?;
    writeln!(&mut out)?;

    let mut imports: BTreeSet<String> = BTreeSet::new();
    let mut needs_string_wire = false;

    let mut proto_types: Vec<(String, ResolvedType, ResolvedType)> = Vec::new();
    for (_, c) in &contracts {
        let (in_t, out_t) = resolve_contract_io(c, resolver, &mut imports, &mut needs_string_wire)?;
        proto_types.push((c.contract.id.clone(), in_t, out_t));
    }

    for imp in &imports {
        writeln!(&mut out, "import \"{imp}\";",)?;
    }
    if !imports.is_empty() {
        writeln!(&mut out)?;
    }

    if needs_string_wire {
        writeln!(
            &mut out,
            "// Wrapper for contracts that use primitive/string until shared IDL exists."
        )?;
        writeln!(&mut out, "message StringWire {{")?;
        writeln!(&mut out, "  string value = 1;")?;
        writeln!(&mut out, "}}")?;
        writeln!(&mut out)?;
    }

    for ((_, c), (_, in_t, out_t)) in contracts.iter().zip(proto_types.iter()) {
        let mode = c.mode.mode_type.trim();
        let svc = contract_id_to_service_name(&c.contract.id);
        writeln!(
            &mut out,
            "// contract: {} (v{})",
            c.contract.id, c.contract.version
        )?;
        writeln!(&mut out, "service {svc} {{")?;

        let rpc = match mode {
            "rpc" => format_unary(in_t, out_t),
            "rpc_server_stream" | "topic_out" => format_stream_out(in_t, out_t),
            "rpc_client_stream" | "topic_in" => format_stream_in(in_t, out_t),
            other => bail!(
                "unknown [mode].type '{other}' in contract {} (expected rpc | rpc_server_stream | rpc_client_stream | topic_out | topic_in)",
                c.contract.id
            ),
        };
        writeln!(&mut out, "  {rpc}")?;
        writeln!(&mut out, "}}")?;
        writeln!(&mut out)?;
    }

    let outfile = out_dir.join("robonix_contracts.proto");
    fs::write(&outfile, &out).with_context(|| format!("write {}", outfile.display()))?;
    if verbose {
        eprintln!(
            "[robonix-codegen] contracts: wrote {} ({} services)",
            outfile.display(),
            contracts.len()
        );
    }

    super::contract_proto_modules_gen::write(out_dir, verbose)?;
    Ok(())
}

#[derive(Clone)]
enum ResolvedType {
    ProtoFqn(String),
    GoogleEmpty,
    StringWire,
}

fn format_stream_out(input: &ResolvedType, output: &ResolvedType) -> String {
    format!(
        "rpc Stream({}) returns (stream {});",
        empty_or_type(input),
        stream_element(output)
    )
}

fn format_stream_in(input: &ResolvedType, output: &ResolvedType) -> String {
    format!(
        "rpc Stream(stream {}) returns ({});",
        stream_element(input),
        unary_return(output)
    )
}

fn format_unary(input: &ResolvedType, output: &ResolvedType) -> String {
    format!(
        "rpc Call({}) returns ({});",
        unary_arg(input),
        unary_return(output)
    )
}

fn empty_or_type(t: &ResolvedType) -> String {
    match t {
        ResolvedType::GoogleEmpty => "google.protobuf.Empty".to_string(),
        ResolvedType::ProtoFqn(s) => s.clone(),
        ResolvedType::StringWire => "robonix.contracts.StringWire".to_string(),
    }
}

fn unary_arg(t: &ResolvedType) -> String {
    empty_or_type(t)
}

fn unary_return(t: &ResolvedType) -> String {
    match t {
        ResolvedType::GoogleEmpty => "google.protobuf.Empty".to_string(),
        ResolvedType::ProtoFqn(s) => s.clone(),
        ResolvedType::StringWire => "robonix.contracts.StringWire".to_string(),
    }
}

fn stream_element(t: &ResolvedType) -> String {
    unary_arg(t)
}

fn srv_stream_field_to_resolved(
    contract_id: &str,
    srv_path: &str,
    section: &str,
    field: &MsgField,
    resolver: &mut MsgResolver,
    imports: &mut BTreeSet<String>,
    needs_string_wire: &mut bool,
) -> Result<ResolvedType> {
    if field.is_array {
        bail!(
            "contract {contract_id}: [{section}] stream element must be a single message, not an array (in {srv_path})"
        );
    }
    field_to_resolved_type(field, resolver, imports, needs_string_wire)
}

fn resolve_contract_io(
    c: &ContractToml,
    resolver: &mut MsgResolver,
    imports: &mut BTreeSet<String>,
    needs_string_wire: &mut bool,
) -> Result<(ResolvedType, ResolvedType)> {
    let n_msg = c.io.msg.is_some() as u8;
    let n_srv = c.io.srv.is_some() as u8;
    if n_msg + n_srv != 1 {
        bail!(
            "contract {}: set exactly one of [io.msg] or [io.srv]",
            c.contract.id
        );
    }

    let mode = c.mode.mode_type.trim();
    let s = c.io.srv.as_ref();
    let m = c.io.msg.as_ref();

    match mode {
        "rpc" => {
            let s = s.ok_or_else(|| {
                anyhow::anyhow!(
                    "contract {}: [mode].type = \"rpc\" requires [io.srv]",
                    c.contract.id
                )
            })?;
            resolve_srv_contract_pair(&s.srv, resolver, imports, needs_string_wire)
        }
        "rpc_server_stream" => {
            let s = s.ok_or_else(|| {
                anyhow::anyhow!(
                    "contract {}: [mode].type = \"rpc_server_stream\" requires [io.srv]",
                    c.contract.id
                )
            })?;
            resolve_srv_server_stream(s, &c.contract.id, resolver, imports, needs_string_wire)
        }
        "rpc_client_stream" => {
            let s = s.ok_or_else(|| {
                anyhow::anyhow!(
                    "contract {}: [mode].type = \"rpc_client_stream\" requires [io.srv]",
                    c.contract.id
                )
            })?;
            resolve_srv_client_stream(s, &c.contract.id, resolver, imports, needs_string_wire)
        }
        "topic_out" => {
            let m = m.ok_or_else(|| {
                anyhow::anyhow!(
                    "contract {}: [mode].type = \"topic_out\" requires [io.msg] with `msg`",
                    c.contract.id
                )
            })?;
            let elem = resolve_io(&m.msg, resolver, imports, needs_string_wire)?;
            Ok((ResolvedType::GoogleEmpty, elem))
        }
        "topic_in" => {
            let m = m.ok_or_else(|| {
                anyhow::anyhow!(
                    "contract {}: [mode].type = \"topic_in\" requires [io.msg] with `msg`",
                    c.contract.id
                )
            })?;
            let elem = resolve_io(&m.msg, resolver, imports, needs_string_wire)?;
            Ok((elem, ResolvedType::GoogleEmpty))
        }
        other => bail!(
            "unknown [mode].type '{}' in contract {}",
            other,
            c.contract.id
        ),
    }
}

fn resolve_srv_server_stream(
    io: &IoSrvIo,
    contract_id: &str,
    resolver: &mut MsgResolver,
    imports: &mut BTreeSet<String>,
    needs_string_wire: &mut bool,
) -> Result<(ResolvedType, ResolvedType)> {
    let p = io.srv.trim();
    let Some((pkg, "srv", name)) = parse_ros_path(p) else {
        bail!("[io.srv].srv must be pkg/srv/Name, got {p:?}");
    };
    resolver
        .resolve_srv(pkg, name)
        .with_context(|| format!("resolve srv {p}"))?;
    let spec = resolver
        .srv_spec(pkg, name)
        .ok_or_else(|| anyhow::anyhow!("internal: srv {p} not cached"))?
        .clone();

    let res = &spec.response;
    if res.fields.len() != 1 {
        bail!(
            "contract {contract_id}: [mode] rpc_server_stream requires the .srv response section to have exactly one field (stream element type), got {} in {p}",
            res.fields.len()
        );
    }
    let in_t = srv_request_to_contract_input(&spec, resolver, imports, needs_string_wire)?;
    let out_t = srv_stream_field_to_resolved(
        contract_id,
        p,
        "response",
        &res.fields[0],
        resolver,
        imports,
        needs_string_wire,
    )?;
    Ok((in_t, out_t))
}

fn resolve_srv_client_stream(
    io: &IoSrvIo,
    contract_id: &str,
    resolver: &mut MsgResolver,
    imports: &mut BTreeSet<String>,
    needs_string_wire: &mut bool,
) -> Result<(ResolvedType, ResolvedType)> {
    let p = io.srv.trim();
    let Some((pkg, "srv", name)) = parse_ros_path(p) else {
        bail!("[io.srv].srv must be pkg/srv/Name, got {p:?}");
    };
    resolver
        .resolve_srv(pkg, name)
        .with_context(|| format!("resolve srv {p}"))?;
    let spec = resolver
        .srv_spec(pkg, name)
        .ok_or_else(|| anyhow::anyhow!("internal: srv {p} not cached"))?
        .clone();

    let req = &spec.request;
    if req.fields.len() != 1 {
        bail!(
            "contract {contract_id}: [mode] rpc_client_stream requires the .srv request section to have exactly one field (stream element type), got {} in {p}",
            req.fields.len()
        );
    }
    let in_t = srv_stream_field_to_resolved(
        contract_id,
        p,
        "request",
        &req.fields[0],
        resolver,
        imports,
        needs_string_wire,
    )?;
    let out_t = srv_response_to_contract_output(&spec, resolver, imports, needs_string_wire)?;
    Ok((in_t, out_t))
}

fn srv_request_to_contract_input(
    srv: &SrvSpec,
    resolver: &mut MsgResolver,
    imports: &mut BTreeSet<String>,
    needs_string_wire: &mut bool,
) -> Result<ResolvedType> {
    let req = &srv.request;
    if req.fields.len() == 1 {
        return field_to_resolved_type(&req.fields[0], resolver, imports, needs_string_wire);
    }
    imports.insert(format!("{}.proto", srv.package));
    Ok(ResolvedType::ProtoFqn(format!(
        "{}.{}",
        proto_package_name(&srv.package),
        req.name
    )))
}

/// Empty `.srv` response section → `google.protobuf.Empty`; else the generated `*_Response` message.
fn srv_response_to_contract_output(
    srv: &SrvSpec,
    resolver: &mut MsgResolver,
    imports: &mut BTreeSet<String>,
    _needs_string_wire: &mut bool,
) -> Result<ResolvedType> {
    let res = &srv.response;
    if res.fields.is_empty() {
        return Ok(ResolvedType::GoogleEmpty);
    }
    for f in &res.fields {
        if let MsgTypeRef::Named { package, name } = &f.type_ref {
            resolver.resolve_named_type(package, name, None)?;
        }
    }
    imports.insert(format!("{}.proto", srv.package));
    Ok(ResolvedType::ProtoFqn(format!(
        "{}.{}",
        proto_package_name(&srv.package),
        res.name
    )))
}

fn resolve_srv_contract_pair(
    path: &str,
    resolver: &mut MsgResolver,
    imports: &mut BTreeSet<String>,
    _needs_string_wire: &mut bool,
) -> Result<(ResolvedType, ResolvedType)> {
    let p = path.trim();
    if let Some((pkg, "srv", name)) = parse_ros_path(p) {
        resolver
            .resolve_srv(pkg, name)
            .with_context(|| format!("resolve srv {p}"))?;
        imports.insert(format!("{pkg}.proto"));
        let req = format!("{name}_Request");
        let res = format!("{name}_Response");
        return Ok((
            ResolvedType::ProtoFqn(format!("{}.{}", proto_package_name(pkg), req)),
            ResolvedType::ProtoFqn(format!("{}.{}", proto_package_name(pkg), res)),
        ));
    }
    bail!("[io.srv].srv must be pkg/srv/Name, got {p:?}");
}

fn field_to_resolved_type(
    field: &MsgField,
    resolver: &mut MsgResolver,
    imports: &mut BTreeSet<String>,
    needs_string_wire: &mut bool,
) -> Result<ResolvedType> {
    match &field.type_ref {
        MsgTypeRef::Primitive(_) => bail!(
            "contract I/O field `{}` must use a named ROS message type, not a primitive",
            field.name
        ),
        MsgTypeRef::Named { package, name } => resolve_io(
            &format!("{package}/msg/{name}"),
            resolver,
            imports,
            needs_string_wire,
        ),
    }
}

fn resolve_io(
    spec: &str,
    resolver: &mut MsgResolver,
    imports: &mut BTreeSet<String>,
    needs_string_wire: &mut bool,
) -> Result<ResolvedType> {
    let s = spec.trim();
    if s == "primitive/string" {
        *needs_string_wire = true;
        return Ok(ResolvedType::StringWire);
    }
    if let Some(rest) = s.strip_prefix("protobuf://") {
        let (pkg, typ) = split_proto_fqn(rest)?;
        imports.insert(proto_file_for_dot_package(pkg));
        return Ok(ResolvedType::ProtoFqn(format!("{}.{}", pkg, typ)));
    }
    if s == "std_msgs/msg/Empty" {
        return Ok(ResolvedType::GoogleEmpty);
    }
    if let Some((pkg, "msg", name)) = parse_ros_path(s) {
        resolver
            .resolve_named_type(pkg, name, None)
            .with_context(|| format!("resolve msg {pkg}/{name} referenced from contract"))?;
        imports.insert(format!("{pkg}.proto"));
        return Ok(ResolvedType::ProtoFqn(format!(
            "{}.{}",
            proto_package_name(pkg),
            name
        )));
    }
    if let Some((pkg, "srv", name)) = parse_ros_path(s) {
        resolver
            .resolve_srv(pkg, name)
            .with_context(|| format!("resolve srv {pkg}/{name} referenced from contract"))?;
        imports.insert(format!("{pkg}.proto"));
        let req = format!("{}_Request", name);
        return Ok(ResolvedType::ProtoFqn(format!(
            "{}.{}",
            proto_package_name(pkg),
            req
        )));
    }
    bail!(
        "unsupported [io] reference '{s}' (expected pkg/msg/Name, pkg/srv/Name, protobuf://..., or primitive/string)"
    )
}

fn parse_ros_path(s: &str) -> Option<(&str, &str, &str)> {
    let parts: Vec<&str> = s.split('/').collect();
    if parts.len() != 3 {
        return None;
    }
    Some((parts[0], parts[1], parts[2]))
}

fn split_proto_fqn(s: &str) -> Result<(&str, &str)> {
    let s = s.trim();
    let (pkg, typ) = s
        .rsplit_once('/')
        .ok_or_else(|| anyhow::anyhow!("protobuf:// expects Package/Type, got {s}"))?;
    if pkg.is_empty() || typ.is_empty() {
        bail!("invalid protobuf ref {s}");
    }
    Ok((pkg, typ))
}

fn proto_file_for_dot_package(pkg: &str) -> String {
    let segs: Vec<&str> = pkg.split('.').collect();
    if segs.len() >= 2 {
        return format!("{}_{}.proto", segs[0], segs[1]);
    }
    format!("{}.proto", pkg.replace('.', "_"))
}

fn contract_id_to_service_name(id: &str) -> String {
    let body = id.strip_prefix("robonix/").unwrap_or(id);
    body.split('/')
        .filter(|x| !x.is_empty())
        .map(|seg| {
            seg.split('_')
                .filter(|p| !p.is_empty())
                .map(|p| {
                    let mut c = p.chars();
                    match c.next() {
                        None => String::new(),
                        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                    }
                })
                .collect::<String>()
        })
        .collect::<String>()
}

fn collect_tomls(dir: &Path) -> Result<Vec<PathBuf>> {
    let mut v = Vec::new();
    collect_tomls_inner(dir, &mut v)?;
    v.sort();
    Ok(v)
}

fn collect_tomls_inner(dir: &Path, out: &mut Vec<PathBuf>) -> Result<()> {
    if !dir.is_dir() {
        bail!("contracts directory does not exist: {}", dir.display());
    }
    for entry in fs::read_dir(dir).with_context(|| format!("read_dir {}", dir.display()))? {
        let entry = entry?;
        let p = entry.path();
        if p.is_dir() {
            collect_tomls_inner(&p, out)?;
        } else if p.extension().and_then(|x| x.to_str()) == Some("toml") {
            out.push(p);
        }
    }
    Ok(())
}
