// @generated by robonix-codegen (--contracts). Source: proto import closure for `robonix_contracts.proto`.
// Do not edit by hand.
// `tonic::include_proto!` order matches prost `super::` sibling resolution.
// Most generated types are unused in any single binary.
// (Suppress dead_code on the `robonix-interfaces` crate — not `#![allow]` here: included via `include!`.)

pub mod pilot {
    tonic::include_proto!("robonix.pilot");
}

pub mod executor {
    tonic::include_proto!("robonix.executor");
}

pub mod builtin_interfaces {
    tonic::include_proto!("robonix.builtin_interfaces");
}

pub mod std_msgs {
    tonic::include_proto!("robonix.std_msgs");
}

pub mod geometry_msgs {
    tonic::include_proto!("robonix.geometry_msgs");
}

pub mod memory {
    tonic::include_proto!("robonix.memory");
}

pub mod nav_msgs {
    tonic::include_proto!("robonix.nav_msgs");
}

pub mod sensor_msgs {
    tonic::include_proto!("robonix.sensor_msgs");
}

pub mod prm_base {
    tonic::include_proto!("robonix.prm_base");
}

pub mod slam {
    tonic::include_proto!("robonix.slam");
}

pub mod robonix_msg {
    tonic::include_proto!("robonix.robonix_msg");
}

pub mod vlm {
    tonic::include_proto!("robonix.vlm");
}

pub mod contracts {
    tonic::include_proto!("robonix.contracts");
}

