# @generated by ridlc --lang python — DO NOT EDIT
# source: ROS IDL package 'actionlib_msgs'
# Payload types for the iceoryx2 Python API (ctypes.Structure + type_name())
# Re-generate: cargo run -p ridlc -- --lang python -I <lib> -o <out>

import ctypes

# Max element counts for unbounded (variable-length) array fields.
# iceoryx2 requires fixed-size payloads; these caps are the upper bound.
# Override the constant in your code before importing these types if needed.
_MAX_IMAGE_BYTES = 8294400  # 1080p RGBA upper bound
_MAX_ARRAY_ELEMS = 256  # generic upper bound for non-byte arrays


class GoalID(ctypes.Structure):
    _fields_ = [
        ("stamp_sec", ctypes.c_int32),
        ("stamp_nanosec", ctypes.c_uint32),
        ("id", ctypes.c_char * 256),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.actionlib_msgs.GoalID"


class GoalStatus(ctypes.Structure):
    PENDING = 0
    ACTIVE = 1
    PREEMPTED = 2
    SUCCEEDED = 3
    ABORTED = 4
    REJECTED = 5
    PREEMPTING = 6
    RECALLING = 7
    RECALLED = 8
    LOST = 9

    _fields_ = [
        ("goal_id_stamp_sec", ctypes.c_int32),
        ("goal_id_stamp_nanosec", ctypes.c_uint32),
        ("goal_id_id", ctypes.c_char * 256),
        ("status", ctypes.c_uint8),
        ("text", ctypes.c_char * 256),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.actionlib_msgs.GoalStatus"


class GoalStatusArray(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        # opaque blob: actionlib_msgs/GoalStatus[] not flattenable
        ("status_list", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.actionlib_msgs.GoalStatusArray"


