# @generated by ridlc --lang python — DO NOT EDIT
# source: ROS IDL package 'builtin_interfaces'
# Payload types for the iceoryx2 Python API (ctypes.Structure + type_name())
# Re-generate: cargo run -p ridlc -- --lang python -I <lib> -o <out>

import ctypes

# Max element counts for unbounded (variable-length) array fields.
# iceoryx2 requires fixed-size payloads; these caps are the upper bound.
# Override the constant in your code before importing these types if needed.
_MAX_IMAGE_BYTES = 8294400  # 1080p RGBA upper bound
_MAX_ARRAY_ELEMS = 256  # generic upper bound for non-byte arrays


class Duration(ctypes.Structure):
    _fields_ = [
        ("sec", ctypes.c_int32),
        ("nanosec", ctypes.c_uint32),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.builtin_interfaces.Duration"


class Time(ctypes.Structure):
    _fields_ = [
        ("sec", ctypes.c_int32),
        ("nanosec", ctypes.c_uint32),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.builtin_interfaces.Time"


