# @generated by ridlc --lang python — DO NOT EDIT
# source: ROS IDL package 'diagnostic_msgs'
# Payload types for the iceoryx2 Python API (ctypes.Structure + type_name())
# Re-generate: cargo run -p ridlc -- --lang python -I <lib> -o <out>

import ctypes

# Max element counts for unbounded (variable-length) array fields.
# iceoryx2 requires fixed-size payloads; these caps are the upper bound.
# Override the constant in your code before importing these types if needed.
_MAX_IMAGE_BYTES = 8294400  # 1080p RGBA upper bound
_MAX_ARRAY_ELEMS = 256  # generic upper bound for non-byte arrays


class DiagnosticArray(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        # opaque blob: diagnostic_msgs/DiagnosticStatus[] not flattenable
        ("status", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.diagnostic_msgs.DiagnosticArray"


class DiagnosticStatus(ctypes.Structure):
    OK = 0
    WARN = 1
    ERROR = 2
    STALE = 3

    _fields_ = [
        ("level", ctypes.c_uint8),
        ("name", ctypes.c_char * 256),
        ("message", ctypes.c_char * 256),
        ("hardware_id", ctypes.c_char * 256),
        # opaque blob: diagnostic_msgs/KeyValue[] not flattenable
        ("values", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.diagnostic_msgs.DiagnosticStatus"


class KeyValue(ctypes.Structure):
    _fields_ = [
        ("key", ctypes.c_char * 256),
        ("value", ctypes.c_char * 256),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.diagnostic_msgs.KeyValue"


