# @generated by ridlc --lang python — DO NOT EDIT
# source: ROS IDL package 'geometry_msgs'
# Payload types for the iceoryx2 Python API (ctypes.Structure + type_name())
# Re-generate: cargo run -p ridlc -- --lang python -I <lib> -o <out>

import ctypes

# Max element counts for unbounded (variable-length) array fields.
# iceoryx2 requires fixed-size payloads; these caps are the upper bound.
# Override the constant in your code before importing these types if needed.
_MAX_IMAGE_BYTES = 8294400  # 1080p RGBA upper bound
_MAX_ARRAY_ELEMS = 256  # generic upper bound for non-byte arrays


class Accel(ctypes.Structure):
    _fields_ = [
        ("linear_x", ctypes.c_double),
        ("linear_y", ctypes.c_double),
        ("linear_z", ctypes.c_double),
        ("angular_x", ctypes.c_double),
        ("angular_y", ctypes.c_double),
        ("angular_z", ctypes.c_double),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.Accel"


class AccelStamped(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("accel_linear_x", ctypes.c_double),
        ("accel_linear_y", ctypes.c_double),
        ("accel_linear_z", ctypes.c_double),
        ("accel_angular_x", ctypes.c_double),
        ("accel_angular_y", ctypes.c_double),
        ("accel_angular_z", ctypes.c_double),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.AccelStamped"


class AccelWithCovariance(ctypes.Structure):
    _fields_ = [
        ("accel_linear_x", ctypes.c_double),
        ("accel_linear_y", ctypes.c_double),
        ("accel_linear_z", ctypes.c_double),
        ("accel_angular_x", ctypes.c_double),
        ("accel_angular_y", ctypes.c_double),
        ("accel_angular_z", ctypes.c_double),
        ("covariance", ctypes.c_double * 36),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.AccelWithCovariance"


class AccelWithCovarianceStamped(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("accel_accel_linear_x", ctypes.c_double),
        ("accel_accel_linear_y", ctypes.c_double),
        ("accel_accel_linear_z", ctypes.c_double),
        ("accel_accel_angular_x", ctypes.c_double),
        ("accel_accel_angular_y", ctypes.c_double),
        ("accel_accel_angular_z", ctypes.c_double),
        ("accel_covariance", ctypes.c_double * 36),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.AccelWithCovarianceStamped"


class Inertia(ctypes.Structure):
    _fields_ = [
        ("m", ctypes.c_double),
        ("com_x", ctypes.c_double),
        ("com_y", ctypes.c_double),
        ("com_z", ctypes.c_double),
        ("ixx", ctypes.c_double),
        ("ixy", ctypes.c_double),
        ("ixz", ctypes.c_double),
        ("iyy", ctypes.c_double),
        ("iyz", ctypes.c_double),
        ("izz", ctypes.c_double),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.Inertia"


class InertiaStamped(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("inertia_m", ctypes.c_double),
        ("inertia_com_x", ctypes.c_double),
        ("inertia_com_y", ctypes.c_double),
        ("inertia_com_z", ctypes.c_double),
        ("inertia_ixx", ctypes.c_double),
        ("inertia_ixy", ctypes.c_double),
        ("inertia_ixz", ctypes.c_double),
        ("inertia_iyy", ctypes.c_double),
        ("inertia_iyz", ctypes.c_double),
        ("inertia_izz", ctypes.c_double),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.InertiaStamped"


class Point(ctypes.Structure):
    _fields_ = [
        ("x", ctypes.c_double),
        ("y", ctypes.c_double),
        ("z", ctypes.c_double),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.Point"


class Point32(ctypes.Structure):
    _fields_ = [
        ("x", ctypes.c_float),
        ("y", ctypes.c_float),
        ("z", ctypes.c_float),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.Point32"


class PointStamped(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("point_x", ctypes.c_double),
        ("point_y", ctypes.c_double),
        ("point_z", ctypes.c_double),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.PointStamped"


class Polygon(ctypes.Structure):
    _fields_ = [
        # opaque blob: geometry_msgs/Point32[] not flattenable
        ("points", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.Polygon"


class PolygonInstance(ctypes.Structure):
    _fields_ = [
        # opaque blob: geometry_msgs/Point32[] not flattenable
        ("polygon_points", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
        ("id", ctypes.c_int64),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.PolygonInstance"


class PolygonInstanceStamped(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        # opaque blob: geometry_msgs/Point32[] not flattenable
        ("polygon_polygon_points", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
        ("polygon_id", ctypes.c_int64),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.PolygonInstanceStamped"


class PolygonStamped(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        # opaque blob: geometry_msgs/Point32[] not flattenable
        ("polygon_points", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.PolygonStamped"


class Pose(ctypes.Structure):
    _fields_ = [
        ("position_x", ctypes.c_double),
        ("position_y", ctypes.c_double),
        ("position_z", ctypes.c_double),
        ("orientation_x", ctypes.c_double),
        ("orientation_y", ctypes.c_double),
        ("orientation_z", ctypes.c_double),
        ("orientation_w", ctypes.c_double),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.Pose"


class Pose2D(ctypes.Structure):
    _fields_ = [
        ("x", ctypes.c_double),
        ("y", ctypes.c_double),
        ("theta", ctypes.c_double),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.Pose2D"


class PoseArray(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        # opaque blob: geometry_msgs/Pose[] not flattenable
        ("poses", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.PoseArray"


class PoseStamped(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("pose_position_x", ctypes.c_double),
        ("pose_position_y", ctypes.c_double),
        ("pose_position_z", ctypes.c_double),
        ("pose_orientation_x", ctypes.c_double),
        ("pose_orientation_y", ctypes.c_double),
        ("pose_orientation_z", ctypes.c_double),
        ("pose_orientation_w", ctypes.c_double),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.PoseStamped"


class PoseWithCovariance(ctypes.Structure):
    _fields_ = [
        ("pose_position_x", ctypes.c_double),
        ("pose_position_y", ctypes.c_double),
        ("pose_position_z", ctypes.c_double),
        ("pose_orientation_x", ctypes.c_double),
        ("pose_orientation_y", ctypes.c_double),
        ("pose_orientation_z", ctypes.c_double),
        ("pose_orientation_w", ctypes.c_double),
        ("covariance", ctypes.c_double * 36),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.PoseWithCovariance"


class PoseWithCovarianceStamped(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("pose_pose_position_x", ctypes.c_double),
        ("pose_pose_position_y", ctypes.c_double),
        ("pose_pose_position_z", ctypes.c_double),
        ("pose_pose_orientation_x", ctypes.c_double),
        ("pose_pose_orientation_y", ctypes.c_double),
        ("pose_pose_orientation_z", ctypes.c_double),
        ("pose_pose_orientation_w", ctypes.c_double),
        ("pose_covariance", ctypes.c_double * 36),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.PoseWithCovarianceStamped"


class Quaternion(ctypes.Structure):
    _fields_ = [
        ("x", ctypes.c_double),
        ("y", ctypes.c_double),
        ("z", ctypes.c_double),
        ("w", ctypes.c_double),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.Quaternion"


class QuaternionStamped(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("quaternion_x", ctypes.c_double),
        ("quaternion_y", ctypes.c_double),
        ("quaternion_z", ctypes.c_double),
        ("quaternion_w", ctypes.c_double),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.QuaternionStamped"


class Transform(ctypes.Structure):
    _fields_ = [
        ("translation_x", ctypes.c_double),
        ("translation_y", ctypes.c_double),
        ("translation_z", ctypes.c_double),
        ("rotation_x", ctypes.c_double),
        ("rotation_y", ctypes.c_double),
        ("rotation_z", ctypes.c_double),
        ("rotation_w", ctypes.c_double),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.Transform"


class TransformStamped(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("child_frame_id", ctypes.c_char * 256),
        ("transform_translation_x", ctypes.c_double),
        ("transform_translation_y", ctypes.c_double),
        ("transform_translation_z", ctypes.c_double),
        ("transform_rotation_x", ctypes.c_double),
        ("transform_rotation_y", ctypes.c_double),
        ("transform_rotation_z", ctypes.c_double),
        ("transform_rotation_w", ctypes.c_double),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.TransformStamped"


class Twist(ctypes.Structure):
    _fields_ = [
        ("linear_x", ctypes.c_double),
        ("linear_y", ctypes.c_double),
        ("linear_z", ctypes.c_double),
        ("angular_x", ctypes.c_double),
        ("angular_y", ctypes.c_double),
        ("angular_z", ctypes.c_double),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.Twist"


class TwistStamped(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("twist_linear_x", ctypes.c_double),
        ("twist_linear_y", ctypes.c_double),
        ("twist_linear_z", ctypes.c_double),
        ("twist_angular_x", ctypes.c_double),
        ("twist_angular_y", ctypes.c_double),
        ("twist_angular_z", ctypes.c_double),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.TwistStamped"


class TwistWithCovariance(ctypes.Structure):
    _fields_ = [
        ("twist_linear_x", ctypes.c_double),
        ("twist_linear_y", ctypes.c_double),
        ("twist_linear_z", ctypes.c_double),
        ("twist_angular_x", ctypes.c_double),
        ("twist_angular_y", ctypes.c_double),
        ("twist_angular_z", ctypes.c_double),
        ("covariance", ctypes.c_double * 36),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.TwistWithCovariance"


class TwistWithCovarianceStamped(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("twist_twist_linear_x", ctypes.c_double),
        ("twist_twist_linear_y", ctypes.c_double),
        ("twist_twist_linear_z", ctypes.c_double),
        ("twist_twist_angular_x", ctypes.c_double),
        ("twist_twist_angular_y", ctypes.c_double),
        ("twist_twist_angular_z", ctypes.c_double),
        ("twist_covariance", ctypes.c_double * 36),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.TwistWithCovarianceStamped"


class Vector3(ctypes.Structure):
    _fields_ = [
        ("x", ctypes.c_double),
        ("y", ctypes.c_double),
        ("z", ctypes.c_double),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.Vector3"


class Vector3Stamped(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("vector_x", ctypes.c_double),
        ("vector_y", ctypes.c_double),
        ("vector_z", ctypes.c_double),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.Vector3Stamped"


class VelocityStamped(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("body_frame_id", ctypes.c_char * 256),
        ("reference_frame_id", ctypes.c_char * 256),
        ("velocity_linear_x", ctypes.c_double),
        ("velocity_linear_y", ctypes.c_double),
        ("velocity_linear_z", ctypes.c_double),
        ("velocity_angular_x", ctypes.c_double),
        ("velocity_angular_y", ctypes.c_double),
        ("velocity_angular_z", ctypes.c_double),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.VelocityStamped"


class Wrench(ctypes.Structure):
    _fields_ = [
        ("force_x", ctypes.c_double),
        ("force_y", ctypes.c_double),
        ("force_z", ctypes.c_double),
        ("torque_x", ctypes.c_double),
        ("torque_y", ctypes.c_double),
        ("torque_z", ctypes.c_double),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.Wrench"


class WrenchStamped(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("wrench_force_x", ctypes.c_double),
        ("wrench_force_y", ctypes.c_double),
        ("wrench_force_z", ctypes.c_double),
        ("wrench_torque_x", ctypes.c_double),
        ("wrench_torque_y", ctypes.c_double),
        ("wrench_torque_z", ctypes.c_double),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.geometry_msgs.WrenchStamped"


