# @generated by ridlc --lang python — DO NOT EDIT
# source: ROS IDL package 'lifecycle_msgs'
# Payload types for the iceoryx2 Python API (ctypes.Structure + type_name())
# Re-generate: cargo run -p ridlc -- --lang python -I <lib> -o <out>

import ctypes

# Max element counts for unbounded (variable-length) array fields.
# iceoryx2 requires fixed-size payloads; these caps are the upper bound.
# Override the constant in your code before importing these types if needed.
_MAX_IMAGE_BYTES = 8294400  # 1080p RGBA upper bound
_MAX_ARRAY_ELEMS = 256  # generic upper bound for non-byte arrays


class State(ctypes.Structure):
    PRIMARY_STATE_UNKNOWN = 0
    PRIMARY_STATE_UNCONFIGURED = 1
    PRIMARY_STATE_INACTIVE = 2
    PRIMARY_STATE_ACTIVE = 3
    PRIMARY_STATE_FINALIZED = 4
    TRANSITION_STATE_CONFIGURING = 10
    TRANSITION_STATE_CLEANINGUP = 11
    TRANSITION_STATE_SHUTTINGDOWN = 12
    TRANSITION_STATE_ACTIVATING = 13
    TRANSITION_STATE_DEACTIVATING = 14
    TRANSITION_STATE_ERRORPROCESSING = 15

    _fields_ = [
        ("id", ctypes.c_uint8),
        ("label", ctypes.c_char * 256),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.lifecycle_msgs.State"


class Transition(ctypes.Structure):
    TRANSITION_CREATE = 0
    TRANSITION_CONFIGURE = 1
    TRANSITION_CLEANUP = 2
    TRANSITION_ACTIVATE = 3
    TRANSITION_DEACTIVATE = 4
    TRANSITION_UNCONFIGURED_SHUTDOWN = 5
    TRANSITION_INACTIVE_SHUTDOWN = 6
    TRANSITION_ACTIVE_SHUTDOWN = 7
    TRANSITION_DESTROY = 8
    TRANSITION_ON_CONFIGURE_SUCCESS = 10
    TRANSITION_ON_CONFIGURE_FAILURE = 11
    TRANSITION_ON_CONFIGURE_ERROR = 12
    TRANSITION_ON_CLEANUP_SUCCESS = 20
    TRANSITION_ON_CLEANUP_FAILURE = 21
    TRANSITION_ON_CLEANUP_ERROR = 22
    TRANSITION_ON_ACTIVATE_SUCCESS = 30
    TRANSITION_ON_ACTIVATE_FAILURE = 31
    TRANSITION_ON_ACTIVATE_ERROR = 32
    TRANSITION_ON_DEACTIVATE_SUCCESS = 40
    TRANSITION_ON_DEACTIVATE_FAILURE = 41
    TRANSITION_ON_DEACTIVATE_ERROR = 42
    TRANSITION_ON_SHUTDOWN_SUCCESS = 50
    TRANSITION_ON_SHUTDOWN_FAILURE = 51
    TRANSITION_ON_SHUTDOWN_ERROR = 52
    TRANSITION_ON_ERROR_SUCCESS = 60
    TRANSITION_ON_ERROR_FAILURE = 61
    TRANSITION_ON_ERROR_ERROR = 62
    TRANSITION_CALLBACK_SUCCESS = 97
    TRANSITION_CALLBACK_FAILURE = 98
    TRANSITION_CALLBACK_ERROR = 99

    _fields_ = [
        ("id", ctypes.c_uint8),
        ("label", ctypes.c_char * 256),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.lifecycle_msgs.Transition"


class TransitionDescription(ctypes.Structure):
    _fields_ = [
        ("transition_id", ctypes.c_uint8),
        ("transition_label", ctypes.c_char * 256),
        ("start_state_id", ctypes.c_uint8),
        ("start_state_label", ctypes.c_char * 256),
        ("goal_state_id", ctypes.c_uint8),
        ("goal_state_label", ctypes.c_char * 256),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.lifecycle_msgs.TransitionDescription"


class TransitionEvent(ctypes.Structure):
    _fields_ = [
        ("timestamp", ctypes.c_uint64),
        ("transition_id", ctypes.c_uint8),
        ("transition_label", ctypes.c_char * 256),
        ("start_state_id", ctypes.c_uint8),
        ("start_state_label", ctypes.c_char * 256),
        ("goal_state_id", ctypes.c_uint8),
        ("goal_state_label", ctypes.c_char * 256),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.lifecycle_msgs.TransitionEvent"


