# @generated by ridlc --lang python — DO NOT EDIT
# source: ROS IDL package 'rcl_interfaces'
# Payload types for the iceoryx2 Python API (ctypes.Structure + type_name())
# Re-generate: cargo run -p ridlc -- --lang python -I <lib> -o <out>

import ctypes

# Max element counts for unbounded (variable-length) array fields.
# iceoryx2 requires fixed-size payloads; these caps are the upper bound.
# Override the constant in your code before importing these types if needed.
_MAX_IMAGE_BYTES = 8294400  # 1080p RGBA upper bound
_MAX_ARRAY_ELEMS = 256  # generic upper bound for non-byte arrays


class FloatingPointRange(ctypes.Structure):
    _fields_ = [
        ("from_value", ctypes.c_double),
        ("to_value", ctypes.c_double),
        ("step", ctypes.c_double),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.rcl_interfaces.FloatingPointRange"


class IntegerRange(ctypes.Structure):
    _fields_ = [
        ("from_value", ctypes.c_int64),
        ("to_value", ctypes.c_int64),
        ("step", ctypes.c_uint64),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.rcl_interfaces.IntegerRange"


class ListParametersResult(ctypes.Structure):
    _fields_ = [
        # unbounded string[]; capped at _MAX_ARRAY_ELEMS
        ("names", ctypes.c_char * 256 * _MAX_ARRAY_ELEMS),
        # unbounded string[]; capped at _MAX_ARRAY_ELEMS
        ("prefixes", ctypes.c_char * 256 * _MAX_ARRAY_ELEMS),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.rcl_interfaces.ListParametersResult"


class Log(ctypes.Structure):
    DEBUG = 10
    INFO = 20
    WARN = 30
    ERROR = 40
    FATAL = 50

    _fields_ = [
        ("stamp_sec", ctypes.c_int32),
        ("stamp_nanosec", ctypes.c_uint32),
        ("level", ctypes.c_uint8),
        ("name", ctypes.c_char * 256),
        ("msg", ctypes.c_char * 256),
        ("file", ctypes.c_char * 256),
        ("function", ctypes.c_char * 256),
        ("line", ctypes.c_uint32),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.rcl_interfaces.Log"


class Parameter(ctypes.Structure):
    _fields_ = [
        ("name", ctypes.c_char * 256),
        ("value_type", ctypes.c_uint8),
        ("value_bool_value", ctypes.c_bool),
        ("value_integer_value", ctypes.c_int64),
        ("value_double_value", ctypes.c_double),
        ("value_string_value", ctypes.c_char * 256),
        # unbounded byte[]; capped at _MAX_IMAGE_BYTES
        ("value_byte_array_value", ctypes.c_uint8 * _MAX_IMAGE_BYTES),
        # unbounded bool[]; capped at _MAX_ARRAY_ELEMS
        ("value_bool_array_value", ctypes.c_bool * _MAX_ARRAY_ELEMS),
        # unbounded int64[]; capped at _MAX_ARRAY_ELEMS
        ("value_integer_array_value", ctypes.c_int64 * _MAX_ARRAY_ELEMS),
        # unbounded float64[]; capped at _MAX_ARRAY_ELEMS
        ("value_double_array_value", ctypes.c_double * _MAX_ARRAY_ELEMS),
        # unbounded string[]; capped at _MAX_ARRAY_ELEMS
        ("value_string_array_value", ctypes.c_char * 256 * _MAX_ARRAY_ELEMS),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.rcl_interfaces.Parameter"


class ParameterDescriptor(ctypes.Structure):
    _fields_ = [
        ("name", ctypes.c_char * 256),
        ("type", ctypes.c_uint8),
        ("description", ctypes.c_char * 256),
        ("additional_constraints", ctypes.c_char * 256),
        ("read_only", ctypes.c_bool),
        ("dynamic_typing", ctypes.c_bool),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.rcl_interfaces.ParameterDescriptor"


class ParameterEvent(ctypes.Structure):
    _fields_ = [
        ("stamp_sec", ctypes.c_int32),
        ("stamp_nanosec", ctypes.c_uint32),
        ("node", ctypes.c_char * 256),
        # opaque blob: rcl_interfaces/Parameter[] not flattenable
        ("new_parameters", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
        # opaque blob: rcl_interfaces/Parameter[] not flattenable
        ("changed_parameters", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
        # opaque blob: rcl_interfaces/Parameter[] not flattenable
        ("deleted_parameters", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.rcl_interfaces.ParameterEvent"


class ParameterEventDescriptors(ctypes.Structure):
    _fields_ = [
        # opaque blob: rcl_interfaces/ParameterDescriptor[] not flattenable
        ("new_parameters", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
        # opaque blob: rcl_interfaces/ParameterDescriptor[] not flattenable
        ("changed_parameters", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
        # opaque blob: rcl_interfaces/ParameterDescriptor[] not flattenable
        ("deleted_parameters", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.rcl_interfaces.ParameterEventDescriptors"


class ParameterType(ctypes.Structure):
    PARAMETER_NOT_SET = 0
    PARAMETER_BOOL = 1
    PARAMETER_INTEGER = 2
    PARAMETER_DOUBLE = 3
    PARAMETER_STRING = 4
    PARAMETER_BYTE_ARRAY = 5
    PARAMETER_BOOL_ARRAY = 6
    PARAMETER_INTEGER_ARRAY = 7
    PARAMETER_DOUBLE_ARRAY = 8
    PARAMETER_STRING_ARRAY = 9

    _fields_: list = []

    @staticmethod
    def type_name() -> str:
        return "robonix.rcl_interfaces.ParameterType"


class ParameterValue(ctypes.Structure):
    _fields_ = [
        ("type", ctypes.c_uint8),
        ("bool_value", ctypes.c_bool),
        ("integer_value", ctypes.c_int64),
        ("double_value", ctypes.c_double),
        ("string_value", ctypes.c_char * 256),
        # unbounded byte[]; capped at _MAX_IMAGE_BYTES
        ("byte_array_value", ctypes.c_uint8 * _MAX_IMAGE_BYTES),
        # unbounded bool[]; capped at _MAX_ARRAY_ELEMS
        ("bool_array_value", ctypes.c_bool * _MAX_ARRAY_ELEMS),
        # unbounded int64[]; capped at _MAX_ARRAY_ELEMS
        ("integer_array_value", ctypes.c_int64 * _MAX_ARRAY_ELEMS),
        # unbounded float64[]; capped at _MAX_ARRAY_ELEMS
        ("double_array_value", ctypes.c_double * _MAX_ARRAY_ELEMS),
        # unbounded string[]; capped at _MAX_ARRAY_ELEMS
        ("string_array_value", ctypes.c_char * 256 * _MAX_ARRAY_ELEMS),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.rcl_interfaces.ParameterValue"


class SetParametersResult(ctypes.Structure):
    _fields_ = [
        ("successful", ctypes.c_bool),
        ("reason", ctypes.c_char * 256),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.rcl_interfaces.SetParametersResult"


