# @generated by ridlc --lang python — DO NOT EDIT
# source: ROS IDL package 'sensor_msgs'
# Payload types for the iceoryx2 Python API (ctypes.Structure + type_name())
# Re-generate: cargo run -p ridlc -- --lang python -I <lib> -o <out>

import ctypes

# Max element counts for unbounded (variable-length) array fields.
# iceoryx2 requires fixed-size payloads; these caps are the upper bound.
# Override the constant in your code before importing these types if needed.
_MAX_IMAGE_BYTES = 8294400  # 1080p RGBA upper bound
_MAX_ARRAY_ELEMS = 256  # generic upper bound for non-byte arrays


class BatteryState(ctypes.Structure):
    POWER_SUPPLY_STATUS_UNKNOWN = 0
    POWER_SUPPLY_STATUS_CHARGING = 1
    POWER_SUPPLY_STATUS_DISCHARGING = 2
    POWER_SUPPLY_STATUS_NOT_CHARGING = 3
    POWER_SUPPLY_STATUS_FULL = 4
    POWER_SUPPLY_HEALTH_UNKNOWN = 0
    POWER_SUPPLY_HEALTH_GOOD = 1
    POWER_SUPPLY_HEALTH_OVERHEAT = 2
    POWER_SUPPLY_HEALTH_DEAD = 3
    POWER_SUPPLY_HEALTH_OVERVOLTAGE = 4
    POWER_SUPPLY_HEALTH_UNSPEC_FAILURE = 5
    POWER_SUPPLY_HEALTH_COLD = 6
    POWER_SUPPLY_HEALTH_WATCHDOG_TIMER_EXPIRE = 7
    POWER_SUPPLY_HEALTH_SAFETY_TIMER_EXPIRE = 8
    POWER_SUPPLY_TECHNOLOGY_UNKNOWN = 0
    POWER_SUPPLY_TECHNOLOGY_NIMH = 1
    POWER_SUPPLY_TECHNOLOGY_LION = 2
    POWER_SUPPLY_TECHNOLOGY_LIPO = 3
    POWER_SUPPLY_TECHNOLOGY_LIFE = 4
    POWER_SUPPLY_TECHNOLOGY_NICD = 5
    POWER_SUPPLY_TECHNOLOGY_LIMN = 6

    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("voltage", ctypes.c_float),
        ("temperature", ctypes.c_float),
        ("current", ctypes.c_float),
        ("charge", ctypes.c_float),
        ("capacity", ctypes.c_float),
        ("design_capacity", ctypes.c_float),
        ("percentage", ctypes.c_float),
        ("power_supply_status", ctypes.c_uint8),
        ("power_supply_health", ctypes.c_uint8),
        ("power_supply_technology", ctypes.c_uint8),
        ("present", ctypes.c_bool),
        # unbounded float32[]; capped at _MAX_ARRAY_ELEMS
        ("cell_voltage", ctypes.c_float * _MAX_ARRAY_ELEMS),
        # unbounded float32[]; capped at _MAX_ARRAY_ELEMS
        ("cell_temperature", ctypes.c_float * _MAX_ARRAY_ELEMS),
        ("location", ctypes.c_char * 256),
        ("serial_number", ctypes.c_char * 256),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.sensor_msgs.BatteryState"


class CameraInfo(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("height", ctypes.c_uint32),
        ("width", ctypes.c_uint32),
        ("distortion_model", ctypes.c_char * 256),
        # unbounded float64[]; capped at _MAX_ARRAY_ELEMS
        ("d", ctypes.c_double * _MAX_ARRAY_ELEMS),
        ("k", ctypes.c_double * 9),
        ("r", ctypes.c_double * 9),
        ("p", ctypes.c_double * 12),
        ("binning_x", ctypes.c_uint32),
        ("binning_y", ctypes.c_uint32),
        ("roi_x_offset", ctypes.c_uint32),
        ("roi_y_offset", ctypes.c_uint32),
        ("roi_height", ctypes.c_uint32),
        ("roi_width", ctypes.c_uint32),
        ("roi_do_rectify", ctypes.c_bool),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.sensor_msgs.CameraInfo"


class ChannelFloat32(ctypes.Structure):
    _fields_ = [
        ("name", ctypes.c_char * 256),
        # unbounded float32[]; capped at _MAX_ARRAY_ELEMS
        ("values", ctypes.c_float * _MAX_ARRAY_ELEMS),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.sensor_msgs.ChannelFloat32"


class CompressedImage(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("format", ctypes.c_char * 256),
        # unbounded uint8[]; capped at _MAX_IMAGE_BYTES
        ("data", ctypes.c_uint8 * _MAX_IMAGE_BYTES),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.sensor_msgs.CompressedImage"


class FluidPressure(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("fluid_pressure", ctypes.c_double),
        ("variance", ctypes.c_double),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.sensor_msgs.FluidPressure"


class Illuminance(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("illuminance", ctypes.c_double),
        ("variance", ctypes.c_double),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.sensor_msgs.Illuminance"


class Image(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("height", ctypes.c_uint32),
        ("width", ctypes.c_uint32),
        ("encoding", ctypes.c_char * 256),
        ("is_bigendian", ctypes.c_uint8),
        ("step", ctypes.c_uint32),
        # unbounded uint8[]; capped at _MAX_IMAGE_BYTES
        ("data", ctypes.c_uint8 * _MAX_IMAGE_BYTES),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.sensor_msgs.Image"


class Imu(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("orientation_x", ctypes.c_double),
        ("orientation_y", ctypes.c_double),
        ("orientation_z", ctypes.c_double),
        ("orientation_w", ctypes.c_double),
        ("orientation_covariance", ctypes.c_double * 9),
        ("angular_velocity_x", ctypes.c_double),
        ("angular_velocity_y", ctypes.c_double),
        ("angular_velocity_z", ctypes.c_double),
        ("angular_velocity_covariance", ctypes.c_double * 9),
        ("linear_acceleration_x", ctypes.c_double),
        ("linear_acceleration_y", ctypes.c_double),
        ("linear_acceleration_z", ctypes.c_double),
        ("linear_acceleration_covariance", ctypes.c_double * 9),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.sensor_msgs.Imu"


class JointState(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        # unbounded string[]; capped at _MAX_ARRAY_ELEMS
        ("name", ctypes.c_char * 256 * _MAX_ARRAY_ELEMS),
        # unbounded float64[]; capped at _MAX_ARRAY_ELEMS
        ("position", ctypes.c_double * _MAX_ARRAY_ELEMS),
        # unbounded float64[]; capped at _MAX_ARRAY_ELEMS
        ("velocity", ctypes.c_double * _MAX_ARRAY_ELEMS),
        # unbounded float64[]; capped at _MAX_ARRAY_ELEMS
        ("effort", ctypes.c_double * _MAX_ARRAY_ELEMS),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.sensor_msgs.JointState"


class Joy(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        # unbounded float32[]; capped at _MAX_ARRAY_ELEMS
        ("axes", ctypes.c_float * _MAX_ARRAY_ELEMS),
        # unbounded int32[]; capped at _MAX_ARRAY_ELEMS
        ("buttons", ctypes.c_int32 * _MAX_ARRAY_ELEMS),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.sensor_msgs.Joy"


class JoyFeedback(ctypes.Structure):
    TYPE_LED = 0
    TYPE_RUMBLE = 1
    TYPE_BUZZER = 2

    _fields_ = [
        ("type", ctypes.c_uint8),
        ("id", ctypes.c_uint8),
        ("intensity", ctypes.c_float),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.sensor_msgs.JoyFeedback"


class JoyFeedbackArray(ctypes.Structure):
    _fields_ = [
        # opaque blob: sensor_msgs/JoyFeedback[] not flattenable
        ("array", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.sensor_msgs.JoyFeedbackArray"


class LaserEcho(ctypes.Structure):
    _fields_ = [
        # unbounded float32[]; capped at _MAX_ARRAY_ELEMS
        ("echoes", ctypes.c_float * _MAX_ARRAY_ELEMS),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.sensor_msgs.LaserEcho"


class LaserScan(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("angle_min", ctypes.c_float),
        ("angle_max", ctypes.c_float),
        ("angle_increment", ctypes.c_float),
        ("time_increment", ctypes.c_float),
        ("scan_time", ctypes.c_float),
        ("range_min", ctypes.c_float),
        ("range_max", ctypes.c_float),
        # unbounded float32[]; capped at _MAX_ARRAY_ELEMS
        ("ranges", ctypes.c_float * _MAX_ARRAY_ELEMS),
        # unbounded float32[]; capped at _MAX_ARRAY_ELEMS
        ("intensities", ctypes.c_float * _MAX_ARRAY_ELEMS),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.sensor_msgs.LaserScan"


class MagneticField(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("magnetic_field_x", ctypes.c_double),
        ("magnetic_field_y", ctypes.c_double),
        ("magnetic_field_z", ctypes.c_double),
        ("magnetic_field_covariance", ctypes.c_double * 9),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.sensor_msgs.MagneticField"


class MultiDOFJointState(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        # unbounded string[]; capped at _MAX_ARRAY_ELEMS
        ("joint_names", ctypes.c_char * 256 * _MAX_ARRAY_ELEMS),
        # opaque blob: geometry_msgs/Transform[] not flattenable
        ("transforms", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
        # opaque blob: geometry_msgs/Twist[] not flattenable
        ("twist", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
        # opaque blob: geometry_msgs/Wrench[] not flattenable
        ("wrench", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.sensor_msgs.MultiDOFJointState"


class MultiEchoLaserScan(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("angle_min", ctypes.c_float),
        ("angle_max", ctypes.c_float),
        ("angle_increment", ctypes.c_float),
        ("time_increment", ctypes.c_float),
        ("scan_time", ctypes.c_float),
        ("range_min", ctypes.c_float),
        ("range_max", ctypes.c_float),
        # opaque blob: sensor_msgs/LaserEcho[] not flattenable
        ("ranges", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
        # opaque blob: sensor_msgs/LaserEcho[] not flattenable
        ("intensities", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.sensor_msgs.MultiEchoLaserScan"


class NavSatFix(ctypes.Structure):
    COVARIANCE_TYPE_UNKNOWN = 0
    COVARIANCE_TYPE_APPROXIMATED = 1
    COVARIANCE_TYPE_DIAGONAL_KNOWN = 2
    COVARIANCE_TYPE_KNOWN = 3

    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("status_status", ctypes.c_int8),
        ("status_service", ctypes.c_uint16),
        ("latitude", ctypes.c_double),
        ("longitude", ctypes.c_double),
        ("altitude", ctypes.c_double),
        ("position_covariance", ctypes.c_double * 9),
        ("position_covariance_type", ctypes.c_uint8),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.sensor_msgs.NavSatFix"


class NavSatStatus(ctypes.Structure):
    STATUS_NO_FIX = -1
    STATUS_FIX = 0
    STATUS_SBAS_FIX = 1
    STATUS_GBAS_FIX = 2
    SERVICE_GPS = 1
    SERVICE_GLONASS = 2
    SERVICE_COMPASS = 4
    SERVICE_GALILEO = 8

    _fields_ = [
        ("status", ctypes.c_int8),
        ("service", ctypes.c_uint16),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.sensor_msgs.NavSatStatus"


class PointCloud(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        # opaque blob: geometry_msgs/Point32[] not flattenable
        ("points", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
        # opaque blob: sensor_msgs/ChannelFloat32[] not flattenable
        ("channels", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.sensor_msgs.PointCloud"


class PointCloud2(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("height", ctypes.c_uint32),
        ("width", ctypes.c_uint32),
        # opaque blob: sensor_msgs/PointField[] not flattenable
        ("fields", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
        ("is_bigendian", ctypes.c_bool),
        ("point_step", ctypes.c_uint32),
        ("row_step", ctypes.c_uint32),
        # unbounded uint8[]; capped at _MAX_IMAGE_BYTES
        ("data", ctypes.c_uint8 * _MAX_IMAGE_BYTES),
        ("is_dense", ctypes.c_bool),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.sensor_msgs.PointCloud2"


class PointField(ctypes.Structure):
    INT8 = 1
    UINT8 = 2
    INT16 = 3
    UINT16 = 4
    INT32 = 5
    UINT32 = 6
    FLOAT32 = 7
    FLOAT64 = 8

    _fields_ = [
        ("name", ctypes.c_char * 256),
        ("offset", ctypes.c_uint32),
        ("datatype", ctypes.c_uint8),
        ("count", ctypes.c_uint32),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.sensor_msgs.PointField"


class Range(ctypes.Structure):
    ULTRASOUND = 0
    INFRARED = 1

    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("radiation_type", ctypes.c_uint8),
        ("field_of_view", ctypes.c_float),
        ("min_range", ctypes.c_float),
        ("max_range", ctypes.c_float),
        ("range", ctypes.c_float),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.sensor_msgs.Range"


class RegionOfInterest(ctypes.Structure):
    _fields_ = [
        ("x_offset", ctypes.c_uint32),
        ("y_offset", ctypes.c_uint32),
        ("height", ctypes.c_uint32),
        ("width", ctypes.c_uint32),
        ("do_rectify", ctypes.c_bool),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.sensor_msgs.RegionOfInterest"


class RelativeHumidity(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("relative_humidity", ctypes.c_double),
        ("variance", ctypes.c_double),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.sensor_msgs.RelativeHumidity"


class Temperature(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("temperature", ctypes.c_double),
        ("variance", ctypes.c_double),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.sensor_msgs.Temperature"


class TimeReference(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("time_ref_sec", ctypes.c_int32),
        ("time_ref_nanosec", ctypes.c_uint32),
        ("source", ctypes.c_char * 256),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.sensor_msgs.TimeReference"


