# @generated by ridlc --lang python — DO NOT EDIT
# source: ROS IDL package 'shape_msgs'
# Payload types for the iceoryx2 Python API (ctypes.Structure + type_name())
# Re-generate: cargo run -p ridlc -- --lang python -I <lib> -o <out>

import ctypes

# Max element counts for unbounded (variable-length) array fields.
# iceoryx2 requires fixed-size payloads; these caps are the upper bound.
# Override the constant in your code before importing these types if needed.
_MAX_IMAGE_BYTES = 8294400  # 1080p RGBA upper bound
_MAX_ARRAY_ELEMS = 256  # generic upper bound for non-byte arrays


class Mesh(ctypes.Structure):
    _fields_ = [
        # opaque blob: shape_msgs/MeshTriangle[] not flattenable
        ("triangles", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
        # opaque blob: geometry_msgs/Point[] not flattenable
        ("vertices", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.shape_msgs.Mesh"


class MeshTriangle(ctypes.Structure):
    _fields_ = [
        ("vertex_indices", ctypes.c_uint32 * 3),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.shape_msgs.MeshTriangle"


class Plane(ctypes.Structure):
    _fields_ = [
        ("coef", ctypes.c_double * 4),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.shape_msgs.Plane"


class SolidPrimitive(ctypes.Structure):
    BOX = 1
    SPHERE = 2
    CYLINDER = 3
    CONE = 4
    PRISM = 5
    BOX_X = 0
    BOX_Y = 1
    BOX_Z = 2
    SPHERE_RADIUS = 0
    CYLINDER_HEIGHT = 0
    CYLINDER_RADIUS = 1
    CONE_HEIGHT = 0
    CONE_RADIUS = 1
    PRISM_HEIGHT = 0

    _fields_ = [
        ("type", ctypes.c_uint8),
        # opaque blob: geometry_msgs/Point32[] not flattenable
        ("polygon_points", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.shape_msgs.SolidPrimitive"


