# @generated by ridlc --lang python — DO NOT EDIT
# source: ROS IDL package 'statistics_msgs'
# Payload types for the iceoryx2 Python API (ctypes.Structure + type_name())
# Re-generate: cargo run -p ridlc -- --lang python -I <lib> -o <out>

import ctypes

# Max element counts for unbounded (variable-length) array fields.
# iceoryx2 requires fixed-size payloads; these caps are the upper bound.
# Override the constant in your code before importing these types if needed.
_MAX_IMAGE_BYTES = 8294400  # 1080p RGBA upper bound
_MAX_ARRAY_ELEMS = 256  # generic upper bound for non-byte arrays


class MetricsMessage(ctypes.Structure):
    _fields_ = [
        ("measurement_source_name", ctypes.c_char * 256),
        ("metrics_source", ctypes.c_char * 256),
        ("unit", ctypes.c_char * 256),
        ("window_start_sec", ctypes.c_int32),
        ("window_start_nanosec", ctypes.c_uint32),
        ("window_stop_sec", ctypes.c_int32),
        ("window_stop_nanosec", ctypes.c_uint32),
        # opaque blob: statistics_msgs/StatisticDataPoint[] not flattenable
        ("statistics", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.statistics_msgs.MetricsMessage"


class StatisticDataPoint(ctypes.Structure):
    _fields_ = [
        ("data_type", ctypes.c_uint8),
        ("data", ctypes.c_double),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.statistics_msgs.StatisticDataPoint"


class StatisticDataType(ctypes.Structure):
    STATISTICS_DATA_TYPE_UNINITIALIZED = 0
    STATISTICS_DATA_TYPE_AVERAGE = 1
    STATISTICS_DATA_TYPE_MINIMUM = 2
    STATISTICS_DATA_TYPE_MAXIMUM = 3
    STATISTICS_DATA_TYPE_STDDEV = 4
    STATISTICS_DATA_TYPE_SAMPLE_COUNT = 5

    _fields_: list = []

    @staticmethod
    def type_name() -> str:
        return "robonix.statistics_msgs.StatisticDataType"


