# @generated by ridlc --lang python — DO NOT EDIT
# source: ROS IDL package 'stereo_msgs'
# Payload types for the iceoryx2 Python API (ctypes.Structure + type_name())
# Re-generate: cargo run -p ridlc -- --lang python -I <lib> -o <out>

import ctypes

# Max element counts for unbounded (variable-length) array fields.
# iceoryx2 requires fixed-size payloads; these caps are the upper bound.
# Override the constant in your code before importing these types if needed.
_MAX_IMAGE_BYTES = 8294400  # 1080p RGBA upper bound
_MAX_ARRAY_ELEMS = 256  # generic upper bound for non-byte arrays


class DisparityImage(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("image_header_stamp_sec", ctypes.c_int32),
        ("image_header_stamp_nanosec", ctypes.c_uint32),
        ("image_header_frame_id", ctypes.c_char * 256),
        ("image_height", ctypes.c_uint32),
        ("image_width", ctypes.c_uint32),
        ("image_encoding", ctypes.c_char * 256),
        ("image_is_bigendian", ctypes.c_uint8),
        ("image_step", ctypes.c_uint32),
        # unbounded uint8[]; capped at _MAX_IMAGE_BYTES
        ("image_data", ctypes.c_uint8 * _MAX_IMAGE_BYTES),
        ("f", ctypes.c_float),
        ("t", ctypes.c_float),
        ("valid_window_x_offset", ctypes.c_uint32),
        ("valid_window_y_offset", ctypes.c_uint32),
        ("valid_window_height", ctypes.c_uint32),
        ("valid_window_width", ctypes.c_uint32),
        ("valid_window_do_rectify", ctypes.c_bool),
        ("min_disparity", ctypes.c_float),
        ("max_disparity", ctypes.c_float),
        ("delta_d", ctypes.c_float),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.stereo_msgs.DisparityImage"


