# @generated by ridlc --lang python — DO NOT EDIT
# source: ROS IDL package 'visualization_msgs'
# Payload types for the iceoryx2 Python API (ctypes.Structure + type_name())
# Re-generate: cargo run -p ridlc -- --lang python -I <lib> -o <out>

import ctypes

# Max element counts for unbounded (variable-length) array fields.
# iceoryx2 requires fixed-size payloads; these caps are the upper bound.
# Override the constant in your code before importing these types if needed.
_MAX_IMAGE_BYTES = 8294400  # 1080p RGBA upper bound
_MAX_ARRAY_ELEMS = 256  # generic upper bound for non-byte arrays


class ImageMarker(ctypes.Structure):
    CIRCLE = 0
    LINE_STRIP = 1
    LINE_LIST = 2
    POLYGON = 3
    POINTS = 4
    ADD = 0
    REMOVE = 1

    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("ns", ctypes.c_char * 256),
        ("id", ctypes.c_int32),
        ("type", ctypes.c_int32),
        ("action", ctypes.c_int32),
        ("position_x", ctypes.c_double),
        ("position_y", ctypes.c_double),
        ("position_z", ctypes.c_double),
        ("scale", ctypes.c_float),
        ("outline_color_r", ctypes.c_float),
        ("outline_color_g", ctypes.c_float),
        ("outline_color_b", ctypes.c_float),
        ("outline_color_a", ctypes.c_float),
        ("filled", ctypes.c_uint8),
        ("fill_color_r", ctypes.c_float),
        ("fill_color_g", ctypes.c_float),
        ("fill_color_b", ctypes.c_float),
        ("fill_color_a", ctypes.c_float),
        ("lifetime_sec", ctypes.c_int32),
        ("lifetime_nanosec", ctypes.c_uint32),
        # opaque blob: geometry_msgs/Point[] not flattenable
        ("points", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
        # opaque blob: std_msgs/ColorRGBA[] not flattenable
        ("outline_colors", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.visualization_msgs.ImageMarker"


class InteractiveMarker(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("pose_position_x", ctypes.c_double),
        ("pose_position_y", ctypes.c_double),
        ("pose_position_z", ctypes.c_double),
        ("pose_orientation_x", ctypes.c_double),
        ("pose_orientation_y", ctypes.c_double),
        ("pose_orientation_z", ctypes.c_double),
        ("pose_orientation_w", ctypes.c_double),
        ("name", ctypes.c_char * 256),
        ("description", ctypes.c_char * 256),
        ("scale", ctypes.c_float),
        # opaque blob: visualization_msgs/MenuEntry[] not flattenable
        ("menu_entries", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
        # opaque blob: visualization_msgs/InteractiveMarkerControl[] not flattenable
        ("controls", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.visualization_msgs.InteractiveMarker"


class InteractiveMarkerControl(ctypes.Structure):
    INHERIT = 0
    FIXED = 1
    VIEW_FACING = 2
    NONE = 0
    MENU = 1
    BUTTON = 2
    MOVE_AXIS = 3
    MOVE_PLANE = 4
    ROTATE_AXIS = 5
    MOVE_ROTATE = 6
    MOVE_3D = 7
    ROTATE_3D = 8
    MOVE_ROTATE_3D = 9

    _fields_ = [
        ("name", ctypes.c_char * 256),
        ("orientation_x", ctypes.c_double),
        ("orientation_y", ctypes.c_double),
        ("orientation_z", ctypes.c_double),
        ("orientation_w", ctypes.c_double),
        ("orientation_mode", ctypes.c_uint8),
        ("interaction_mode", ctypes.c_uint8),
        ("always_visible", ctypes.c_bool),
        # opaque blob: visualization_msgs/Marker[] not flattenable
        ("markers", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
        ("independent_marker_orientation", ctypes.c_bool),
        ("description", ctypes.c_char * 256),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.visualization_msgs.InteractiveMarkerControl"


class InteractiveMarkerFeedback(ctypes.Structure):
    KEEP_ALIVE = 0
    POSE_UPDATE = 1
    MENU_SELECT = 2
    BUTTON_CLICK = 3
    MOUSE_DOWN = 4
    MOUSE_UP = 5

    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("client_id", ctypes.c_char * 256),
        ("marker_name", ctypes.c_char * 256),
        ("control_name", ctypes.c_char * 256),
        ("event_type", ctypes.c_uint8),
        ("pose_position_x", ctypes.c_double),
        ("pose_position_y", ctypes.c_double),
        ("pose_position_z", ctypes.c_double),
        ("pose_orientation_x", ctypes.c_double),
        ("pose_orientation_y", ctypes.c_double),
        ("pose_orientation_z", ctypes.c_double),
        ("pose_orientation_w", ctypes.c_double),
        ("menu_entry_id", ctypes.c_uint32),
        ("mouse_point_x", ctypes.c_double),
        ("mouse_point_y", ctypes.c_double),
        ("mouse_point_z", ctypes.c_double),
        ("mouse_point_valid", ctypes.c_bool),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.visualization_msgs.InteractiveMarkerFeedback"


class InteractiveMarkerInit(ctypes.Structure):
    _fields_ = [
        ("server_id", ctypes.c_char * 256),
        ("seq_num", ctypes.c_uint64),
        # opaque blob: visualization_msgs/InteractiveMarker[] not flattenable
        ("markers", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.visualization_msgs.InteractiveMarkerInit"


class InteractiveMarkerPose(ctypes.Structure):
    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("pose_position_x", ctypes.c_double),
        ("pose_position_y", ctypes.c_double),
        ("pose_position_z", ctypes.c_double),
        ("pose_orientation_x", ctypes.c_double),
        ("pose_orientation_y", ctypes.c_double),
        ("pose_orientation_z", ctypes.c_double),
        ("pose_orientation_w", ctypes.c_double),
        ("name", ctypes.c_char * 256),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.visualization_msgs.InteractiveMarkerPose"


class InteractiveMarkerUpdate(ctypes.Structure):
    KEEP_ALIVE = 0
    UPDATE = 1

    _fields_ = [
        ("server_id", ctypes.c_char * 256),
        ("seq_num", ctypes.c_uint64),
        ("type", ctypes.c_uint8),
        # opaque blob: visualization_msgs/InteractiveMarker[] not flattenable
        ("markers", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
        # opaque blob: visualization_msgs/InteractiveMarkerPose[] not flattenable
        ("poses", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
        # unbounded string[]; capped at _MAX_ARRAY_ELEMS
        ("erases", ctypes.c_char * 256 * _MAX_ARRAY_ELEMS),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.visualization_msgs.InteractiveMarkerUpdate"


class Marker(ctypes.Structure):
    ARROW = 0
    CUBE = 1
    SPHERE = 2
    CYLINDER = 3
    LINE_STRIP = 4
    LINE_LIST = 5
    CUBE_LIST = 6
    SPHERE_LIST = 7
    POINTS = 8
    TEXT_VIEW_FACING = 9
    MESH_RESOURCE = 10
    TRIANGLE_LIST = 11
    ADD = 0
    MODIFY = 0
    DELETE = 2
    DELETEALL = 3

    _fields_ = [
        ("header_stamp_sec", ctypes.c_int32),
        ("header_stamp_nanosec", ctypes.c_uint32),
        ("header_frame_id", ctypes.c_char * 256),
        ("ns", ctypes.c_char * 256),
        ("id", ctypes.c_int32),
        ("type", ctypes.c_int32),
        ("action", ctypes.c_int32),
        ("pose_position_x", ctypes.c_double),
        ("pose_position_y", ctypes.c_double),
        ("pose_position_z", ctypes.c_double),
        ("pose_orientation_x", ctypes.c_double),
        ("pose_orientation_y", ctypes.c_double),
        ("pose_orientation_z", ctypes.c_double),
        ("pose_orientation_w", ctypes.c_double),
        ("scale_x", ctypes.c_double),
        ("scale_y", ctypes.c_double),
        ("scale_z", ctypes.c_double),
        ("color_r", ctypes.c_float),
        ("color_g", ctypes.c_float),
        ("color_b", ctypes.c_float),
        ("color_a", ctypes.c_float),
        ("lifetime_sec", ctypes.c_int32),
        ("lifetime_nanosec", ctypes.c_uint32),
        ("frame_locked", ctypes.c_bool),
        # opaque blob: geometry_msgs/Point[] not flattenable
        ("points", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
        # opaque blob: std_msgs/ColorRGBA[] not flattenable
        ("colors", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
        ("texture_resource", ctypes.c_char * 256),
        ("texture_header_stamp_sec", ctypes.c_int32),
        ("texture_header_stamp_nanosec", ctypes.c_uint32),
        ("texture_header_frame_id", ctypes.c_char * 256),
        ("texture_format", ctypes.c_char * 256),
        # unbounded uint8[]; capped at _MAX_IMAGE_BYTES
        ("texture_data", ctypes.c_uint8 * _MAX_IMAGE_BYTES),
        # opaque blob: visualization_msgs/UVCoordinate[] not flattenable
        ("uv_coordinates", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
        ("text", ctypes.c_char * 256),
        ("mesh_resource", ctypes.c_char * 256),
        ("mesh_file_filename", ctypes.c_char * 256),
        # unbounded uint8[]; capped at _MAX_IMAGE_BYTES
        ("mesh_file_data", ctypes.c_uint8 * _MAX_IMAGE_BYTES),
        ("mesh_use_embedded_materials", ctypes.c_bool),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.visualization_msgs.Marker"


class MarkerArray(ctypes.Structure):
    _fields_ = [
        # opaque blob: visualization_msgs/Marker[] not flattenable
        ("markers", ctypes.c_uint8 * _MAX_ARRAY_ELEMS * 64),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.visualization_msgs.MarkerArray"


class MenuEntry(ctypes.Structure):
    FEEDBACK = 0
    ROSRUN = 1
    ROSLAUNCH = 2

    _fields_ = [
        ("id", ctypes.c_uint32),
        ("parent_id", ctypes.c_uint32),
        ("title", ctypes.c_char * 256),
        ("command", ctypes.c_char * 256),
        ("command_type", ctypes.c_uint8),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.visualization_msgs.MenuEntry"


class MeshFile(ctypes.Structure):
    _fields_ = [
        ("filename", ctypes.c_char * 256),
        # unbounded uint8[]; capped at _MAX_IMAGE_BYTES
        ("data", ctypes.c_uint8 * _MAX_IMAGE_BYTES),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.visualization_msgs.MeshFile"


class UVCoordinate(ctypes.Structure):
    _fields_ = [
        ("u", ctypes.c_float),
        ("v", ctypes.c_float),
    ]

    @staticmethod
    def type_name() -> str:
        return "robonix.visualization_msgs.UVCoordinate"


