[package]
name = "robonix-server"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
env_logger = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
tokio = { version = "1.49", features = ["full"] }
tonic = "0.14.5"
prost = "0.14.3"
uuid = { version = "1.22.0", features = ["v4"] }
tonic-prost = "0.14.5"
rclrs = "0.7.0"
rosidl_runtime_rs = "0.6.0"
libloading = "0.8"

[build-dependencies]
protoc-bin-vendored = "3.2.0"
tonic-build = "0.14.5"
tonic-prost-build = "0.14.5"
ridlc = { path = "../ridlc" }
