#!/usr/bin/env python3
# pyright: reportArgumentType=false
"""Tiago robot bridge node: ROS2 ↔ MCP for robonix agent.

Subscribes to ROS2 topics (camera, pose, scan) and exposes them as MCP tools
that the robonix agent can call.  Each MCP tool maps to exactly one contract.

Contract → MCP tool mapping:
  robonix/prm/camera/snapshot       → camera_snapshot()
  robonix/prm/camera/depth_snapshot → camera_depth_snapshot()
  robonix/prm/robot/state           → robot_state()
  robonix/prm/sensor/lidar_snapshot → lidar_snapshot()
  robonix/prm/base/navigate         → base_navigate(pose: PoseStamped)
  robonix/prm/base/nav_status       → base_nav_status(msg: String)
  robonix/prm/base/nav_cancel       → base_nav_cancel(msg: String)
  robonix/prm/base/cmd              → base_cmd(msg: MoveCommand)

Optional env vars:
  ROBONIX_ATLAS            Control-plane address (default: localhost:50051)
  ROBONIX_NODE_ID          Registry node id (default: com.robonix.prm.tiago)
  ROBONIX_DISTRO           Distro label for QueryNodes (default: humble)
  ROBONIX_CONTAINER_ID     Container label for QueryNodes (default: empty)
  ROBONIX_MCP_LISTEN_PORT  Free TCP port for MCP HTTP (0 = auto).
  ROBONIX_PRM_GRPC_LISTEN_PORT  Fixed port for PRM camera gRPC.
  TIAGO_RGB_STREAM_HZ      gRPC PrmCameraRgb.Stream max rate (default: 2)
  TIAGO_RGB_FRAME_ID       frame_id in streamed sensor_msgs/Image
  TIAGO_ROS_DOMAIN         ROS_DOMAIN_ID (default: unset)
  TIAGO_BASE_CMD_DURATION_SEC  How long to publish cmd_vel for base_cmd (not in MoveCommand.msg; default 1.0)
"""
import json
import logging
import math
import os
import queue
import socket
import sys
import threading
import time
import uuid
from io import BytesIO
from pathlib import Path

import numpy as np

for _logger_name in (
    "mcp", "mcp.server", "mcp.server.streamable_http",
    "mcp.server.streamable_http_manager",
    "httpx", "httpcore", "uvicorn", "uvicorn.access",
):
    logging.getLogger(_logger_name).setLevel(logging.WARNING)


def _ensure_proto_gen() -> None:
    """Resolve package-local proto_gen (tiago_bridge/proto_gen) for repo and Docker layouts."""
    d = Path(__file__).resolve().parent
    while d.parent != d:
        pg = d / "proto_gen"
        if pg.is_dir() and (pg / "robonix_runtime_pb2.py").exists():
            sys.path.insert(0, str(pg))
            return
        d = d.parent


def _ensure_mcp_types() -> None:
    """Find robonix_mcp_types/ generated by robonix-codegen --lang mcp and add to path."""
    d = Path(__file__).resolve().parent
    while d.parent != d:
        mt = d / "robonix_mcp_types"
        if mt.is_dir() and (mt / "__init__.py").exists():
            if str(mt) not in sys.path:
                sys.path.insert(0, str(mt))
            return
        d = d.parent


def _ensure_robonix_mcp_contract() -> None:
    """Find ``examples/packages/robonix_mcp_contract`` and add to ``sys.path``."""
    d = Path(__file__).resolve().parent
    while d.parent != d:
        cand = d / "robonix_mcp_contract"
        if cand.is_dir() and (cand / "robonix_mcp_contract" / "__init__.py").exists():
            if str(cand) not in sys.path:
                sys.path.insert(0, str(cand))
            return
        d = d.parent


_ensure_proto_gen()
_ensure_mcp_types()
_ensure_robonix_mcp_contract()

from robonix_mcp_contract import mcp_contract  # noqa: E402
from mcp.server.fastmcp import FastMCP  # noqa: E402

import grpc
from concurrent import futures as _grpc_futures
from google.protobuf import empty_pb2

import robonix_contracts_pb2_grpc
import sensor_msgs_pb2
import robonix_runtime_pb2 as pb
import robonix_runtime_pb2_grpc as pb_grpc

# Contract IDL types (robonix-codegen --lang mcp → tiago_bridge/robonix_mcp_types/)
import builtin_interfaces_mcp
import std_msgs_mcp
import sensor_msgs_mcp
import prm_base_mcp
from geometry_msgs_mcp import PoseStamped
from prm_base_mcp import MoveCommand, RobotState
from sensor_msgs_mcp import Image, LaserScan
from std_msgs_mcp import Empty, String

# ── ROS2 imports (deferred so the file can be syntax-checked without ROS) ────

_rclpy = None
_Image = None
_CompressedImage = None
_PoseWithCovarianceStamped = None
_PoseStamped = None
_Twist = None
_LaserScan = None
_NavigateToPose = None
_GoalStatus = None


def _import_ros2():
    """Lazy-import ROS2 dependencies."""
    global _rclpy, _Image, _CompressedImage, _PoseWithCovarianceStamped
    global _PoseStamped, _Twist, _LaserScan, _NavigateToPose, _GoalStatus

    import rclpy  # type: ignore
    from sensor_msgs.msg import Image, CompressedImage, LaserScan  # type: ignore
    from geometry_msgs.msg import PoseWithCovarianceStamped, PoseStamped as RosPoseStamped, Twist  # type: ignore

    _rclpy = rclpy
    _Image = Image
    _CompressedImage = CompressedImage
    _PoseWithCovarianceStamped = PoseWithCovarianceStamped
    _PoseStamped = RosPoseStamped
    _Twist = Twist
    _LaserScan = LaserScan

    try:
        from nav2_msgs.action import NavigateToPose  # type: ignore
        _NavigateToPose = NavigateToPose
    except ImportError:
        print("[tiago-node] WARNING: nav2_msgs not available, navigate action disabled")

    try:
        from action_msgs.msg import GoalStatus  # type: ignore
        _GoalStatus = GoalStatus
    except ImportError:
        _GoalStatus = None


# ── MCP server + shared state ─────────────────────────────────────────────────

mcp = FastMCP("tiago-node")

_latest_rgb: bytes | None = None
_latest_depth: bytes | None = None
_latest_pose: dict | None = None
_latest_scan_msg = None   # raw ROS LaserScan msg
_ros_node = None
_lock = threading.Lock()

_RGB_ROS_TOPIC: str | None = None
_rgb_remap_pub = None

_nav_queue: "queue.Queue[tuple[str, float, float, float, str]]" = queue.Queue()
_nav_client = None
_nav_action_ready = False
_goal_states: dict[str, dict] = {}
_goal_handles: dict[str, object] = {}

_goal_pub = None
_cmd_vel_pub = None


def _goal_status_name(status: int) -> str:
    if _GoalStatus is None:
        return str(int(status))
    g = _GoalStatus
    m = {
        int(g.STATUS_UNKNOWN): "UNKNOWN",
        int(g.STATUS_ACCEPTED): "ACCEPTED",
        int(g.STATUS_EXECUTING): "EXECUTING",
        int(g.STATUS_CANCELING): "CANCELING",
        int(g.STATUS_SUCCEEDED): "SUCCEEDED",
        int(g.STATUS_CANCELED): "CANCELED",
        int(g.STATUS_ABORTED): "ABORTED",
    }
    return m.get(int(status), str(int(status)))


def _ros2_image_to_jpeg(msg) -> bytes:
    """Convert a ROS2 sensor_msgs/Image to JPEG bytes."""
    h, w = msg.height, msg.width
    encoding = msg.encoding.lower()

    if encoding in ("rgb8",):
        arr = np.frombuffer(msg.data, dtype=np.uint8).reshape(h, w, 3)
    elif encoding in ("bgr8",):
        arr = np.frombuffer(msg.data, dtype=np.uint8).reshape(h, w, 3)
        arr = arr[:, :, ::-1]
    elif encoding in ("rgba8",):
        arr = np.frombuffer(msg.data, dtype=np.uint8).reshape(h, w, 4)[:, :, :3]
    elif encoding in ("bgra8",):
        arr = np.frombuffer(msg.data, dtype=np.uint8).reshape(h, w, 4)
        arr = arr[:, :, 2::-1]
    elif encoding in ("mono8", "8uc1"):
        arr = np.frombuffer(msg.data, dtype=np.uint8).reshape(h, w)
        arr = np.stack([arr, arr, arr], axis=-1)
    elif encoding in ("16uc1", "mono16"):
        raw = np.frombuffer(msg.data, dtype=np.uint16).reshape(h, w)
        arr = (raw / raw.max() * 255).astype(np.uint8) if raw.max() > 0 else np.zeros((h, w), np.uint8)
        arr = np.stack([arr, arr, arr], axis=-1)
    elif encoding in ("32fc1",):
        raw = np.frombuffer(msg.data, dtype=np.float32).reshape(h, w)
        valid = np.isfinite(raw)
        if valid.any():
            mn, mx = raw[valid].min(), raw[valid].max()
            norm = np.where(valid, (raw - mn) / max(mx - mn, 1e-6) * 255, 0).astype(np.uint8)
        else:
            norm = np.zeros((h, w), np.uint8)
        arr = np.stack([norm, norm, norm], axis=-1)
    else:
        raise ValueError(f"unsupported image encoding: {encoding}")

    from PIL import Image as PILImage
    buf = BytesIO()
    PILImage.fromarray(np.ascontiguousarray(arr)).save(buf, format="JPEG", quality=85)
    return buf.getvalue()


def _ros_laserscan_to_mcp(msg) -> LaserScan:
    """ROS 2 `sensor_msgs/msg/LaserScan` → codegen `LaserScan` (incl. `header`)."""
    h = msg.header
    stamp = builtin_interfaces_mcp.Time(sec=int(h.stamp.sec), nanosec=int(h.stamp.nanosec))
    header = std_msgs_mcp.Header(stamp=stamp, frame_id=str(h.frame_id))
    intensities = [float(x) for x in msg.intensities] if len(msg.intensities) else []
    return LaserScan(
        header=header,
        angle_min=float(msg.angle_min),
        angle_max=float(msg.angle_max),
        angle_increment=float(msg.angle_increment),
        time_increment=float(msg.time_increment),
        scan_time=float(msg.scan_time),
        range_min=float(msg.range_min),
        range_max=float(msg.range_max),
        ranges=[float(r) for r in msg.ranges],
        intensities=intensities,
    )


def _mcp_header_now(frame_id: str) -> std_msgs_mcp.Header:
    now = time.time()
    sec = int(now)
    ns = int((now % 1) * 1e9) % 1_000_000_000
    return std_msgs_mcp.Header(
        stamp=builtin_interfaces_mcp.Time(sec=sec, nanosec=ns),
        frame_id=frame_id,
    )


def _image_error(message: str) -> Image:
    """Valid `sensor_msgs/Image` carrying an error (encoding=`error`, UTF-8 payload in data)."""
    raw = message.encode("utf-8")
    return Image(
        header=_mcp_header_now("tiago_bridge_error"),
        height=0,
        width=0,
        encoding="error",
        is_bigendian=0,
        step=len(raw),
        data=raw,
    )


def _jpeg_to_image_mcp(jpg: bytes, frame_id: str) -> Image:
    from PIL import Image as PILImage
    im = PILImage.open(BytesIO(jpg))
    w, h = im.size
    return Image(
        header=_mcp_header_now(frame_id),
        height=h,
        width=w,
        encoding="jpeg",
        is_bigendian=0,
        step=len(jpg),
        data=jpg,
    )


def _laserscan_error(message: str) -> LaserScan:
    """Valid `sensor_msgs/LaserScan` with empty `ranges`; short error hint in `header.frame_id`."""
    fid = "error:" + message.replace("\n", " ")[:200]
    return LaserScan(
        header=_mcp_header_now(fid),
        ranges=[],
        intensities=[],
    )


# ── MCP tools (one per contract) ─────────────────────────────────────────────


# Contract: robonix/prm/camera/snapshot
# input: std_msgs/msg/Empty  output: sensor_msgs/msg/Image
@mcp_contract(
    mcp,
    contract_id="robonix/prm/camera/snapshot",
)
def camera_snapshot(msg: Empty) -> Image:
    """Get the current RGB camera image from the robot's head camera.
    Contract: robonix/prm/camera/snapshot.
    Returns codegen `sensor_msgs/Image` (JPEG in `data`)."""
    _ = msg
    with _lock:
        data = _latest_rgb
    if data is None:
        return _image_error("no RGB image received yet")
    fid = os.environ.get("TIAGO_RGB_FRAME_ID", "head_front_camera_rgb_optical_frame")
    return _jpeg_to_image_mcp(data, fid)


# Contract: robonix/prm/camera/depth_snapshot
# input: std_msgs/msg/Empty  output: sensor_msgs/msg/Image
@mcp_contract(
    mcp,
    contract_id="robonix/prm/camera/depth_snapshot",
)
def camera_depth_snapshot(msg: Empty) -> Image:
    """Get the current depth image from the robot's head camera (normalized to grayscale JPEG).
    Contract: robonix/prm/camera/depth_snapshot.
    Returns codegen `sensor_msgs/Image`."""
    _ = msg
    with _lock:
        data = _latest_depth
    if data is None:
        return _image_error("no depth image received yet")
    fid = os.environ.get("TIAGO_DEPTH_FRAME_ID", "head_front_camera_depth_optical_frame")
    return _jpeg_to_image_mcp(data, fid)


# Contract: robonix/prm/robot/state
# input: std_msgs/msg/Empty  output: prm_base/msg/RobotState
@mcp_contract(
    mcp,
    contract_id="robonix/prm/robot/state",
)
def robot_state(msg: Empty) -> RobotState:
    """Get the robot's current state (pose, joint state, gripper).
    Contract: robonix/prm/robot/state.
    Returns codegen `prm_base/RobotState`; base_pose from AMCL when available."""
    _ = msg
    with _lock:
        pose = _latest_pose
    state = RobotState()
    if pose is not None:
        bp = PoseStamped()
        bp.header.frame_id = pose.get("frame", "map")
        pos = pose.get("position", {})
        bp.pose.position.x = float(pos.get("x", 0.0))
        bp.pose.position.y = float(pos.get("y", 0.0))
        bp.pose.position.z = float(pos.get("z", 0.0))
        ori = pose.get("orientation", {})
        bp.pose.orientation.x = float(ori.get("x", 0.0))
        bp.pose.orientation.y = float(ori.get("y", 0.0))
        bp.pose.orientation.z = float(ori.get("z", 0.0))
        bp.pose.orientation.w = float(ori.get("w", 1.0))
        state.base_pose = bp
    return state


# Contract: robonix/prm/sensor/lidar_snapshot
# input: std_msgs/msg/Empty  output: sensor_msgs/msg/LaserScan
@mcp_contract(
    mcp,
    contract_id="robonix/prm/sensor/lidar_snapshot",
)
def lidar_snapshot(msg: Empty) -> LaserScan:
    """Get the latest lidar scan.
    Contract: robonix/prm/sensor/lidar_snapshot.
    Returns codegen `sensor_msgs/LaserScan`."""
    _ = msg
    with _lock:
        ros_scan = _latest_scan_msg
    if ros_scan is None:
        return _laserscan_error("no lidar scan received yet")
    return _ros_laserscan_to_mcp(ros_scan)


# Contract: robonix/prm/base/navigate
# input: geometry_msgs/msg/PoseStamped  output: std_msgs/msg/String
@mcp_contract(
    mcp,
    contract_id="robonix/prm/base/navigate",
)
def base_navigate(msg: PoseStamped) -> String:
    """Send the robot to a target pose.
    Contract: robonix/prm/base/navigate.
    pose: geometry_msgs/PoseStamped (codegen).
    Returns codegen `std_msgs/String`; `data` is JSON with goal_id / error."""
    if _ros_node is None:
        return String(data=json.dumps({"error": "ROS2 node not initialized"}))

    frame_id = msg.header.frame_id or "map"
    x = msg.pose.position.x
    y = msg.pose.position.y
    qz = msg.pose.orientation.z
    qw = msg.pose.orientation.w
    yaw = 2.0 * math.atan2(qz, qw)

    gid = str(uuid.uuid4())
    _nav_queue.put((gid, float(x), float(y), float(yaw), frame_id))
    with _lock:
        _goal_states[gid] = {"status": "QUEUED", "accepted": False}
    result = {"goal_id": gid, "status": "queued", "nav_action": _nav_action_ready}
    return String(data=json.dumps(result))


# Contract: robonix/prm/base/nav_status
# input: std_msgs/msg/String (data = goal_id)  output: std_msgs/msg/String (data = status JSON)
@mcp_contract(
    mcp,
    contract_id="robonix/prm/base/nav_status",
)
def base_nav_status(msg: String) -> String:
    """Return stored navigation status for a goal_id.
    Contract: robonix/prm/base/nav_status.
    msg.data is the goal_id from base_navigate.
    Returns codegen `std_msgs/String`; `data` is JSON status."""
    gid = msg.data
    with _lock:
        st = _goal_states.get(gid)
    if st is None:
        result = {"error": "unknown goal_id", "goal_id": gid}
    else:
        result = {"goal_id": gid, **st}
    return String(data=json.dumps(result))


# Contract: robonix/prm/base/nav_cancel
# input: std_msgs/msg/String (data = goal_id)  output: std_msgs/msg/String (data = status JSON)
@mcp_contract(
    mcp,
    contract_id="robonix/prm/base/nav_cancel",
)
def base_nav_cancel(msg: String) -> String:
    """Request cancellation of a navigation goal (Nav2 action only).
    Contract: robonix/prm/base/nav_cancel.
    msg.data is the goal_id from base_navigate.
    Returns codegen `std_msgs/String`; `data` is JSON status."""
    gid = msg.data
    with _lock:
        gh = _goal_handles.get(gid)
    if gh is None:
        result = {"error": "no active goal handle for goal_id", "goal_id": gid}
    else:
        gh.cancel_goal_async()  # type: ignore[union-attr]
        result = {"goal_id": gid, "status": "cancel_requested"}
    return String(data=json.dumps(result))


# Contract: robonix/prm/base/cmd
# input: prm_base/msg/MoveCommand  output: std_msgs/msg/String
@mcp_contract(
    mcp,
    contract_id="robonix/prm/base/cmd",
)
def base_cmd(msg: MoveCommand) -> String:
    """Send a velocity command to the robot base.
    Contract: robonix/prm/base/cmd.
    cmd: prm_base/MoveCommand. Publish duration: env `TIAGO_BASE_CMD_DURATION_SEC` (default 1.0).
    Returns codegen `std_msgs/String`; `data` is JSON execution status."""
    if _ros_node is None:
        return String(data=json.dumps({"error": "ROS2 node not initialized"}))

    duration = float(os.environ.get("TIAGO_BASE_CMD_DURATION_SEC", "1.0"))

    from geometry_msgs.msg import Twist  # type: ignore
    tw = Twist()
    tw.linear.x = float(msg.linear_x)
    tw.linear.y = float(msg.linear_y)
    tw.linear.z = float(msg.linear_z)
    tw.angular.x = float(msg.angular_x)
    tw.angular.y = float(msg.angular_y)
    tw.angular.z = float(msg.angular_z)

    stop = Twist()
    steps = max(1, int(duration / 0.1))
    for _ in range(steps):
        _cmd_vel_pub.publish(tw)
        time.sleep(0.1)
    _cmd_vel_pub.publish(stop)

    result = {
        "status": "done",
        "linear_x": msg.linear_x,
        "angular_z": msg.angular_z,
        "duration": duration,
    }
    return String(data=json.dumps(result))


# ── ROS2 subscriber callbacks ─────────────────────────────────────────────────

def _on_rgb(msg):
    global _latest_rgb
    try:
        data = _ros2_image_to_jpeg(msg)
        with _lock:
            _latest_rgb = data
        pub = _rgb_remap_pub
        if pub is not None:
            pub.publish(msg)
    except Exception as e:
        print(f"[tiago-node] RGB conversion error: {e}")


def _on_depth(msg):
    global _latest_depth
    try:
        data = _ros2_image_to_jpeg(msg)
        with _lock:
            _latest_depth = data
    except Exception as e:
        print(f"[tiago-node] Depth conversion error: {e}")


def _on_pose(msg):
    global _latest_pose
    p = msg.pose.pose
    with _lock:
        _latest_pose = {
            "frame": msg.header.frame_id,
            "position": {"x": p.position.x, "y": p.position.y, "z": p.position.z},
            "orientation": {
                "x": p.orientation.x, "y": p.orientation.y,
                "z": p.orientation.z, "w": p.orientation.w,
            },
        }


def _on_scan(msg):
    global _latest_scan_msg
    with _lock:
        _latest_scan_msg = msg


def _make_pose_stamped(node, frame_id: str, x: float, y: float, yaw: float):
    goal = _PoseStamped()
    goal.header.frame_id = frame_id
    goal.header.stamp = node.get_clock().now().to_msg()
    goal.pose.position.x = float(x)
    goal.pose.position.y = float(y)
    goal.pose.position.z = 0.0
    goal.pose.orientation.z = math.sin(yaw / 2.0)
    goal.pose.orientation.w = math.cos(yaw / 2.0)
    return goal


def _feedback_cb(gid: str, _feedback):
    with _lock:
        if gid in _goal_states:
            _goal_states[gid]["feedback"] = "navigating"


def _goal_response_cb(fut, gid: str):
    global _goal_handles
    try:
        gh = fut.result()
    except Exception as e:
        with _lock:
            _goal_states[gid] = {"status": "FAILED", "accepted": False, "error": str(e)}
        return
    if not gh.accepted:
        with _lock:
            _goal_states[gid] = {"status": "REJECTED", "accepted": False}
        return
    with _lock:
        _goal_handles[gid] = gh
        _goal_states[gid] = {"status": "ACCEPTED", "accepted": True}
    res_fut = gh.get_result_async()
    res_fut.add_done_callback(lambda f: _result_cb(f, gid))


def _result_cb(fut, gid: str):
    try:
        res = fut.result()
        status = getattr(res, "status", None)
        st_name = _goal_status_name(status) if status is not None else "UNKNOWN"
        with _lock:
            _goal_states[gid] = {"status": st_name, "accepted": True, "terminal": True}
            _goal_handles.pop(gid, None)
    except Exception as e:
        with _lock:
            _goal_states[gid] = {"status": "FAILED", "accepted": True, "error": str(e), "terminal": True}
            _goal_handles.pop(gid, None)


def _dispatch_nav_goal(node, gid: str, x: float, y: float, yaw: float, frame_id: str):
    global _nav_client
    pose = _make_pose_stamped(node, frame_id, x, y, yaw)
    if _nav_client is not None and _nav_action_ready:
        goal_msg = _NavigateToPose.Goal()
        goal_msg.pose = pose
        send_future = _nav_client.send_goal_async(  # type: ignore[union-attr]
            goal_msg,
            feedback_callback=lambda fb: _feedback_cb(gid, fb),
        )
        send_future.add_done_callback(lambda f, g=gid: _goal_response_cb(f, g))
        with _lock:
            _goal_states[gid] = {"status": "SENT", "accepted": False}
        return
    _goal_pub.publish(pose)
    with _lock:
        _goal_states[gid] = {"status": "PUBLISHED_TOPIC", "accepted": True, "topic": "/goal_pose"}


def _start_ros2():
    """Initialize ROS2 node, subscriptions, optional Nav2 action client, spin."""
    global _ros_node, _goal_pub, _cmd_vel_pub, _nav_client, _nav_action_ready, _rgb_remap_pub
    _import_ros2()
    _rclpy.init()

    from rclpy.executors import MultiThreadedExecutor  # type: ignore
    from rclpy.action import ActionClient  # type: ignore

    node = _rclpy.create_node("tiago_robonix_bridge")
    _ros_node = node

    rgb_topic = os.environ.get("TIAGO_RGB_TOPIC", "/head_front_camera/rgb/image_raw")
    depth_topic = os.environ.get("TIAGO_DEPTH_TOPIC", "/head_front_camera/depth_registered/image_raw")
    scan_topic = os.environ.get("TIAGO_SCAN_TOPIC", "/scanner/scan")

    node.create_subscription(_Image, rgb_topic, _on_rgb, 1)
    node.create_subscription(_Image, depth_topic, _on_depth, 1)

    if _RGB_ROS_TOPIC:
        _rgb_remap_pub = node.create_publisher(_Image, _RGB_ROS_TOPIC, 1)
        print(f"[tiago-node] PRM camera_rgb ROS2 republish → {_RGB_ROS_TOPIC!r}")
    node.create_subscription(_PoseWithCovarianceStamped, "/amcl_pose", _on_pose, 1)
    node.create_subscription(_LaserScan, scan_topic, _on_scan, 1)

    _goal_pub = node.create_publisher(_PoseStamped, "/goal_pose", 1)
    _cmd_vel_pub = node.create_publisher(_Twist, "/cmd_vel", 1)

    if _NavigateToPose is not None:
        _nav_client = ActionClient(node, _NavigateToPose, "navigate_to_pose")
        _nav_action_ready = _nav_client.wait_for_server(
            timeout_sec=float(os.environ.get("TIAGO_NAV2_WAIT_SEC", "30"))
        )
        if not _nav_action_ready:
            print("[tiago-node] WARNING: navigate_to_pose action server not ready; using /goal_pose fallback")

    executor = MultiThreadedExecutor()
    executor.add_node(node)

    print("[tiago-node] ROS2 subscriptions active")
    while _rclpy.ok():
        executor.spin_once(timeout_sec=0.05)
        while True:
            try:
                gid, x, y, yaw, frame_id = _nav_queue.get_nowait()
            except queue.Empty:
                break
            _dispatch_nav_goal(node, gid, x, y, yaw, frame_id)


# ── MCP interface metadata helpers ────────────────────────────────────────────

def _single_tool_meta(tool_name: str, description: str, input_schema: dict) -> str:
    return json.dumps({
        "tools": [{
            "name": tool_name,
            "description": description,
            "input_schema": input_schema,
        }]
    })


def _start_mcp_http(port: int) -> None:
    import uvicorn
    app = mcp.streamable_http_app()
    uvicorn.run(app, host="0.0.0.0", port=port, log_level="warning")


def _pick_grpc_listen_port() -> int:
    raw = os.environ.get("ROBONIX_PRM_GRPC_LISTEN_PORT", "").strip()
    if raw.isdigit():
        p = int(raw)
        if 1 <= p <= 65535:
            return p
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    s.bind(("0.0.0.0", 0))
    p = int(s.getsockname()[1])
    s.close()
    return p


def _jpeg_to_sensor_image_proto(jpg: bytes):
    from PIL import Image as PILImage
    im = PILImage.open(BytesIO(jpg))
    w, h = im.size
    img = sensor_msgs_pb2.Image()
    img.header.frame_id = os.environ.get("TIAGO_RGB_FRAME_ID", "head_front_camera_rgb_optical_frame")
    now = time.time()
    img.header.stamp.sec = int(now)
    img.header.stamp.nanosec = int((now % 1) * 1e9) % 1_000_000_000
    img.width = w
    img.height = h
    img.encoding = "jpeg"
    img.is_bigendian = 0
    img.step = len(jpg)
    img.data = jpg
    return img


class _PrmCameraRgbServicer(robonix_contracts_pb2_grpc.PrmCameraRgbServicer):
    """Implements contract `robonix/prm/camera/rgb` (PrmCameraRgb.Stream gRPC)."""

    def Stream(self, request: empty_pb2.Empty, context):
        _ = request
        hz = float(os.environ.get("TIAGO_RGB_STREAM_HZ", "2"))
        period = 1.0 / max(hz, 0.25)
        while context.is_active():
            with _lock:
                jpg = _latest_rgb
            if jpg:
                try:
                    yield _jpeg_to_sensor_image_proto(jpg)
                except Exception as e:
                    print(f"[tiago-node] gRPC PrmCameraRgb.Stream encode error: {e}")
            time.sleep(period)


def _run_grpc_prm_server(port: int) -> None:
    server = grpc.server(_grpc_futures.ThreadPoolExecutor(max_workers=4))
    robonix_contracts_pb2_grpc.add_PrmCameraRgbServicer_to_server(_PrmCameraRgbServicer(), server)
    server.add_insecure_port(f"0.0.0.0:{port}")
    server.start()
    print(f"[tiago-node] robonix.contracts.PrmCameraRgb (Stream) on 0.0.0.0:{port}")
    server.wait_for_termination()


def _pick_mcp_listen_port() -> int:
    raw = os.environ.get("ROBONIX_MCP_LISTEN_PORT", "").strip()
    if raw.isdigit():
        p = int(raw)
        if 1 <= p <= 65535:
            return p
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    s.bind(("127.0.0.1", 0))
    p = int(s.getsockname()[1])
    s.close()
    return p


def _heartbeat_loop(stub: pb_grpc.RobonixRuntimeStub, node_id: str) -> None:
    while True:
        time.sleep(15.0)
        try:
            stub.NodeHeartbeat(pb.NodeHeartbeatRequest(node_id=node_id))
        except Exception as e:
            print(f"[tiago-node] heartbeat failed: {e}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    global _RGB_ROS_TOPIC

    channel = grpc.insecure_channel(os.environ.get("ROBONIX_ATLAS", "localhost:50051"))
    stub = pb_grpc.RobonixRuntimeStub(channel)
    node_id = os.environ.get("ROBONIX_NODE_ID", "com.robonix.prm.tiago")

    stub.RegisterNode(
        pb.RegisterNodeRequest(
            node_id=node_id,
            namespace="robonix/prm",
            kind="primitive",
            skill_md="",
            distro=os.environ.get("ROBONIX_DISTRO", "humble"),
            container_id=os.environ.get("ROBONIX_CONTAINER_ID", ""),
        )
    )

    mcp_port = _pick_mcp_listen_port()

    # ── One DeclareInterface per contract ──────────────────────────────────────

    # robonix/prm/camera/snapshot — Empty → Image
    stub.DeclareInterface(pb.DeclareInterfaceRequest(
        node_id=node_id, name="camera_snapshot",
        supported_transports=["mcp"],
        metadata_json=_single_tool_meta(
            "camera_snapshot",
            "Get current RGB camera image. Returns sensor_msgs/Image (JPEG data base64-encoded).",
            Empty.json_schema(),
        ),
        listen_port=mcp_port,
        contract_id="robonix/prm/camera/snapshot",
    ))

    # robonix/prm/camera/depth_snapshot — Empty → Image
    stub.DeclareInterface(pb.DeclareInterfaceRequest(
        node_id=node_id, name="camera_depth_snapshot",
        supported_transports=["mcp"],
        metadata_json=_single_tool_meta(
            "camera_depth_snapshot",
            "Get current depth image (grayscale JPEG). Returns sensor_msgs/Image.",
            Empty.json_schema(),
        ),
        listen_port=mcp_port,
        contract_id="robonix/prm/camera/depth_snapshot",
    ))

    # robonix/prm/robot/state — Empty → RobotState
    stub.DeclareInterface(pb.DeclareInterfaceRequest(
        node_id=node_id, name="robot_state",
        supported_transports=["mcp"],
        metadata_json=_single_tool_meta(
            "robot_state",
            "Get robot state (pose, joints, gripper). Returns prm_base/RobotState.",
            Empty.json_schema(),
        ),
        listen_port=mcp_port,
        contract_id="robonix/prm/robot/state",
    ))

    # robonix/prm/sensor/lidar_snapshot — Empty → LaserScan
    stub.DeclareInterface(pb.DeclareInterfaceRequest(
        node_id=node_id, name="lidar_snapshot",
        supported_transports=["mcp"],
        metadata_json=_single_tool_meta(
            "lidar_snapshot",
            "Get latest lidar scan. Returns sensor_msgs/LaserScan.",
            Empty.json_schema(),
        ),
        listen_port=mcp_port,
        contract_id="robonix/prm/sensor/lidar_snapshot",
    ))

    # robonix/prm/base/navigate — PoseStamped → String
    stub.DeclareInterface(pb.DeclareInterfaceRequest(
        node_id=node_id, name="base_navigate",
        supported_transports=["mcp"],
        metadata_json=_single_tool_meta(
            "base_navigate",
            "Navigate to pose. Arguments: geometry_msgs/PoseStamped wire JSON. Returns std_msgs/String (goal_id in data).",
            PoseStamped.json_schema(),
        ),
        listen_port=mcp_port,
        contract_id="robonix/prm/base/navigate",
    ))

    # robonix/prm/base/nav_status — String → String
    stub.DeclareInterface(pb.DeclareInterfaceRequest(
        node_id=node_id, name="base_nav_status",
        supported_transports=["mcp"],
        metadata_json=_single_tool_meta(
            "base_nav_status",
            "Get navigation status. std_msgs/String; data is goal_id. Returns std_msgs/String.",
            String.json_schema(),
        ),
        listen_port=mcp_port,
        contract_id="robonix/prm/base/nav_status",
    ))

    # robonix/prm/base/nav_cancel — String → String
    stub.DeclareInterface(pb.DeclareInterfaceRequest(
        node_id=node_id, name="base_nav_cancel",
        supported_transports=["mcp"],
        metadata_json=_single_tool_meta(
            "base_nav_cancel",
            "Cancel navigation goal. std_msgs/String; data is goal_id. Returns std_msgs/String.",
            String.json_schema(),
        ),
        listen_port=mcp_port,
        contract_id="robonix/prm/base/nav_cancel",
    ))

    # robonix/prm/base/cmd — MoveCommand → String
    stub.DeclareInterface(pb.DeclareInterfaceRequest(
        node_id=node_id, name="base_cmd",
        supported_transports=["mcp"],
        metadata_json=_single_tool_meta(
            "base_cmd",
            "Velocity command. prm_base/MoveCommand wire JSON. Optional wall duration: TIAGO_BASE_CMD_DURATION_SEC. Returns std_msgs/String.",
            MoveCommand.json_schema(),
        ),
        listen_port=mcp_port,
        contract_id="robonix/prm/base/cmd",
    ))

    # ── PRM gRPC camera rgb stream (separate from MCP) ─────────────────────────
    prm_grpc_port = _pick_grpc_listen_port()
    resp_cam_g = stub.DeclareInterface(pb.DeclareInterfaceRequest(
        node_id=node_id, name="rgb",
        supported_transports=["grpc"],
        metadata_json="{}",
        listen_port=prm_grpc_port,
        contract_id="robonix/prm/camera/rgb",
    ))
    resp_cam_r = stub.DeclareInterface(pb.DeclareInterfaceRequest(
        node_id=node_id, name="rgb",
        supported_transports=["ros2"],
        metadata_json="{}",
        listen_port=0,
        contract_id="robonix/prm/camera/rgb",
    ))
    _RGB_ROS_TOPIC = resp_cam_r.allocated_endpoint

    threading.Thread(target=_heartbeat_loop, args=(stub, node_id), daemon=True).start()
    threading.Thread(target=_run_grpc_prm_server, args=(prm_grpc_port,), daemon=True).start()
    print(
        f"[tiago-node] PRM camera rgb gRPC stream endpoint {resp_cam_g.allocated_endpoint}"
    )

    ros_thread = threading.Thread(target=_start_ros2, daemon=True)
    ros_thread.start()

    threading.Thread(target=_start_mcp_http, args=(mcp_port,), daemon=True).start()
    print(f"[tiago-node] MCP HTTP on port {mcp_port} — 8 contract interfaces registered")
    print("[tiago-node] ready")

    try:
        while True:
            time.sleep(1.0)
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main()
