# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: executor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'executor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pilot_pb2 as pilot__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xecutor.proto\x12\x10robonix.executor\x1a\x0bpilot.proto\"5\n\rBatchComplete\x12\x10\n\x08graph_id\x18\x01 \x01(\t\x12\x12\n\nany_failed\x18\x02 \x01(\x08\"\xb9\x01\n\rTaskCallEvent\x12\x12\n\nevent_kind\x18\x01 \x01(\r\x12\x32\n\x07started\x18\x02 \x01(\x0b\x32!.robonix.executor.TaskCallStarted\x12-\n\x06result\x18\x03 \x01(\x0b\x32\x1d.robonix.pilot.TaskCallResult\x12\x31\n\x08\x63omplete\x18\x04 \x01(\x0b\x32\x1f.robonix.executor.BatchComplete\"5\n\x0fTaskCallStarted\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\x12\x11\n\ttool_name\x18\x02 \x01(\t\"z\n\x08ToolSpec\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x19\n\x11input_schema_json\x18\x03 \x01(\t\x12+\n\x07routing\x18\x04 \x01(\x0b\x32\x1a.robonix.pilot.ToolRouting\":\n\x0f\x45xecute_Request\x12\'\n\x05graph\x18\x01 \x01(\x0b\x32\x18.robonix.pilot.TaskGraph\"B\n\x10\x45xecute_Response\x12.\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x1f.robonix.executor.TaskCallEvent\"$\n\x11ListTools_Request\x12\x0f\n\x07refresh\x18\x01 \x01(\x08\"?\n\x12ListTools_Response\x12)\n\x05tools\x18\x01 \x03(\x0b\x32\x1a.robonix.executor.ToolSpecb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'executor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATCHCOMPLETE']._serialized_start=49
  _globals['_BATCHCOMPLETE']._serialized_end=102
  _globals['_TASKCALLEVENT']._serialized_start=105
  _globals['_TASKCALLEVENT']._serialized_end=290
  _globals['_TASKCALLSTARTED']._serialized_start=292
  _globals['_TASKCALLSTARTED']._serialized_end=345
  _globals['_TOOLSPEC']._serialized_start=347
  _globals['_TOOLSPEC']._serialized_end=469
  _globals['_EXECUTE_REQUEST']._serialized_start=471
  _globals['_EXECUTE_REQUEST']._serialized_end=529
  _globals['_EXECUTE_RESPONSE']._serialized_start=531
  _globals['_EXECUTE_RESPONSE']._serialized_end=597
  _globals['_LISTTOOLS_REQUEST']._serialized_start=599
  _globals['_LISTTOOLS_REQUEST']._serialized_end=635
  _globals['_LISTTOOLS_RESPONSE']._serialized_start=637
  _globals['_LISTTOOLS_RESPONSE']._serialized_end=700
# @@protoc_insertion_point(module_scope)
