import json
import os
import sys
import asyncio
import logging
from pathlib import Path

# Suppress verbose gRPC / absl warnings from milvus-lite
os.environ["GRPC_VERBOSITY"] = "ERROR"
os.environ["GLOG_minloglevel"] = "2"
logging.getLogger("absl").setLevel(logging.ERROR)


def _ensure_proto_gen() -> None:
    d = Path(__file__).resolve().parent
    while d.parent != d:
        pg = d / "proto_gen"
        if pg.is_dir() and (pg / "robonix_runtime_pb2.py").exists():
            sys.path.insert(0, str(pg))
            return
        d = d.parent


def _ensure_mcp_types() -> None:
    """Find robonix_mcp_types/ generated by robonix-codegen --lang mcp and add to path."""
    d = Path(__file__).resolve().parent
    while d.parent != d:
        mt = d / "robonix_mcp_types"
        if mt.is_dir() and (mt / "__init__.py").exists():
            if str(mt) not in sys.path:
                sys.path.insert(0, str(mt))
            return
        d = d.parent


def _ensure_robonix_py() -> None:
    """Add the shared Python helper lib (crates/robonix-py) to sys.path.

    Uses `rbnx path robonix-py` when available; falls back to PYTHONPATH
    injected by the package build.sh (rbnx-build/ws/install/setup.bash).
    """
    import subprocess
    try:
        out = subprocess.run(
            ["rbnx", "path", "robonix-py"],
            capture_output=True, text=True, timeout=5, check=False,
        )
        if out.returncode == 0:
            lib = Path(out.stdout.strip())
            if lib.is_dir() and str(lib) not in sys.path:
                sys.path.insert(0, str(lib))
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass  # rbnx not installed → rely on PYTHONPATH set by build.sh


_ensure_robonix_py()

import grpc
import robonix_runtime_pb2 as pb
import robonix_runtime_pb2_grpc as pb_grpc
import std_msgs_mcp

from mcp.server.fastmcp import FastMCP
from memsearch import MemSearch

from robonix_py import mcp_contract

mcp = FastMCP("memsearch_provider")

MEMORY_DIR = os.environ.get("AGENT_MEMORY_DIR", "./agent_memory")
MILVUS_URI = os.environ.get("AGENT_MILVUS_URI", "./agent_milvus.db")

import importlib.util
import shutil
import subprocess


OLLAMA_EMBEDDING_MODEL = "nomic-embed-text"


def _has_onnx() -> bool:
    """Return True iff onnxruntime is importable."""
    try:
        return importlib.util.find_spec("onnxruntime") is not None
    except Exception:
        return False


def _has_ollama() -> tuple[bool, bool]:
    """Return (binary_present, model_pulled)."""
    if shutil.which("ollama") is None:
        return (False, False)
    try:
        # `ollama list` lists locally-cached models, one per line
        out = subprocess.run(
            ["ollama", "list"],
            capture_output=True, text=True, timeout=5,
        )
        model_pulled = OLLAMA_EMBEDDING_MODEL in (out.stdout or "")
        return (True, model_pulled)
    except Exception:
        return (True, False)


def _print_ollama_help_and_exit() -> None:
    """Neither onnx nor ollama available — print install guide and exit."""
    msg = f"""
[memsearch_service] no embedding backend available.

Tried:
  1. onnxruntime  — not importable (install via `pip install onnxruntime` or the Jetson wheel)
  2. ollama       — binary or model not found

To install ollama + the embedding model, run:

  # install ollama (Linux):
  curl -fsSL https://ollama.com/install.sh | sh

  # start the daemon (systemd or manual):
  sudo systemctl enable --now ollama        # systemd
  # or, for a foreground run:
  ollama serve &

  # pull the embedding model:
  ollama pull {OLLAMA_EMBEDDING_MODEL}

Then re-run this service. It will auto-detect ollama.
"""
    print(msg, file=sys.stderr, flush=True)
    sys.exit(2)


def _select_embedding_backend() -> tuple[str, str | None]:
    """Return (provider_name, model_override).

    Preference: onnx > ollama. Exits with help text if neither is usable.
    """
    if _has_onnx():
        logging.info("[memsearch] embedding backend: onnx (onnxruntime detected)")
        return ("onnx", None)

    ollama_bin, ollama_model = _has_ollama()
    if ollama_bin and ollama_model:
        logging.info(
            "[memsearch] embedding backend: ollama (model=%s)",
            OLLAMA_EMBEDDING_MODEL,
        )
        return ("ollama", OLLAMA_EMBEDDING_MODEL)

    if ollama_bin and not ollama_model:
        logging.warning(
            "[memsearch] ollama binary found but model %s not pulled.",
            OLLAMA_EMBEDDING_MODEL,
        )
    _print_ollama_help_and_exit()
    raise SystemExit(2)  # unreachable; for type-checkers


_EMB_PROVIDER, _EMB_MODEL = _select_embedding_backend()

mem = MemSearch(
    paths=[MEMORY_DIR],
    embedding_provider=_EMB_PROVIDER,
    embedding_model=_EMB_MODEL,
    milvus_uri=MILVUS_URI
)


# ── Contract: robonix/srv/memory/search ──────────────────────────────────────

@mcp_contract(
    mcp,
    contract_id="robonix/srv/memory/search",
)
async def search_memory(msg: std_msgs_mcp.String) -> std_msgs_mcp.String:
    """Search the agent's long-term memory for relevant past context, decisions, or user preferences.
    Contract: robonix/srv/memory/search (input/output std_msgs/String)."""
    try:
        results = await mem.search(msg.data, top_k=2)
    except Exception as e:
        logging.warning("[memsearch] search_memory failed (returning empty): %s", e)
        return std_msgs_mcp.String(
            data="No relevant memories found (search unavailable)."
        )
    if not results:
        return std_msgs_mcp.String(data="No relevant memories found.")
    context = "\n\n".join(f"- {m['content']}" for m in results)
    return std_msgs_mcp.String(data=f"Relevant memories:\n{context}")


# ── Contract: robonix/srv/memory/compact ─────────────────────────────────────

@mcp_contract(
    mcp,
    contract_id="robonix/srv/memory/compact",
)
async def compact_memory(msg: std_msgs_mcp.Empty) -> std_msgs_mcp.String:
    """Compact and summarize recent memories. Call this at the end of a session.
    Contract: robonix/srv/memory/compact (input std_msgs/Empty, output std_msgs/String)."""
    _ = msg
    try:
        summary_path = await mem.compact(llm_provider="openai")
        return std_msgs_mcp.String(
            data=f"Memory compacted successfully to {summary_path}."
        )
    except Exception as e:
        return std_msgs_mcp.String(data=f"Failed to compact memory: {e}")


# ── Contract: robonix/srv/memory/save ────────────────────────────────────────

@mcp_contract(
    mcp,
    contract_id="robonix/srv/memory/save",
)
async def save_memory(msg: std_msgs_mcp.String) -> std_msgs_mcp.String:
    """Save an important fact, user preference, or decision to long-term memory.
    Contract: robonix/srv/memory/save (input/output std_msgs/String)."""
    from datetime import date
    p = Path(MEMORY_DIR) / f"{date.today()}_notes.md"
    p.parent.mkdir(parents=True, exist_ok=True)
    with open(p, "a") as f:
        f.write(f"\n{msg.data}\n")
    try:
        await mem.index()
    except Exception as e:
        logging.warning("[memsearch] re-index after save failed: %s", e)
    return std_msgs_mcp.String(data="Memory saved and indexed.")


def _single_tool_meta(tool_name: str, description: str, input_schema: dict) -> str:
    return json.dumps({
        "tools": [{
            "name": tool_name,
            "description": description,
            "input_schema": input_schema,
        }]
    })


def main():
    channel = grpc.insecure_channel(os.environ.get("ROBONIX_ATLAS", "localhost:50051"))
    stub = pb_grpc.RobonixRuntimeStub(channel)

    port = int(os.environ.get("MEMSEARCH_PORT", "50105"))
    endpoint = f"http://127.0.0.1:{port}"
    node_id = "com.robonix.services.memsearch"

    try:
        stub.RegisterNode(
            pb.RegisterNodeRequest(
                node_id=node_id,
                namespace="robonix/srv/memory",
                kind="service",
                skill_md="# Memsearch MCP\nProvides memory search, save, and compact operations.",
            )
        )

        # One DeclareInterface per contract —————————————————————————————————

        # robonix/srv/memory/search
        stub.DeclareInterface(
            pb.DeclareInterfaceRequest(
                node_id=node_id,
                name="search",
                supported_transports=["mcp"],
                metadata_json=_single_tool_meta(
                    "search_memory",
                    "Search agent long-term memory. data: the search query string.",
                    std_msgs_mcp.String.json_schema(),
                ),
                listen_port=port,
                contract_id="robonix/srv/memory/search",
            )
        )

        # robonix/srv/memory/save
        stub.DeclareInterface(
            pb.DeclareInterfaceRequest(
                node_id=node_id,
                name="save",
                supported_transports=["mcp"],
                metadata_json=_single_tool_meta(
                    "save_memory",
                    "Save fact or preference to long-term memory. data: content to save.",
                    std_msgs_mcp.String.json_schema(),
                ),
                listen_port=port,
                contract_id="robonix/srv/memory/save",
            )
        )

        # robonix/srv/memory/compact  (input: Empty → no parameters)
        stub.DeclareInterface(
            pb.DeclareInterfaceRequest(
                node_id=node_id,
                name="compact",
                supported_transports=["mcp"],
                metadata_json=_single_tool_meta(
                    "compact_memory",
                    "Compact and summarize recent memories. No input required.",
                    std_msgs_mcp.Empty.json_schema(),
                ),
                listen_port=port,
                contract_id="robonix/srv/memory/compact",
            )
        )

        print(f"[memsearch-service] Registered node {node_id} — 3 interfaces at {endpoint}")
    except Exception as e:
        print(f"[memsearch-service] Warning: Failed to register with control plane: {e}")

    try:
        asyncio.run(mem.index())
    except Exception as e:
        logging.warning("[memsearch] initial index failed (empty corpus?): %s", e)

    print(f"[memsearch-service] Starting MCP Streamable HTTP server on port {port}...")
    import uvicorn
    logging.getLogger("absl").setLevel(logging.ERROR)
    app = mcp.streamable_http_app()
    uvicorn.run(app, host="127.0.0.1", port=port, log_level="warning")


if __name__ == "__main__":
    main()
