# SPDX-License-Identifier: MulanPSL-2.0
"""Generated protobuf stubs must load in the image that imports them.

A generated `_pb2.py` records the gencode that produced it and refuses to load
on an older runtime. One deployment generates one set of stubs and imports them
from several images, so the generator and every runtime have to sit in the same
protobuf major line.

They did not, and `tiago_health` died at import with

    VersionError: gencode 7.35.1 runtime 6.33.6

because its build called `rbnx codegen` directly -- picking up whatever
protobuf the host had -- while its three sibling drivers went through the
Webots codegen venv, which pins the version the simulator image installs. The
Scene image had separately floated to a different major.

These checks fail on both shapes of that mistake: a Webots package that
generates outside the pinned venv, and a runtime image whose protobuf line
differs from the generator's.
"""

from __future__ import annotations

from pathlib import Path
import re
import unittest

REPO_ROOT = Path(__file__).resolve().parents[2]
CODEGEN_SH = REPO_ROOT / "examples/webots/scripts/run_python_codegen.sh"
WEBOTS_PRIMITIVES = REPO_ROOT / "examples/webots/primitives"
RUNTIME_IMAGES = (
    "system/scene/docker/Dockerfile",
    "examples/webots/sim/bridge/Dockerfile",
)
# Packages that pin the generator themselves, inside their own build script,
# rather than going through the shared venv. Equivalent, and checked below.
SELF_PINNED = {"audio_driver", "audio_client_bridge"}


def _generator_version() -> str:
    m = re.search(r'^PROTOBUF_VERSION="([^"]+)"', CODEGEN_SH.read_text(encoding="utf-8"), re.M)
    assert m, "run_python_codegen.sh no longer pins PROTOBUF_VERSION"
    return m.group(1)


def _pinned(var: str) -> str:
    m = re.search(rf'^{var}="([^"]+)"', CODEGEN_SH.read_text(encoding="utf-8"), re.M)
    assert m, f"run_python_codegen.sh no longer pins {var}"
    return m.group(1)


def _major(version: str) -> int:
    return int(version.split(".")[0])


class GeneratedStubCompatibilityTests(unittest.TestCase):
    def test_webots_packages_generate_with_a_pinned_protobuf(self):
        version = _generator_version()
        for pkg in sorted(p for p in WEBOTS_PRIMITIVES.iterdir() if p.is_dir()):
            build = pkg / "scripts" / "build.sh"
            if not build.exists():
                continue
            text = build.read_text(encoding="utf-8")
            if pkg.name in SELF_PINNED:
                self.assertIn(
                    f'"protobuf=={version}"', text,
                    f"{pkg.name} pins its own generator but not at {version}, "
                    f"which is what the simulator image runs")
                continue
            self.assertIn(
                "run_python_codegen.sh", text,
                f"{pkg.name}/scripts/build.sh calls the code generator directly, so "
                f"it uses whatever protobuf the host has. Stubs generated by a "
                f"newer gencode than the simulator image's runtime fail at import. "
                f"Generate through examples/webots/scripts/run_python_codegen.sh, "
                f"as tiago_camera, tiago_chassis and tiago_lidar do.")

    def test_runtime_images_share_the_generator_major(self):
        want = _major(_generator_version())
        spec = re.compile(r"""["']?protobuf\s*(?:==|>=|~=)\s*([0-9][0-9.]*)""")
        for rel in RUNTIME_IMAGES:
            text = (REPO_ROOT / rel).read_text(encoding="utf-8")
            found = spec.findall(text)
            self.assertTrue(found, f"{rel} installs no protobuf")
            for version in found:
                self.assertEqual(
                    _major(version), want,
                    f"{rel} installs protobuf {version}, but stubs are generated "
                    f"with {_generator_version()}; a runtime in another major "
                    f"line refuses to import them.")


    def test_the_whole_repository_names_one_version_of_each(self):
        """protobuf, grpcio and grpcio-tools are pinned, and pinned alike.

        Every package that generates or imports stubs has to agree, including
        packages in other repositories that install against these. A range lets
        two installs of the same deployment resolve differently, which is how a
        runtime ends up older than the gencode it is asked to load.
        """
        wanted = {
            "protobuf": _generator_version(),
            "grpcio-tools": _pinned("GRPC_TOOLS_VERSION"),
            "grpcio": _pinned("GRPCIO_VERSION"),
        }
        # Anything that states a dependency: images, requirement files, package
        # metadata, and the build scripts that install into a venv.
        globs = ("**/Dockerfile*", "**/requirements*.txt", "**/pyproject.toml",
                 "**/scripts/build.sh")
        skip = ("rbnx-build", "node_modules", ".git", "output", "cache")
        spec = re.compile(
            r"""["']?(protobuf|grpcio-tools|grpcio)\s*(==|>=|<=|~=|>|<)\s*([0-9][0-9.]*)|"""
            r"""^\s*["']?(protobuf|grpcio-tools|grpcio)["']?\s*,?\s*$""",
            re.M)
        offenders = []
        for pattern in globs:
            for path in REPO_ROOT.glob(pattern):
                rel = str(path.relative_to(REPO_ROOT))
                if any(part in rel for part in skip) or not path.is_file():
                    continue
                for m in spec.finditer(path.read_text(encoding="utf-8")):
                    name, op, version, bare = m.group(1), m.group(2), m.group(3), m.group(4)
                    if bare:
                        offenders.append(f"{rel}: '{bare}' has no version at all")
                    elif op != "==" or version != wanted[name]:
                        offenders.append(f"{rel}: {name}{op}{version}, want =={wanted[name]}")
        self.assertEqual(offenders, [], "\n".join([""] + offenders))


if __name__ == "__main__":
    unittest.main()
