# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: skl_spatiallm_detect.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'skl_spatiallm_detect.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1askl_spatiallm_detect.proto\x12\x10spatiallm_detect\"+\n\x16SpatialLMDetectRequest\x12\x11\n\tply_model\x18\x01 \x01(\x0c\"@\n\x14SpatialLMDetectReply\x12\x0b\n\x03txt\x18\x01 \x01(\t\x12\x0b\n\x03rrd\x18\x02 \x01(\x0c\x12\x0e\n\x06status\x18\x03 \x01(\t2m\n\x0fSpatialLMDetect\x12Z\n\x06\x44\x65tect\x12(.spatiallm_detect.SpatialLMDetectRequest\x1a&.spatiallm_detect.SpatialLMDetectReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'skl_spatiallm_detect_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPATIALLMDETECTREQUEST']._serialized_start=48
  _globals['_SPATIALLMDETECTREQUEST']._serialized_end=91
  _globals['_SPATIALLMDETECTREPLY']._serialized_start=93
  _globals['_SPATIALLMDETECTREPLY']._serialized_end=157
  _globals['_SPATIALLMDETECT']._serialized_start=159
  _globals['_SPATIALLMDETECT']._serialized_end=268
# @@protoc_insertion_point(module_scope)
