// SPDX-License-Identifier: MulanPSL-2.0
// Shared in-process state for Executor plan cancellation.

use crate::pb::pilot::{CapabilityCall, CapabilityCallResult};
use robonix_atlas::client::AtlasClient;
use robonix_atlas::pb as atlas_pb;
use robonix_scribe::warn;
use serde::Deserialize;
use std::collections::HashMap;
use std::sync::Arc;
use std::time::Duration;
use tokio::sync::{Mutex, Notify};

const DEFAULT_CANCEL_WAIT_MS: u64 = 5_000;

#[derive(Clone, Default)]
pub struct PlanRuntime {
    inner: Arc<Mutex<HashMap<String, PlanRun>>>,
}

#[derive(Clone)]
pub struct RunningAsyncCall {
    pub call_id: String,
    pub provider_id: String,
    pub cancel_contract: String,
    pub run_id: String,
}

struct PlanRun {
    cancelled: bool,
    running_async: HashMap<String, RunningAsyncCall>,
    /// Notifies `cancel_plan` waiters when this plan leaves the active table.
    done: Arc<Notify>,
}

struct CancelSnapshot {
    /// Completion signal cloned out of `PlanRun` before releasing the runtime lock.
    done: Arc<Notify>,
    async_calls: Vec<RunningAsyncCall>,
}

struct CancelAllSnapshot {
    async_calls: Vec<RunningAsyncCall>,
}

#[derive(Deserialize)]
struct CancelPlanArgs {
    plan_id: String,
    wait_ms: Option<u64>,
}

impl PlanRuntime {
    /// Register a plan before execution starts.
    ///
    /// If a stale entry with the same id exists it is replaced. Plan ids are
    /// UUIDs generated by Pilot, so replacement is only a defensive cleanup path.
    pub async fn register_plan(&self, plan_id: &str) {
        let mut plans = self.inner.lock().await;
        plans.insert(
            plan_id.to_string(),
            PlanRun {
                cancelled: false,
                running_async: HashMap::new(),
                done: Arc::new(Notify::new()),
            },
        );
    }

    /// Mark a plan complete, remove it from the active table, and notify waiters.
    pub async fn complete_plan(&self, plan_id: &str) {
        let done = {
            let mut plans = self.inner.lock().await;
            let Some(run) = plans.remove(plan_id) else {
                return;
            };
            run.done
        };
        done.notify_waiters();
    }

    /// Return whether a registered plan has been cancelled.
    pub async fn is_cancelled(&self, plan_id: &str) -> bool {
        self.inner
            .lock()
            .await
            .get(plan_id)
            .is_some_and(|run| run.cancelled)
    }

    /// Add one async capability call to the plan's cancellation set, or cancel
    /// it immediately if the plan has already been marked cancelled.
    ///
    /// Returns `true` when the call was registered for normal polling. Returns
    /// `false` when the runtime sent the provider cancel contract instead.
    pub async fn register_or_cancel_async_call(
        &self,
        plan_id: &str,
        call: RunningAsyncCall,
        self_provider_id: &str,
        atlas: &mut AtlasClient,
    ) -> bool {
        let cancelled_call = {
            let mut plans = self.inner.lock().await;
            let Some(run) = plans.get_mut(plan_id) else {
                return true;
            };
            if run.cancelled {
                Some(call)
            } else {
                run.running_async.insert(call.call_id.clone(), call);
                None
            }
        };

        if let Some(call) = cancelled_call {
            let _ = cancel_async_call(self_provider_id, &call, atlas).await;
            false
        } else {
            true
        }
    }

    /// Remove an async call once it reaches a terminal state.
    pub async fn unregister_async_call(&self, plan_id: &str, call_id: &str) {
        if let Some(run) = self.inner.lock().await.get_mut(plan_id) {
            run.running_async.remove(call_id);
        }
    }

    /// If a cancelled plan still owns `call_id`, remove it and send its cancel
    /// contract. Calls already claimed by `cancel_plan` become a no-op here.
    pub async fn cancel_async_call_for_plan(
        &self,
        plan_id: &str,
        call_id: &str,
        self_provider_id: &str,
        atlas: &mut AtlasClient,
    ) {
        let running = {
            let mut plans = self.inner.lock().await;
            plans.get_mut(plan_id).and_then(|run| {
                if run.cancelled {
                    run.running_async.remove(call_id)
                } else {
                    None
                }
            })
        };
        // If running_async contains this call, cancel it.
        if let Some(running) = running {
            let _ = cancel_async_call(self_provider_id, &running, atlas).await;
        }
    }

    /// Apply the `cancel_plan` builtin.
    ///
    /// Cancellation is best-effort: future sequence children are skipped by the
    /// executor loop, and currently running async capability calls receive their
    /// sibling cancel contract when available. Synchronous calls already in
    /// progress are allowed to return naturally.
    pub async fn cancel_plan_builtin(
        &self,
        call: &CapabilityCall,
        self_provider_id: &str,
        atlas: &mut AtlasClient,
    ) -> CapabilityCallResult {
        let args: CancelPlanArgs = match serde_json::from_str(&call.args_json) {
            Ok(args) => args,
            Err(e) => return error_result(call, format!("invalid cancel_plan args: {e}")),
        };
        let wait_ms = args.wait_ms.unwrap_or(DEFAULT_CANCEL_WAIT_MS);
        // Get a snapshot so that the planruntime's lock can be released immediately.
        let snapshot = match self.begin_cancel(&args.plan_id).await {
            Ok(snapshot) => snapshot,
            // Cancelling a plan that is no longer in the active table (already
            // finished, already cancelled, or never existed) is a no-op SUCCESS,
            // not an error: the caller's intent — "this plan must not be running"
            // — is already satisfied. Returning an error here makes the planner
            // retry the cancel forever. begin_cancel's only error is unknown-id.
            Err(_) => {
                return CapabilityCallResult {
                    call_id: call.call_id.clone(),
                    provider_id: call.provider_id.clone(),
                    contract_id: call.contract_id.clone(),
                    success: true,
                    output: format!(
                        "RTDL plan '{}' is not running (already finished or cancelled); nothing to cancel.",
                        args.plan_id
                    ),
                    error: String::new(),
                };
            }
        };

        let mut cancel_errors = Vec::new();
        for running in &snapshot.async_calls {
            if let Err(e) = cancel_async_call(self_provider_id, running, atlas).await {
                cancel_errors.push(format!("{}: {e:#}", running.call_id));
            }
        }

        let completed =
            tokio::time::timeout(Duration::from_millis(wait_ms), snapshot.done.notified())
                .await
                .is_ok();

        let mut output = format!(
            "Cancellation was requested for RTDL plan '{}'; cancelled=true, completed={}, async_cancel_attempts={}.",
            args.plan_id,
            completed,
            snapshot.async_calls.len()
        );
        if !cancel_errors.is_empty() {
            output.push_str(" Some async cancel requests failed: ");
            output.push_str(&cancel_errors.join("; "));
        }
        CapabilityCallResult {
            call_id: call.call_id.clone(),
            provider_id: call.provider_id.clone(),
            contract_id: call.contract_id.clone(),
            success: true,
            output,
            error: String::new(),
        }
    }

    /// Cancel every active plan and make best-effort cancel calls for running async work.
    pub async fn cancel_all_plans(&self, self_provider_id: &str, atlas: &mut AtlasClient) -> bool {
        let snapshot = self.begin_cancel_all().await;
        for running in &snapshot.async_calls {
            if let Err(e) = cancel_async_call(self_provider_id, running, atlas).await {
                warn!(
                    "[executor] cancel_all_plans async cancel failed for {}: {e:#}",
                    running.call_id
                );
            }
        }
        true
    }

    /// Mark a plan cancelled and return the state needed by `cancel_plan`.
    ///
    /// This pure runtime step is separated from atlas/MCP cancel calls so tests
    /// can cover unknown-plan and cancellation-state behavior without a live
    /// atlas server.
    async fn begin_cancel(&self, plan_id: &str) -> Result<CancelSnapshot, String> {
        let mut plans = self.inner.lock().await;
        let Some(run) = plans.get_mut(plan_id) else {
            return Err(format!("unknown plan_id '{plan_id}'"));
        };
        run.cancelled = true;
        Ok(CancelSnapshot {
            done: run.done.clone(),
            async_calls: run
                .running_async
                .drain()
                .map(|(_, running)| running)
                .collect(),
        })
    }

    /// Mark every active plan cancelled and drain their async cancel sets into
    /// one snapshot. Provider cancel calls happen after the runtime lock is
    /// released by `cancel_all_plans`.
    async fn begin_cancel_all(&self) -> CancelAllSnapshot {
        let mut plans = self.inner.lock().await;
        let mut async_calls = Vec::new();
        for run in plans.values_mut() {
            run.cancelled = true;
            async_calls.extend(run.running_async.drain().map(|(_, running)| running));
        }
        CancelAllSnapshot { async_calls }
    }
}

/// Call a provider's async cancel contract through atlas/MCP.
///
/// The cancel payload mirrors the status polling payload and sends `run_id`
/// when present. Atlas channels are disconnected after the MCP request returns.
async fn cancel_async_call(
    consumer_id: &str,
    running: &RunningAsyncCall,
    atlas: &mut AtlasClient,
) -> anyhow::Result<()> {
    let args = if running.run_id.is_empty() {
        "{}".to_string()
    } else {
        serde_json::json!({ "run_id": running.run_id }).to_string()
    };
    let cancel_call = CapabilityCall {
        call_id: format!("cancel-{}", uuid::Uuid::new_v4()),
        provider_id: running.provider_id.clone(),
        contract_id: running.cancel_contract.clone(),
        args_json: args,
    };
    let (channel_id, endpoint, _) = atlas
        .connect_capability(
            consumer_id,
            &running.provider_id,
            &running.cancel_contract,
            atlas_pb::Transport::Mcp,
        )
        .await?;
    let result = crate::dispatch::mcp::execute(&cancel_call, &endpoint).await;
    let _ = atlas.disconnect_capability(&channel_id).await;
    if result.success {
        Ok(())
    } else {
        anyhow::bail!("{}", result.error)
    }
}

/// Build a failed capability result for the `cancel_plan` builtin.
fn error_result(call: &CapabilityCall, error: String) -> CapabilityCallResult {
    CapabilityCallResult {
        call_id: call.call_id.clone(),
        provider_id: call.provider_id.clone(),
        contract_id: call.contract_id.clone(),
        success: false,
        output: String::new(),
        error,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn begin_cancel_unknown_plan_fails() {
        let runtime = PlanRuntime::default();
        let err = match runtime.begin_cancel("missing").await {
            Ok(_) => panic!("missing plan should not cancel"),
            Err(err) => err,
        };
        assert!(err.contains("unknown plan_id"));
    }

    #[tokio::test]
    async fn registered_plan_starts_uncancelled_then_flips() {
        let runtime = PlanRuntime::default();
        runtime.register_plan("p").await;
        assert!(!runtime.is_cancelled("p").await);

        runtime.begin_cancel("p").await.unwrap();

        assert!(runtime.is_cancelled("p").await);
    }

    #[tokio::test]
    async fn begin_cancel_drains_async_calls() {
        let runtime = PlanRuntime::default();
        runtime.register_plan("p").await;
        {
            let mut plans = runtime.inner.lock().await;
            plans
                .get_mut("p")
                .unwrap()
                .running_async
                .insert("c".into(), running_call("c"));
        }

        let snapshot = runtime.begin_cancel("p").await.unwrap();

        assert_eq!(snapshot.async_calls.len(), 1);
        let plans = runtime.inner.lock().await;
        assert!(plans.get("p").unwrap().running_async.is_empty());
    }

    #[tokio::test]
    async fn begin_cancel_all_marks_every_plan() {
        let runtime = PlanRuntime::default();
        runtime.register_plan("p1").await;
        runtime.register_plan("p2").await;
        let snapshot = runtime.begin_cancel_all().await;

        assert!(snapshot.async_calls.is_empty());
        assert!(runtime.is_cancelled("p1").await);
        assert!(runtime.is_cancelled("p2").await);
    }

    fn running_call(call_id: &str) -> RunningAsyncCall {
        RunningAsyncCall {
            call_id: call_id.into(),
            provider_id: "provider".into(),
            cancel_contract: "robonix/test/cancel".into(),
            run_id: "r".into(),
        }
    }
}
