// SPDX-License-Identifier: MulanPSL-2.0
// ROS 2 colcon-package generator: capabilities/lib IDL -> a self-contained
// colcon overlay. Robonix pins one canonical definition of every type it
// uses; vendors build their ROS 2 nodes against this overlay (not the
// distro's messages), so the wire types are always the Robonix ones.
//
// Emits, under `<out>/src/`, one ament_cmake interface package per ROS
// package (chassis, geometry_msgs, ...) with package.xml + CMakeLists.txt +
// its msg/srv. Cross-package refs use the `pkg/Type` convention, so
// per-package granularity is the layout the IDL requires.
//
// .msg/.srv are copied raw (preserving constants like `uint8 CMD_INIT=0`
// and comments, which the shared parser drops); normalize_idl only rewrites
// `pkg/msg/Type` refs to rosidl's `pkg/Type` form and defuses `*/` in
// comments.

use anyhow::{Context, Result};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as FmtWrite;
use std::fs;
use std::path::Path;

use super::msg_parser::{MsgResolver, MsgTypeRef};

const PKG_VERSION: &str = "0.1.0";
const MAINTAINER: &str = "robonix";
const MAINTAINER_EMAIL: &str = "robonix@syswonder.org";
const LICENSE: &str = "MulanPSL-2.0";

/// Make a raw `.msg`/`.srv` file safe for rosidl. Two rewrites, both on
/// the code portion / comment portion respectively; constants, the
/// `---` separator and blank lines pass through untouched.
///
/// First, rewrite `pkg/msg/Type` / `pkg/srv/Type` field refs to the
/// `pkg/Type` form rosidl expects (code portion only — trailing
/// comments may legitimately mention the 3-part spelling).
///
/// Second, defuse any literal `*/` in comments: rosidl_generator_c emits
/// a message's description as a C `/* ... */` doc block, so a `*/` inside
/// the text (e.g. `linear_*/angular_*`) closes the comment early and
/// spills the rest as invalid C. Splitting it to `* /` keeps the prose
/// readable without breaking generation.
fn normalize_idl(src: &str) -> String {
    let mut out = String::with_capacity(src.len());
    for line in src.lines() {
        match line.split_once('#') {
            Some((code, comment)) => {
                out.push_str(&code.replace("/msg/", "/").replace("/srv/", "/"));
                out.push('#');
                out.push_str(&comment.replace("*/", "* /"));
            }
            None => out.push_str(&line.replace("/msg/", "/").replace("/srv/", "/")),
        }
        out.push('\n');
    }
    out
}

fn package_xml(pkg: &str, deps: &BTreeSet<String>) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "<?xml version=\"1.0\"?>");
    // NB: no `--` in this comment — illegal inside XML comments.
    let _ = writeln!(s, "<!-- @generated by robonix-codegen (lang ros2) -->");
    let _ = writeln!(s, "<package format=\"3\">");
    let _ = writeln!(s, "  <name>{pkg}</name>");
    let _ = writeln!(s, "  <version>{PKG_VERSION}</version>");
    let _ = writeln!(
        s,
        "  <description>Robonix canonical ROS 2 interfaces — {pkg} (generated).</description>"
    );
    let _ = writeln!(
        s,
        "  <maintainer email=\"{MAINTAINER_EMAIL}\">{MAINTAINER}</maintainer>"
    );
    let _ = writeln!(s, "  <license>{LICENSE}</license>");
    let _ = writeln!(s);
    let _ = writeln!(s, "  <buildtool_depend>ament_cmake</buildtool_depend>");
    let _ = writeln!(
        s,
        "  <buildtool_depend>rosidl_default_generators</buildtool_depend>"
    );
    let _ = writeln!(s);
    for d in deps {
        let _ = writeln!(s, "  <depend>{d}</depend>");
    }
    if !deps.is_empty() {
        let _ = writeln!(s);
    }
    let _ = writeln!(s, "  <exec_depend>rosidl_default_runtime</exec_depend>");
    let _ = writeln!(
        s,
        "  <member_of_group>rosidl_interface_packages</member_of_group>"
    );
    let _ = writeln!(s);
    let _ = writeln!(s, "  <export>");
    let _ = writeln!(s, "    <build_type>ament_cmake</build_type>");
    let _ = writeln!(s, "  </export>");
    let _ = writeln!(s, "</package>");
    s
}

fn cmakelists(pkg: &str, msgs: &[String], srvs: &[String], deps: &BTreeSet<String>) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "# @generated by robonix-codegen --lang ros2");
    let _ = writeln!(s, "cmake_minimum_required(VERSION 3.8)");
    let _ = writeln!(s, "project({pkg})");
    let _ = writeln!(s);
    let _ = writeln!(s, "find_package(ament_cmake REQUIRED)");
    let _ = writeln!(s, "find_package(rosidl_default_generators REQUIRED)");
    for d in deps {
        let _ = writeln!(s, "find_package({d} REQUIRED)");
    }
    let _ = writeln!(s);
    let _ = writeln!(s, "rosidl_generate_interfaces(${{PROJECT_NAME}}");
    for m in msgs {
        let _ = writeln!(s, "  \"msg/{m}.msg\"");
    }
    for sv in srvs {
        let _ = writeln!(s, "  \"srv/{sv}.srv\"");
    }
    if !deps.is_empty() {
        let joined: Vec<&str> = deps.iter().map(|s| s.as_str()).collect();
        let _ = writeln!(s, "  DEPENDENCIES {}", joined.join(" "));
    }
    let _ = writeln!(s, ")");
    let _ = writeln!(s);
    let _ = writeln!(s, "ament_package()");
    s
}

/// Per-package emit plan: which msgs/srvs land in it and what it depends on.
#[derive(Default)]
struct PkgPlan {
    msgs: BTreeSet<String>,
    srvs: BTreeSet<String>,
    deps: BTreeSet<String>,
}

pub fn generate(resolver: &MsgResolver, out_dir: &Path, verbose: bool) -> Result<()> {
    // Bucket every resolved msg/srv into per-package plans, including the
    // standard std_msgs / geometry_msgs / builtin_interfaces families.
    // Robonix pins one canonical definition of every type it uses, so the
    // overlay is self-contained: it carries its own std_msgs etc. rather
    // than depending on the distro's (which may differ field-for-field).
    let mut plans: BTreeMap<String, PkgPlan> = BTreeMap::new();
    for ((pkg, name), spec) in &resolver.cache {
        let plan = plans.entry(pkg.clone()).or_default();
        plan.msgs.insert(name.clone());
        for f in &spec.fields {
            if let MsgTypeRef::Named { package, .. } = &f.type_ref
                && package != pkg
            {
                plan.deps.insert(package.clone());
            }
        }
    }
    for ((pkg, name), srv) in &resolver.srv_cache {
        let plan = plans.entry(pkg.clone()).or_default();
        plan.srvs.insert(name.clone());
        for f in srv.request.fields.iter().chain(srv.response.fields.iter()) {
            if let MsgTypeRef::Named { package, .. } = &f.type_ref
                && package != pkg
            {
                plan.deps.insert(package.clone());
            }
        }
    }

    // Emit.
    let src_root = out_dir.join("src");
    fs::create_dir_all(&src_root)?;
    let mut n_pkgs = 0usize;
    let mut n_msgs = 0usize;
    let mut n_srvs = 0usize;
    for (pkg, plan) in &plans {
        let pkg_dir = src_root.join(pkg);
        let msgs: Vec<String> = plan.msgs.iter().cloned().collect();
        let srvs: Vec<String> = plan.srvs.iter().cloned().collect();

        if !msgs.is_empty() {
            fs::create_dir_all(pkg_dir.join("msg"))?;
        }
        for m in &msgs {
            let Some(path) = resolver.find_msg_path(pkg, m) else {
                if verbose {
                    eprintln!("[robonix-codegen] ros2: missing .msg for {pkg}/{m}, skipping");
                }
                continue;
            };
            let raw =
                fs::read_to_string(&path).with_context(|| format!("read {}", path.display()))?;
            fs::write(
                pkg_dir.join("msg").join(format!("{m}.msg")),
                normalize_idl(&raw),
            )?;
            n_msgs += 1;
        }

        if !srvs.is_empty() {
            fs::create_dir_all(pkg_dir.join("srv"))?;
        }
        for sv in &srvs {
            let Some(path) = resolver.find_srv_path(pkg, sv) else {
                if verbose {
                    eprintln!("[robonix-codegen] ros2: missing .srv for {pkg}/{sv}, skipping");
                }
                continue;
            };
            let raw =
                fs::read_to_string(&path).with_context(|| format!("read {}", path.display()))?;
            fs::write(
                pkg_dir.join("srv").join(format!("{sv}.srv")),
                normalize_idl(&raw),
            )?;
            n_srvs += 1;
        }

        fs::write(pkg_dir.join("package.xml"), package_xml(pkg, &plan.deps))?;
        fs::write(
            pkg_dir.join("CMakeLists.txt"),
            cmakelists(pkg, &msgs, &srvs, &plan.deps),
        )?;
        n_pkgs += 1;
        if verbose {
            eprintln!(
                "[robonix-codegen] ros2: {pkg} ({} msg, {} srv, deps: {})",
                msgs.len(),
                srvs.len(),
                plan.deps.iter().cloned().collect::<Vec<_>>().join(" ")
            );
        }
    }

    eprintln!(
        "[robonix-codegen] ros2: {n_pkgs} packages, {n_msgs} msg, {n_srvs} srv -> {}/src",
        out_dir.display()
    );
    Ok(())
}
