<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robonix_ridlc_e2e</name>
  <version>0.0.1</version>
  <description>End-to-end test nodes for RIDL-generated interfaces.</description>
  <maintainer email="robonix@example.com">robonix</maintainer>
  <license>MulanPSL-2.0</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>robonix_interfaces</depend>
  <depend>robonix_interfaces_ros2</depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
