<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>skill_demo</name>
  <version>0.1.0</version>
  <description>Skill demo: execute command server + client</description>
  <maintainer email="wheatfox17@icloud.com">robonix</maintainer>
  <license>MulanPSL-2.0</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <depend>rclpy</depend>
  <depend>robonix_interfaces</depend>
  <depend>robonix_interfaces_ros2</depend>
  <depend>std_msgs</depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
