# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import composition_interfaces_pb2 as composition__interfaces__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in composition_interfaces_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CompositionInterfacesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListNodes = channel.unary_unary(
                '/robonix.composition_interfaces.CompositionInterfacesService/ListNodes',
                request_serializer=composition__interfaces__pb2.ListNodes_Request.SerializeToString,
                response_deserializer=composition__interfaces__pb2.ListNodes_Response.FromString,
                _registered_method=True)
        self.LoadNode = channel.unary_unary(
                '/robonix.composition_interfaces.CompositionInterfacesService/LoadNode',
                request_serializer=composition__interfaces__pb2.LoadNode_Request.SerializeToString,
                response_deserializer=composition__interfaces__pb2.LoadNode_Response.FromString,
                _registered_method=True)
        self.UnloadNode = channel.unary_unary(
                '/robonix.composition_interfaces.CompositionInterfacesService/UnloadNode',
                request_serializer=composition__interfaces__pb2.UnloadNode_Request.SerializeToString,
                response_deserializer=composition__interfaces__pb2.UnloadNode_Response.FromString,
                _registered_method=True)


class CompositionInterfacesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CompositionInterfacesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNodes,
                    request_deserializer=composition__interfaces__pb2.ListNodes_Request.FromString,
                    response_serializer=composition__interfaces__pb2.ListNodes_Response.SerializeToString,
            ),
            'LoadNode': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadNode,
                    request_deserializer=composition__interfaces__pb2.LoadNode_Request.FromString,
                    response_serializer=composition__interfaces__pb2.LoadNode_Response.SerializeToString,
            ),
            'UnloadNode': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadNode,
                    request_deserializer=composition__interfaces__pb2.UnloadNode_Request.FromString,
                    response_serializer=composition__interfaces__pb2.UnloadNode_Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robonix.composition_interfaces.CompositionInterfacesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robonix.composition_interfaces.CompositionInterfacesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CompositionInterfacesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.composition_interfaces.CompositionInterfacesService/ListNodes',
            composition__interfaces__pb2.ListNodes_Request.SerializeToString,
            composition__interfaces__pb2.ListNodes_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.composition_interfaces.CompositionInterfacesService/LoadNode',
            composition__interfaces__pb2.LoadNode_Request.SerializeToString,
            composition__interfaces__pb2.LoadNode_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.composition_interfaces.CompositionInterfacesService/UnloadNode',
            composition__interfaces__pb2.UnloadNode_Request.SerializeToString,
            composition__interfaces__pb2.UnloadNode_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
