# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: diagnostic_msgs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'diagnostic_msgs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import std_msgs_pb2 as std__msgs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x64iagnostic_msgs.proto\x12\x17robonix.diagnostic_msgs\x1a\x0estd_msgs.proto\"v\n\x0f\x44iagnosticArray\x12(\n\x06header\x18\x01 \x01(\x0b\x32\x18.robonix.std_msgs.Header\x12\x39\n\x06status\x18\x02 \x03(\x0b\x32).robonix.diagnostic_msgs.DiagnosticStatus\"\x88\x01\n\x10\x44iagnosticStatus\x12\r\n\x05level\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x13\n\x0bhardware_id\x18\x04 \x01(\t\x12\x31\n\x06values\x18\x05 \x03(\x0b\x32!.robonix.diagnostic_msgs.KeyValue\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"0\n\x16\x41\x64\x64\x44iagnostics_Request\x12\x16\n\x0eload_namespace\x18\x01 \x01(\t\";\n\x17\x41\x64\x64\x44iagnostics_Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x12\n\x10SelfTest_Request\"j\n\x11SelfTest_Response\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06passed\x18\x02 \x01(\r\x12\x39\n\x06status\x18\x03 \x03(\x0b\x32).robonix.diagnostic_msgs.DiagnosticStatus2\xef\x01\n\x15\x44iagnosticMsgsService\x12s\n\x0e\x41\x64\x64\x44iagnostics\x12/.robonix.diagnostic_msgs.AddDiagnostics_Request\x1a\x30.robonix.diagnostic_msgs.AddDiagnostics_Response\x12\x61\n\x08SelfTest\x12).robonix.diagnostic_msgs.SelfTest_Request\x1a*.robonix.diagnostic_msgs.SelfTest_Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'diagnostic_msgs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DIAGNOSTICARRAY']._serialized_start=66
  _globals['_DIAGNOSTICARRAY']._serialized_end=184
  _globals['_DIAGNOSTICSTATUS']._serialized_start=187
  _globals['_DIAGNOSTICSTATUS']._serialized_end=323
  _globals['_KEYVALUE']._serialized_start=325
  _globals['_KEYVALUE']._serialized_end=363
  _globals['_ADDDIAGNOSTICS_REQUEST']._serialized_start=365
  _globals['_ADDDIAGNOSTICS_REQUEST']._serialized_end=413
  _globals['_ADDDIAGNOSTICS_RESPONSE']._serialized_start=415
  _globals['_ADDDIAGNOSTICS_RESPONSE']._serialized_end=474
  _globals['_SELFTEST_REQUEST']._serialized_start=476
  _globals['_SELFTEST_REQUEST']._serialized_end=494
  _globals['_SELFTEST_RESPONSE']._serialized_start=496
  _globals['_SELFTEST_RESPONSE']._serialized_end=602
  _globals['_DIAGNOSTICMSGSSERVICE']._serialized_start=605
  _globals['_DIAGNOSTICMSGSSERVICE']._serialized_end=844
# @@protoc_insertion_point(module_scope)
