# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import diagnostic_msgs_pb2 as diagnostic__msgs__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in diagnostic_msgs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DiagnosticMsgsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddDiagnostics = channel.unary_unary(
                '/robonix.diagnostic_msgs.DiagnosticMsgsService/AddDiagnostics',
                request_serializer=diagnostic__msgs__pb2.AddDiagnostics_Request.SerializeToString,
                response_deserializer=diagnostic__msgs__pb2.AddDiagnostics_Response.FromString,
                _registered_method=True)
        self.SelfTest = channel.unary_unary(
                '/robonix.diagnostic_msgs.DiagnosticMsgsService/SelfTest',
                request_serializer=diagnostic__msgs__pb2.SelfTest_Request.SerializeToString,
                response_deserializer=diagnostic__msgs__pb2.SelfTest_Response.FromString,
                _registered_method=True)


class DiagnosticMsgsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddDiagnostics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelfTest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiagnosticMsgsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddDiagnostics': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDiagnostics,
                    request_deserializer=diagnostic__msgs__pb2.AddDiagnostics_Request.FromString,
                    response_serializer=diagnostic__msgs__pb2.AddDiagnostics_Response.SerializeToString,
            ),
            'SelfTest': grpc.unary_unary_rpc_method_handler(
                    servicer.SelfTest,
                    request_deserializer=diagnostic__msgs__pb2.SelfTest_Request.FromString,
                    response_serializer=diagnostic__msgs__pb2.SelfTest_Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robonix.diagnostic_msgs.DiagnosticMsgsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robonix.diagnostic_msgs.DiagnosticMsgsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DiagnosticMsgsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddDiagnostics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.diagnostic_msgs.DiagnosticMsgsService/AddDiagnostics',
            diagnostic__msgs__pb2.AddDiagnostics_Request.SerializeToString,
            diagnostic__msgs__pb2.AddDiagnostics_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelfTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.diagnostic_msgs.DiagnosticMsgsService/SelfTest',
            diagnostic__msgs__pb2.SelfTest_Request.SerializeToString,
            diagnostic__msgs__pb2.SelfTest_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
