# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import lifecycle_msgs_pb2 as lifecycle__msgs__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lifecycle_msgs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LifecycleMsgsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChangeState = channel.unary_unary(
                '/robonix.lifecycle_msgs.LifecycleMsgsService/ChangeState',
                request_serializer=lifecycle__msgs__pb2.ChangeState_Request.SerializeToString,
                response_deserializer=lifecycle__msgs__pb2.ChangeState_Response.FromString,
                _registered_method=True)
        self.GetAvailableStates = channel.unary_unary(
                '/robonix.lifecycle_msgs.LifecycleMsgsService/GetAvailableStates',
                request_serializer=lifecycle__msgs__pb2.GetAvailableStates_Request.SerializeToString,
                response_deserializer=lifecycle__msgs__pb2.GetAvailableStates_Response.FromString,
                _registered_method=True)
        self.GetAvailableTransitions = channel.unary_unary(
                '/robonix.lifecycle_msgs.LifecycleMsgsService/GetAvailableTransitions',
                request_serializer=lifecycle__msgs__pb2.GetAvailableTransitions_Request.SerializeToString,
                response_deserializer=lifecycle__msgs__pb2.GetAvailableTransitions_Response.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/robonix.lifecycle_msgs.LifecycleMsgsService/GetState',
                request_serializer=lifecycle__msgs__pb2.GetState_Request.SerializeToString,
                response_deserializer=lifecycle__msgs__pb2.GetState_Response.FromString,
                _registered_method=True)


class LifecycleMsgsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ChangeState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableStates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableTransitions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LifecycleMsgsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChangeState': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeState,
                    request_deserializer=lifecycle__msgs__pb2.ChangeState_Request.FromString,
                    response_serializer=lifecycle__msgs__pb2.ChangeState_Response.SerializeToString,
            ),
            'GetAvailableStates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableStates,
                    request_deserializer=lifecycle__msgs__pb2.GetAvailableStates_Request.FromString,
                    response_serializer=lifecycle__msgs__pb2.GetAvailableStates_Response.SerializeToString,
            ),
            'GetAvailableTransitions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableTransitions,
                    request_deserializer=lifecycle__msgs__pb2.GetAvailableTransitions_Request.FromString,
                    response_serializer=lifecycle__msgs__pb2.GetAvailableTransitions_Response.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=lifecycle__msgs__pb2.GetState_Request.FromString,
                    response_serializer=lifecycle__msgs__pb2.GetState_Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robonix.lifecycle_msgs.LifecycleMsgsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robonix.lifecycle_msgs.LifecycleMsgsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LifecycleMsgsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ChangeState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.lifecycle_msgs.LifecycleMsgsService/ChangeState',
            lifecycle__msgs__pb2.ChangeState_Request.SerializeToString,
            lifecycle__msgs__pb2.ChangeState_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailableStates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.lifecycle_msgs.LifecycleMsgsService/GetAvailableStates',
            lifecycle__msgs__pb2.GetAvailableStates_Request.SerializeToString,
            lifecycle__msgs__pb2.GetAvailableStates_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailableTransitions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.lifecycle_msgs.LifecycleMsgsService/GetAvailableTransitions',
            lifecycle__msgs__pb2.GetAvailableTransitions_Request.SerializeToString,
            lifecycle__msgs__pb2.GetAvailableTransitions_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.lifecycle_msgs.LifecycleMsgsService/GetState',
            lifecycle__msgs__pb2.GetState_Request.SerializeToString,
            lifecycle__msgs__pb2.GetState_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
