# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import nav_msgs_pb2 as nav__msgs__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nav_msgs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NavMsgsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMap = channel.unary_unary(
                '/robonix.nav_msgs.NavMsgsService/GetMap',
                request_serializer=nav__msgs__pb2.GetMap_Request.SerializeToString,
                response_deserializer=nav__msgs__pb2.GetMap_Response.FromString,
                _registered_method=True)
        self.GetPlan = channel.unary_unary(
                '/robonix.nav_msgs.NavMsgsService/GetPlan',
                request_serializer=nav__msgs__pb2.GetPlan_Request.SerializeToString,
                response_deserializer=nav__msgs__pb2.GetPlan_Response.FromString,
                _registered_method=True)
        self.LoadMap = channel.unary_unary(
                '/robonix.nav_msgs.NavMsgsService/LoadMap',
                request_serializer=nav__msgs__pb2.LoadMap_Request.SerializeToString,
                response_deserializer=nav__msgs__pb2.LoadMap_Response.FromString,
                _registered_method=True)
        self.SetMap = channel.unary_unary(
                '/robonix.nav_msgs.NavMsgsService/SetMap',
                request_serializer=nav__msgs__pb2.SetMap_Request.SerializeToString,
                response_deserializer=nav__msgs__pb2.SetMap_Response.FromString,
                _registered_method=True)


class NavMsgsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NavMsgsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMap,
                    request_deserializer=nav__msgs__pb2.GetMap_Request.FromString,
                    response_serializer=nav__msgs__pb2.GetMap_Response.SerializeToString,
            ),
            'GetPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlan,
                    request_deserializer=nav__msgs__pb2.GetPlan_Request.FromString,
                    response_serializer=nav__msgs__pb2.GetPlan_Response.SerializeToString,
            ),
            'LoadMap': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadMap,
                    request_deserializer=nav__msgs__pb2.LoadMap_Request.FromString,
                    response_serializer=nav__msgs__pb2.LoadMap_Response.SerializeToString,
            ),
            'SetMap': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMap,
                    request_deserializer=nav__msgs__pb2.SetMap_Request.FromString,
                    response_serializer=nav__msgs__pb2.SetMap_Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robonix.nav_msgs.NavMsgsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robonix.nav_msgs.NavMsgsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NavMsgsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.nav_msgs.NavMsgsService/GetMap',
            nav__msgs__pb2.GetMap_Request.SerializeToString,
            nav__msgs__pb2.GetMap_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.nav_msgs.NavMsgsService/GetPlan',
            nav__msgs__pb2.GetPlan_Request.SerializeToString,
            nav__msgs__pb2.GetPlan_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.nav_msgs.NavMsgsService/LoadMap',
            nav__msgs__pb2.LoadMap_Request.SerializeToString,
            nav__msgs__pb2.LoadMap_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.nav_msgs.NavMsgsService/SetMap',
            nav__msgs__pb2.SetMap_Request.SerializeToString,
            nav__msgs__pb2.SetMap_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
