# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import prm_base_pb2 as prm__base__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in prm_base_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PrmBaseServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CancelNavigation = channel.unary_unary(
                '/robonix.prm_base.PrmBaseService/CancelNavigation',
                request_serializer=prm__base__pb2.CancelNavigation_Request.SerializeToString,
                response_deserializer=prm__base__pb2.CancelNavigation_Response.FromString,
                _registered_method=True)
        self.GetNavigationStatus = channel.unary_unary(
                '/robonix.prm_base.PrmBaseService/GetNavigationStatus',
                request_serializer=prm__base__pb2.GetNavigationStatus_Request.SerializeToString,
                response_deserializer=prm__base__pb2.GetNavigationStatus_Response.FromString,
                _registered_method=True)
        self.Navigate = channel.unary_unary(
                '/robonix.prm_base.PrmBaseService/Navigate',
                request_serializer=prm__base__pb2.Navigate_Request.SerializeToString,
                response_deserializer=prm__base__pb2.Navigate_Response.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/robonix.prm_base.PrmBaseService/Stop',
                request_serializer=prm__base__pb2.Stop_Request.SerializeToString,
                response_deserializer=prm__base__pb2.Stop_Response.FromString,
                _registered_method=True)


class PrmBaseServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CancelNavigation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNavigationStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Navigate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrmBaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CancelNavigation': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelNavigation,
                    request_deserializer=prm__base__pb2.CancelNavigation_Request.FromString,
                    response_serializer=prm__base__pb2.CancelNavigation_Response.SerializeToString,
            ),
            'GetNavigationStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNavigationStatus,
                    request_deserializer=prm__base__pb2.GetNavigationStatus_Request.FromString,
                    response_serializer=prm__base__pb2.GetNavigationStatus_Response.SerializeToString,
            ),
            'Navigate': grpc.unary_unary_rpc_method_handler(
                    servicer.Navigate,
                    request_deserializer=prm__base__pb2.Navigate_Request.FromString,
                    response_serializer=prm__base__pb2.Navigate_Response.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=prm__base__pb2.Stop_Request.FromString,
                    response_serializer=prm__base__pb2.Stop_Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robonix.prm_base.PrmBaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robonix.prm_base.PrmBaseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PrmBaseService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CancelNavigation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.prm_base.PrmBaseService/CancelNavigation',
            prm__base__pb2.CancelNavigation_Request.SerializeToString,
            prm__base__pb2.CancelNavigation_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNavigationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.prm_base.PrmBaseService/GetNavigationStatus',
            prm__base__pb2.GetNavigationStatus_Request.SerializeToString,
            prm__base__pb2.GetNavigationStatus_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Navigate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.prm_base.PrmBaseService/Navigate',
            prm__base__pb2.Navigate_Request.SerializeToString,
            prm__base__pb2.Navigate_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.prm_base.PrmBaseService/Stop',
            prm__base__pb2.Stop_Request.SerializeToString,
            prm__base__pb2.Stop_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
