# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: prm_camera.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'prm_camera.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sensor_msgs_pb2 as sensor__msgs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10prm_camera.proto\x12\x12robonix.prm_camera\x1a\x11sensor_msgs.proto\"\x16\n\x14SubscribeRgb_Request\"\'\n\x15SubscribeRgb_Response\x12\x0e\n\x06unused\x18\x01 \x01(\x08\x32j\n\x10PrmCameraService\x12V\n\x0cSubscribeRgb\x12(.robonix.prm_camera.SubscribeRgb_Request\x1a\x1a.robonix.sensor_msgs.Image0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prm_camera_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBSCRIBERGB_REQUEST']._serialized_start=59
  _globals['_SUBSCRIBERGB_REQUEST']._serialized_end=81
  _globals['_SUBSCRIBERGB_RESPONSE']._serialized_start=83
  _globals['_SUBSCRIBERGB_RESPONSE']._serialized_end=122
  _globals['_PRMCAMERASERVICE']._serialized_start=124
  _globals['_PRMCAMERASERVICE']._serialized_end=230
# @@protoc_insertion_point(module_scope)
