# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import prm_camera_pb2 as prm__camera__pb2
import sensor_msgs_pb2 as sensor__msgs__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in prm_camera_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PrmCameraServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeRgb = channel.unary_stream(
                '/robonix.prm_camera.PrmCameraService/SubscribeRgb',
                request_serializer=prm__camera__pb2.SubscribeRgb_Request.SerializeToString,
                response_deserializer=sensor__msgs__pb2.Image.FromString,
                _registered_method=True)


class PrmCameraServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubscribeRgb(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrmCameraServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeRgb': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeRgb,
                    request_deserializer=prm__camera__pb2.SubscribeRgb_Request.FromString,
                    response_serializer=sensor__msgs__pb2.Image.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robonix.prm_camera.PrmCameraService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robonix.prm_camera.PrmCameraService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PrmCameraService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubscribeRgb(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/robonix.prm_camera.PrmCameraService/SubscribeRgb',
            prm__camera__pb2.SubscribeRgb_Request.SerializeToString,
            sensor__msgs__pb2.Image.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
