# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rcl_interfaces_pb2 as rcl__interfaces__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rcl_interfaces_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RclInterfacesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DescribeParameters = channel.unary_unary(
                '/robonix.rcl_interfaces.RclInterfacesService/DescribeParameters',
                request_serializer=rcl__interfaces__pb2.DescribeParameters_Request.SerializeToString,
                response_deserializer=rcl__interfaces__pb2.DescribeParameters_Response.FromString,
                _registered_method=True)
        self.GetParameterTypes = channel.unary_unary(
                '/robonix.rcl_interfaces.RclInterfacesService/GetParameterTypes',
                request_serializer=rcl__interfaces__pb2.GetParameterTypes_Request.SerializeToString,
                response_deserializer=rcl__interfaces__pb2.GetParameterTypes_Response.FromString,
                _registered_method=True)
        self.GetParameters = channel.unary_unary(
                '/robonix.rcl_interfaces.RclInterfacesService/GetParameters',
                request_serializer=rcl__interfaces__pb2.GetParameters_Request.SerializeToString,
                response_deserializer=rcl__interfaces__pb2.GetParameters_Response.FromString,
                _registered_method=True)
        self.ListParameters = channel.unary_unary(
                '/robonix.rcl_interfaces.RclInterfacesService/ListParameters',
                request_serializer=rcl__interfaces__pb2.ListParameters_Request.SerializeToString,
                response_deserializer=rcl__interfaces__pb2.ListParameters_Response.FromString,
                _registered_method=True)
        self.SetParameters = channel.unary_unary(
                '/robonix.rcl_interfaces.RclInterfacesService/SetParameters',
                request_serializer=rcl__interfaces__pb2.SetParameters_Request.SerializeToString,
                response_deserializer=rcl__interfaces__pb2.SetParameters_Response.FromString,
                _registered_method=True)
        self.SetParametersAtomically = channel.unary_unary(
                '/robonix.rcl_interfaces.RclInterfacesService/SetParametersAtomically',
                request_serializer=rcl__interfaces__pb2.SetParametersAtomically_Request.SerializeToString,
                response_deserializer=rcl__interfaces__pb2.SetParametersAtomically_Response.FromString,
                _registered_method=True)


class RclInterfacesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DescribeParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetParameterTypes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetParametersAtomically(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RclInterfacesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DescribeParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeParameters,
                    request_deserializer=rcl__interfaces__pb2.DescribeParameters_Request.FromString,
                    response_serializer=rcl__interfaces__pb2.DescribeParameters_Response.SerializeToString,
            ),
            'GetParameterTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParameterTypes,
                    request_deserializer=rcl__interfaces__pb2.GetParameterTypes_Request.FromString,
                    response_serializer=rcl__interfaces__pb2.GetParameterTypes_Response.SerializeToString,
            ),
            'GetParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParameters,
                    request_deserializer=rcl__interfaces__pb2.GetParameters_Request.FromString,
                    response_serializer=rcl__interfaces__pb2.GetParameters_Response.SerializeToString,
            ),
            'ListParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.ListParameters,
                    request_deserializer=rcl__interfaces__pb2.ListParameters_Request.FromString,
                    response_serializer=rcl__interfaces__pb2.ListParameters_Response.SerializeToString,
            ),
            'SetParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.SetParameters,
                    request_deserializer=rcl__interfaces__pb2.SetParameters_Request.FromString,
                    response_serializer=rcl__interfaces__pb2.SetParameters_Response.SerializeToString,
            ),
            'SetParametersAtomically': grpc.unary_unary_rpc_method_handler(
                    servicer.SetParametersAtomically,
                    request_deserializer=rcl__interfaces__pb2.SetParametersAtomically_Request.FromString,
                    response_serializer=rcl__interfaces__pb2.SetParametersAtomically_Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robonix.rcl_interfaces.RclInterfacesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robonix.rcl_interfaces.RclInterfacesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RclInterfacesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DescribeParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.rcl_interfaces.RclInterfacesService/DescribeParameters',
            rcl__interfaces__pb2.DescribeParameters_Request.SerializeToString,
            rcl__interfaces__pb2.DescribeParameters_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetParameterTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.rcl_interfaces.RclInterfacesService/GetParameterTypes',
            rcl__interfaces__pb2.GetParameterTypes_Request.SerializeToString,
            rcl__interfaces__pb2.GetParameterTypes_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.rcl_interfaces.RclInterfacesService/GetParameters',
            rcl__interfaces__pb2.GetParameters_Request.SerializeToString,
            rcl__interfaces__pb2.GetParameters_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.rcl_interfaces.RclInterfacesService/ListParameters',
            rcl__interfaces__pb2.ListParameters_Request.SerializeToString,
            rcl__interfaces__pb2.ListParameters_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.rcl_interfaces.RclInterfacesService/SetParameters',
            rcl__interfaces__pb2.SetParameters_Request.SerializeToString,
            rcl__interfaces__pb2.SetParameters_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetParametersAtomically(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.rcl_interfaces.RclInterfacesService/SetParametersAtomically',
            rcl__interfaces__pb2.SetParametersAtomically_Request.SerializeToString,
            rcl__interfaces__pb2.SetParametersAtomically_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
