# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vlm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vlm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import robonix_msg_pb2 as robonix__msg__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tvlm.proto\x12\x0brobonix.vlm\x1a\x11robonix_msg.proto\"\x99\x01\n\x0c\x43hat_Request\x12\x32\n\x08messages\x18\x01 \x03(\x0b\x32 .robonix.robonix_msg.ChatMessage\x12,\n\x05tools\x18\x02 \x03(\x0b\x32\x1d.robonix.robonix_msg.ToolSpec\x12\x13\n\x0btool_choice\x18\x03 \x01(\t\x12\x12\n\nmax_tokens\x18\x04 \x01(\x05\"S\n\rChat_Response\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x31\n\ntool_calls\x18\x02 \x03(\x0b\x32\x1d.robonix.robonix_msg.ToolCall\"8\n\x10\x44\x65scribe_Request\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x14\n\x0cimage_base64\x18\x02 \x01(\t\"!\n\x11\x44\x65scribe_Response\x12\x0c\n\x04text\x18\x01 \x01(\t2\x96\x01\n\nVlmService\x12=\n\x04\x43hat\x12\x19.robonix.vlm.Chat_Request\x1a\x1a.robonix.vlm.Chat_Response\x12I\n\x08\x44\x65scribe\x12\x1d.robonix.vlm.Describe_Request\x1a\x1e.robonix.vlm.Describe_Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vlm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHAT_REQUEST']._serialized_start=46
  _globals['_CHAT_REQUEST']._serialized_end=199
  _globals['_CHAT_RESPONSE']._serialized_start=201
  _globals['_CHAT_RESPONSE']._serialized_end=284
  _globals['_DESCRIBE_REQUEST']._serialized_start=286
  _globals['_DESCRIBE_REQUEST']._serialized_end=342
  _globals['_DESCRIBE_RESPONSE']._serialized_start=344
  _globals['_DESCRIBE_RESPONSE']._serialized_end=377
  _globals['_VLMSERVICE']._serialized_start=380
  _globals['_VLMSERVICE']._serialized_end=530
# @@protoc_insertion_point(module_scope)
