#!/usr/bin/env python3
"""ManiSkill3 environment bridge.

Dual-interface node:
  - gRPC EnvDataService: high-bandwidth obs for perception/VLA nodes
  - MCP tools: lightweight commands for robonix-agent
"""
import asyncio
import base64
import json
import logging
import os
import socket
import sys
import threading
import time
from concurrent import futures as _grpc_futures
from io import BytesIO
from pathlib import Path

import numpy as np
from PIL import Image as PILImage

for _n in (
    "mcp", "mcp.server", "mcp.server.streamable_http",
    "mcp.server.streamable_http_manager",
    "httpx", "httpcore", "uvicorn", "uvicorn.access",
):
    logging.getLogger(_n).setLevel(logging.WARNING)

from mcp.server.fastmcp import FastMCP


def _ensure_proto_paths() -> None:
    pkg = Path(__file__).resolve().parent
    sys.path.insert(0, str(pkg))
    d = pkg
    while d.parent != d:
        # Prefer proto_stubs/ (stubs generated with this venv's protobuf version)
        # over proto_gen/ (stubs generated by the system build, may be incompatible).
        pc = d / "proto_stubs"
        pg = d / "proto_gen"
        if pc.is_dir() and (pc / "robonix_runtime_pb2.py").exists():
            sys.path.insert(0, str(pc))
            if pg.is_dir():
                sys.path.append(str(pg))  # fallback for any stubs not in proto_stubs
            return
        if pg.is_dir() and (pg / "robonix_runtime_pb2.py").exists():
            sys.path.insert(0, str(pg))
            return
        d = d.parent


_ensure_proto_paths()

import grpc  # noqa: E402
import robonix_runtime_pb2 as pb  # noqa: E402
import robonix_runtime_pb2_grpc as pb_grpc  # noqa: E402
import maniskill_env_pb2 as env_pb  # noqa: E402
import maniskill_env_pb2_grpc as env_pb_grpc  # noqa: E402

# ── Global state ──────────────────────────────────────────────────────────────

mcp = FastMCP("maniskill-env")

_lock = threading.Lock()
_env = None
_latest_obs = None

# ── Observation helpers ───────────────────────────────────────────────────────


def _to_np(t):
    if hasattr(t, "cpu"):
        return t.cpu().numpy()
    return np.asarray(t)


def _get_camera(obs):
    """Return (rgb, depth) arrays from the first available camera."""
    images = obs.get("sensor_data", obs.get("image", {}))
    if not images:
        raise KeyError("no image data in obs (expected 'sensor_data' or 'image' key)")
    cam = next(iter(images.values()))
    rgb = _to_np(cam["rgb"])
    depth = _to_np(cam.get("depth")) if "depth" in cam else None
    if rgb.ndim == 4:
        rgb = rgb[0]
    if depth is not None and depth.ndim == 4:
        depth = depth[0]
    rgb = np.ascontiguousarray(rgb[:, :, :3]).astype(np.uint8)
    if depth is not None:
        if depth.ndim == 3 and depth.shape[-1] == 1:
            depth = depth[:, :, 0]
        # ManiSkill returns depth as int16/uint16 in millimeters (per ManiSkill docs).
        # Convert to float32 meters so downstream consumers (RTAB-Map 32FC1,
        # Rerun DepthImage meter=1.0) all receive correct scale.
        depth = np.ascontiguousarray(depth).astype(np.float32) / 1000.0
    return rgb, depth


def _get_camera_intrinsics(obs):
    """Return (fx, fy, cx, cy) from the first camera's intrinsic_cv matrix."""
    params = obs.get("sensor_param", {})
    if not params:
        return None
    cam = next(iter(params.values()))
    K = _to_np(cam["intrinsic_cv"])
    if K.ndim == 3:
        K = K[0]
    return float(K[0, 0]), float(K[1, 1]), float(K[0, 2]), float(K[1, 2])


def _get_proprio(obs):
    agent = obs.get("agent", {})
    parts = []
    for k in ("qpos", "qvel"):
        v = agent.get(k)
        if v is not None:
            parts.extend(_to_np(v).flatten().tolist())
    return parts


def _get_camera_extrinsic(obs) -> list[float]:
    """Get T_world_camera (4×4, row-major) from ManiSkill sensor_param.

    ManiSkill's extrinsic_cv is the world-to-camera matrix (OpenCV convention).
    We invert it to get the camera-to-world transform needed by downstream
    consumers (TSDF, RTAB-Map, Rerun).

    Handles two layouts seen across ManiSkill versions / envs:
      • (4, 4) — full homogeneous world-to-camera matrix  (ideal)
      • (3, 4) — [R|t] submatrix, missing the [0,0,0,1] row
    GPU-sim observations also carry a leading batch dimension, so we strip
    any extra leading dimensions before processing.
    """
    params = obs.get("sensor_param", {})
    if not params:
        return []
    cam = next(iter(params.values()))
    ext = _to_np(cam["extrinsic_cv"]).astype(np.float64)

    # Strip leading batch dimensions (GPU sim prepends them even for 1 env).
    while ext.ndim > 2:
        ext = ext[0]

    # Some ManiSkill envs return the 3×4 [R|t] form rather than 4×4.
    if ext.shape == (3, 4):
        ext = np.vstack([ext, [0.0, 0.0, 0.0, 1.0]])

    if ext.shape != (4, 4):
        return []  # Unexpected shape — skip rather than crash

    T_world_cam = np.linalg.inv(ext)
    return T_world_cam.flatten().tolist()


def _get_extra(obs):
    """Extract extra info: tcp_pose, goal_pos, is_grasped."""
    extra = obs.get("extra", {})
    result = {}
    for k in ("tcp_pose", "goal_pos"):
        v = extra.get(k)
        if v is not None:
            result[k] = _to_np(v).flatten().tolist()
    if "is_grasped" in extra:
        result["is_grasped"] = _bool_scalar(extra["is_grasped"])
    return result


def _rgb_to_jpeg(rgb: np.ndarray) -> bytes:
    buf = BytesIO()
    PILImage.fromarray(rgb).save(buf, format="JPEG", quality=85)
    return buf.getvalue()


def _scalar(v):
    return float(v.item()) if hasattr(v, "item") else float(v)


def _bool_scalar(v):
    return bool(v.item() if hasattr(v, "item") else v)


def _step_env(action_list, repeat_steps: int = 1):
    """Step env under lock, return (obs, reward, done, info_dict).

    repeat_steps holds the same action for multiple simulator steps so motion
    is visible for small delta actions.
    """
    global _latest_obs
    import torch

    act_dim = _env.action_space.shape[-1]
    while len(action_list) < act_dim:
        action_list.append(0.0)
    action = torch.tensor([action_list[:act_dim]], dtype=torch.float32)
    repeat_steps = max(1, min(int(repeat_steps), 200))
    r = 0.0
    done = False
    info = {}
    with _lock:
        for _ in range(repeat_steps):
            obs, reward, terminated, truncated, info = _env.step(action)
            _latest_obs = obs
            r += _scalar(reward)
            done = _bool_scalar(terminated) or _bool_scalar(truncated)
            if done:
                break
    info_dict = {}
    if "success" in info:
        info_dict["success"] = _bool_scalar(info["success"])
    info_dict["applied_steps"] = repeat_steps
    return obs, r, done, info_dict


def _reset_env():
    global _latest_obs
    with _lock:
        obs, _ = _env.reset()
        _latest_obs = obs
    return obs


# ── MCP tools (for robonix-agent) ────────────────────────────────────────────


@mcp.tool()
def get_camera_image() -> str:
    """Get current RGB camera image as base64 JPEG."""
    with _lock:
        obs = _latest_obs
    if obs is None:
        return json.dumps({"error": "environment not initialized"})
    rgb, _ = _get_camera(obs)
    jpeg = _rgb_to_jpeg(rgb)
    return json.dumps({
        "image_base64": base64.b64encode(jpeg).decode("ascii"),
        "format": "jpeg",
        "width": int(rgb.shape[1]),
        "height": int(rgb.shape[0]),
    })


@mcp.tool()
def get_robot_state() -> str:
    """Get robot state: proprio (joints), tcp_pose (end-effector [x,y,z,qx,qy,qz,qw]),
    goal_pos (target object [x,y,z]), is_grasped (bool)."""
    with _lock:
        obs = _latest_obs
    if obs is None:
        return json.dumps({"error": "environment not initialized"})
    state = {"proprio": _get_proprio(obs)}
    state.update(_get_extra(obs))
    return json.dumps(state)


@mcp.tool()
def step_action(action_values: str, hold_steps: int = 8) -> str:
    """Apply action as JSON list of floats.

    Fetch uses 12-DoF: arm(6)+gripper(1)+body(3)+base(2). Shorter lists are
    zero-padded. The same action is held for `hold_steps` simulator steps
    (default 8) so movement is clearly visible.
    """
    vals = json.loads(action_values)
    _, r, done, info_dict = _step_env(vals, repeat_steps=hold_steps)
    return json.dumps({"reward": r, "done": done, "info": info_dict})


def reset_env() -> str:
    """Reset the ManiSkill3 environment."""
    _reset_env()
    return json.dumps({"status": "reset_complete"})


# ── gRPC data service (for perception / VLA nodes) ───────────────────────────


def _obs_to_proto(obs, done=False, reward=0.0):
    """Build Observation protobuf from ManiSkill obs dict."""
    rgb, depth = _get_camera(obs)
    intrinsics = _get_camera_intrinsics(obs)
    extra = _get_extra(obs)
    kwargs = dict(
        rgb=rgb.tobytes(),
        depth=depth.tobytes() if depth is not None else b"",
        width=rgb.shape[1], height=rgb.shape[0],
        proprio=_get_proprio(obs),
        done=done, reward=reward,
    )
    if intrinsics:
        kwargs["fx"], kwargs["fy"], kwargs["cx"], kwargs["cy"] = intrinsics
    if "goal_pos" in extra:
        kwargs["goal_pos"] = extra["goal_pos"]
    cam_pose = _get_camera_extrinsic(obs)
    if cam_pose:
        kwargs["camera_pose"] = cam_pose
    return env_pb.Observation(**kwargs)


class _EnvDataServicer(env_pb_grpc.EnvDataServiceServicer):

    def GetObs(self, request, context):
        with _lock:
            obs = _latest_obs
        if obs is None:
            context.abort(grpc.StatusCode.UNAVAILABLE, "env not initialized")
            return env_pb.Observation()
        return _obs_to_proto(obs)

    def Step(self, request, context):
        obs, r, done, info_dict = _step_env(list(request.values))
        obs_pb = _obs_to_proto(obs, done=done, reward=r)
        return env_pb.StepResult(
            obs=obs_pb, reward=r, done=done,
            info_json=json.dumps(info_dict),
        )

    def Reset(self, request, context):
        obs = _reset_env()
        return _obs_to_proto(obs)


# ── Boilerplate ──────────────────────────────────────────────────────────────


def _pick_port() -> int:
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    s.bind(("0.0.0.0", 0))
    p = s.getsockname()[1]
    s.close()
    return p


def _mcp_tools_list() -> list[dict]:
    async def _list():
        return await mcp.list_tools()
    tools = asyncio.run(_list())
    return [{"name": t.name, "description": t.description or "",
             "input_schema": dict(t.inputSchema)} for t in tools]


def _iface_meta_mcp() -> str:
    return json.dumps({"tools": _mcp_tools_list()})


def _start_mcp_http(port: int) -> None:
    import uvicorn
    app = mcp.streamable_http_app()
    uvicorn.run(app, host="0.0.0.0", port=port, log_level="warning")


def _run_grpc_server(port: int) -> None:
    server = grpc.server(_grpc_futures.ThreadPoolExecutor(max_workers=4))
    env_pb_grpc.add_EnvDataServiceServicer_to_server(_EnvDataServicer(), server)
    server.add_insecure_port(f"0.0.0.0:{port}")
    server.start()
    print(f"[env-node] gRPC EnvDataService on :{port}", file=sys.stderr)
    server.wait_for_termination()


def _heartbeat_loop(stub, node_id: str) -> None:
    while True:
        time.sleep(15.0)
        try:
            stub.NodeHeartbeat(pb.NodeHeartbeatRequest(node_id=node_id))
        except Exception as e:
            print(f"[env-node] heartbeat failed: {e}", file=sys.stderr)


# ── Main ─────────────────────────────────────────────────────────────────────


def main() -> None:
    global _env, _latest_obs

    import gymnasium as gym
    try:
        import mani_skill.envs  # noqa: F401 — registers ManiSkill envs
    except ImportError:
        print("[env-node] ERROR: mani_skill not installed.  pip install mani-skill", file=sys.stderr)
        sys.exit(1)

    # Auto-accept asset downloads (no stdin in background processes)
    os.environ["MS_SKIP_ASSET_DOWNLOAD_PROMPT"] = "1"

    env_id = os.environ.get("MANISKILL_ENV_ID", "ReplicaCADTidyHouseTrain_SceneManipulation-v1")
    control_mode = os.environ.get("MANISKILL_CONTROL_MODE", "pd_ee_delta_pose")
    cam_w = int(os.environ.get("MANISKILL_CAM_W", "640"))
    cam_h = int(os.environ.get("MANISKILL_CAM_H", "480"))
    # Shader presets: minimal (fastest), default (PBR-ish, more texture detail),
    # rt-fast / rt-med / rt (ray-traced, slowest, most photorealistic).
    shader_pack = os.environ.get("MANISKILL_SHADER_PACK", "default").strip()
    print(f"[env-node] creating ManiSkill3 env: {env_id}  control={control_mode}  robot=fetch  cam={cam_w}x{cam_h}  shader={shader_pack}",
          file=sys.stderr)

    sensor_configs = {"width": cam_w, "height": cam_h, "shader_pack": shader_pack}

    try:
        _env = gym.make(
            env_id,
            obs_mode="rgbd",
            control_mode=control_mode,
            robot_uids="fetch",
            render_mode="rgb_array",
            sensor_configs=sensor_configs,
        )
    except FileNotFoundError as exc:
        # Room/scene envs need asset downloads; fall back to PickCube-v1
        print(f"[env-node] WARNING: {exc}", file=sys.stderr)
        print("[env-node] Scene assets missing. Run: ./run.sh setup  (downloads ReplicaCAD)", file=sys.stderr)
        print("[env-node] Falling back to PickCube-v1 (no assets required).", file=sys.stderr)
        env_id = "PickCube-v1"
        _env = gym.make(
            env_id,
            obs_mode="rgbd",
            control_mode=control_mode,
            robot_uids="fetch",
            render_mode="rgb_array",
            sensor_configs=sensor_configs,
        )
    obs, _ = _env.reset()
    _latest_obs = obs
    print("[env-node] env ready", file=sys.stderr)

    server_addr = os.environ.get("ROBONIX_SERVER", "localhost:50051")
    channel = grpc.insecure_channel(server_addr)
    stub = pb_grpc.RobonixRuntimeStub(channel)

    node_id = "com.robonix.demo.maniskill"
    stub.RegisterNode(pb.RegisterNodeRequest(
        node_id=node_id,
        namespace="robonix/prm/sim/maniskill",
        kind="primitive",
    ))

    mcp_port = _pick_port()
    stub.DeclareInterface(pb.DeclareInterfaceRequest(
        node_id=node_id,
        name="mcp_tools",
        supported_transports=["mcp"],
        metadata_json=_iface_meta_mcp(),
        listen_port=mcp_port,
    ))

    grpc_port = _pick_port()
    stub.DeclareInterface(pb.DeclareInterfaceRequest(
        node_id=node_id,
        name="env_data",
        supported_transports=["grpc"],
        metadata_json="{}",
        listen_port=grpc_port,
    ))

    threading.Thread(target=_heartbeat_loop, args=(stub, node_id), daemon=True).start()
    threading.Thread(target=_run_grpc_server, args=(grpc_port,), daemon=True).start()
    threading.Thread(target=_start_mcp_http, args=(mcp_port,), daemon=True).start()

    print(f"[env-node] MCP :{mcp_port}  gRPC :{grpc_port}", file=sys.stderr)
    print("[env-node] ready", file=sys.stderr)

    try:
        while True:
            time.sleep(1.0)
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main()
