#!/usr/bin/env bash
# SPDX-License-Identifier: MulanPSL-2.0
set -euo pipefail

PKG="${RBNX_PACKAGE_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
FLAGS=(--mcp)
[[ "${RBNX_BUILD_CLEAN:-}" == "1" ]] && FLAGS+=(--clean)

# Generate through the Webots codegen venv, as tiago_camera, tiago_chassis and
# tiago_lidar do. Calling `rbnx codegen` directly uses whatever protobuf the
# host happens to have, and a stub generated by a newer gencode than the
# simulator image's runtime fails at import:
#   VersionError: gencode 7.35.1 runtime 6.33.6
# The venv pins the generator to the version that image installs.
echo "[tiago_health/build] rbnx codegen ${FLAGS[*]}"
"$PKG/../../scripts/run_python_codegen.sh" "$PKG" "${FLAGS[@]}"
echo "[tiago_health/build] done."
